# ##############################################################################
#
#  OSIS stands for Open Student Information System. It's an application
#  designed to manage the core business of higher education institutions,
#  such as universities, faculties, institutes and professional schools.
#  The core business involves the administration of students, teachers,
#  courses, programs and so on.
#
#  Copyright (C) 2015-2025 Université catholique de Louvain (http://www.uclouvain.be)
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  A copy of this license - GNU General Public License - is available
#  at the root of the source code of this program.  If not,
#  see http://www.gnu.org/licenses/.
#
# ##############################################################################

from base.models.utils.utils import ChoiceEnum


class TypeCategorieTableauBord(ChoiceEnum):
    ADMISSION = 'ADMISSION'
    DOCTORAT = 'DOCTORAT'


class CategorieTableauBordEnum(ChoiceEnum):
    PRE_ADMISSION = 'PRE_ADMISSION'
    ADMISSION = 'ADMISSION'
    CONFIRMATION = 'CONFIRMATION'
    FORMATION_DOCTORALE = 'FORMATION_DOCTORALE'
    JURY = 'JURY'
    FORMULE_1_DEFENSE_PRIVEE = 'FORMULE_1_DEFENSE_PRIVEE'
    FORMULE_1_SOUTENANCE_PUBLIQUE = 'FORMULE_1_SOUTENANCE_PUBLIQUE'
    FORMULE_2_RECEVABILITE = 'FORMULE_2_RECEVABILITE'
    FORMULE_2_DEFENSE_PRIVEE_SOUTENANCE_PUBLIQUE = 'FORMULE_2_DEFENSE_PRIVEE_SOUTENANCE_PUBLIQUE'
    AUTORISATION_DIFFUSION_THESE = 'AUTORISATION_DIFFUSION_THESE'


class IndicateurTableauBordEnum(ChoiceEnum):
    PRE_ADMISSION_DOSSIER_SOUMIS = 'PRE_ADMISSION_DOSSIER_SOUMIS'
    PRE_ADMISSION_AUTORISE_SIC = 'PRE_ADMISSION_AUTORISE_SIC'
    PRE_ADMISSION_PAS_EN_ORDRE_INSCRIPTION = 'PRE_ADMISSION_PAS_EN_ORDRE_INSCRIPTION'
    PRE_ADMISSION_ECHEANCE_3_MOIS = 'PRE_ADMISSION_ECHEANCE_3_MOIS'
    ADMISSION_DOSSIER_SOUMIS = 'ADMISSION_DOSSIER_SOUMIS'
    ADMISSION_AUTORISE_SIC = 'ADMISSION_AUTORISE_SIC'
    ADMISSION_PAS_EN_ORDRE_INSCRIPTION = 'ADMISSION_PAS_EN_ORDRE_INSCRIPTION'
    CONFIRMATION_ECHEANCE_2_MOIS = 'CONFIRMATION_ECHEANCE_2_MOIS'
    CONFIRMATION_SOUMISE = 'CONFIRMATION_SOUMISE'
    CONFIRMATION_PV_TELEVERSE = 'CONFIRMATION_PV_TELEVERSE'
    CONFIRMATION_REPORT_DATE = 'CONFIRMATION_REPORT_DATE'
    FORMATION_DOCTORALE_VALIDE_PROMOTEUR = 'FORMATION_DOCTORALE_VALIDE_PROMOTEUR'
    JURY_VALIDE_CA = 'JURY_VALIDE_CA'
    JURY_REJET_ADRE = 'JURY_REJET_ADRE'
    JURY_VALIDE_ADRE = 'JURY_VALIDE_ADRE'
    FORMULE_1_DEFENSE_PRIVEE_SOUMISE = 'FORMULE_1_DEFENSE_PRIVEE_SOUMISE'
    FORMULE_1_DEFENSE_PRIVEE_PV_TELEVERSE = 'FORMULE_1_DEFENSE_PRIVEE_PV_TELEVERSE'
    FORMULE_1_SOUTENANCE_PUBLIQUE_SOUMISE = 'FORMULE_1_SOUTENANCE_PUBLIQUE_SOUMISE'
    FORMULE_1_SOUTENANCE_PUBLIQUE_PV_TELEVERSE = 'FORMULE_1_SOUTENANCE_PUBLIQUE_PV_TELEVERSE'
    FORMULE_2_RECEVABILITE_SOUMISE = 'FORMULE_2_RECEVABILITE_SOUMISE'
    FORMULE_2_RECEVABILITE_PV_TELEVERSE = 'FORMULE_2_RECEVABILITE_PV_TELEVERSE'
    FORMULE_2_DEFENSE_PRIVEE_SOUTENANCE_PUBLIQUE_SOUMISE = 'FORMULE_2_DEFENSE_PRIVEE_SOUTENANCE_PUBLIQUE_SOUMISE'
    FORMULE_2_DEFENSE_PRIVEE_PV_TELEVERSE = 'FORMULE_2_DEFENSE_PRIVEE_PV_TELEVERSE'
    FORMULE_2_SOUTENANCE_PUBLIQUE_PV_TELEVERSE = 'FORMULE_2_SOUTENANCE_PUBLIQUE_PV_TELEVERSE'
    AUTORISATION_DIFFUSION_THESE_ECHEANCE_15_JOURS = 'AUTORISATION_DIFFUSION_THESE_ECHEANCE_15_JOURS'
    AUTORISATION_DIFFUSION_THESE_REJET_ADRE = 'AUTORISATION_DIFFUSION_THESE_REJET_ADRE'
    AUTORISATION_DIFFUSION_THESE_REJET_SCEB = 'AUTORISATION_DIFFUSION_THESE_REJET_SCEB'
