openapi: 3.0.0
info:
  title: Admission API
  version: ''
  description: This API delivers data for the Admission project.
  contact:
    name: UCLouvain - OSIS
    url: https://github.com/uclouvain/osis
paths:
  /propositions:
    get:
      operationId: list_propositions
      description: ''
      parameters:
      - $ref: '#/components/parameters/Accept-Language'
      - $ref: '#/components/parameters/X-User-FirstName'
      - $ref: '#/components/parameters/X-User-LastName'
      - $ref: '#/components/parameters/X-User-Email'
      - $ref: '#/components/parameters/X-User-GlobalID'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PropositionSearchDTO'
          description: ''
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - propositions
    post:
      operationId: create_proposition
      description: ''
      parameters:
      - $ref: '#/components/parameters/Accept-Language'
      - $ref: '#/components/parameters/X-User-FirstName'
      - $ref: '#/components/parameters/X-User-LastName'
      - $ref: '#/components/parameters/X-User-Email'
      - $ref: '#/components/parameters/X-User-GlobalID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitierPropositionCommand'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PropositionIdentityDTO'
          description: ''
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - propositions
  /propositions/{uuid}:
    get:
      operationId: retrieve_proposition
      description: Get a single proposition
      parameters:
      - name: uuid
        in: path
        required: true
        description: ''
        schema:
          type: string
      - $ref: '#/components/parameters/Accept-Language'
      - $ref: '#/components/parameters/X-User-FirstName'
      - $ref: '#/components/parameters/X-User-LastName'
      - $ref: '#/components/parameters/X-User-Email'
      - $ref: '#/components/parameters/X-User-GlobalID'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PropositionDTO'
          description: ''
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - propositions
    put:
      operationId: update_proposition
      description: Edit a proposition
      parameters:
      - name: uuid
        in: path
        required: true
        description: ''
        schema:
          type: string
      - $ref: '#/components/parameters/Accept-Language'
      - $ref: '#/components/parameters/X-User-FirstName'
      - $ref: '#/components/parameters/X-User-LastName'
      - $ref: '#/components/parameters/X-User-Email'
      - $ref: '#/components/parameters/X-User-GlobalID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleterPropositionCommand'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PropositionIdentityDTO'
          description: ''
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - propositions
      tags:
      - propositions
  /autocomplete/sector:
    get:
      operationId: listSectorDTOs
      description: Autocomplete sectors
      parameters:
      - $ref: '#/components/parameters/Accept-Language'
      - $ref: '#/components/parameters/X-User-FirstName'
      - $ref: '#/components/parameters/X-User-LastName'
      - $ref: '#/components/parameters/X-User-Email'
      - $ref: '#/components/parameters/X-User-GlobalID'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SectorDTO'
          description: ''
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - autocomplete
  /autocomplete/sector/{sigle}/doctorates:
    get:
      operationId: listDoctoratDTOs
      description: Autocomplete doctorates given a sector
      parameters:
      - name: sigle
        in: path
        required: true
        description: ''
        schema:
          type: string
      - $ref: '#/components/parameters/Accept-Language'
      - $ref: '#/components/parameters/X-User-FirstName'
      - $ref: '#/components/parameters/X-User-LastName'
      - $ref: '#/components/parameters/X-User-Email'
      - $ref: '#/components/parameters/X-User-GlobalID'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DoctoratDTO'
          description: ''
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
      - autocomplete
components:
  schemas:
    PropositionSearchDTO:
      type: object
      properties:
        uuid:
          type: string
        type_admission:
          type: string
        sigle_doctorat:
          type: string
        intitule_doctorat_fr:
          type: string
        intitule_doctorat_en:
          type: string
        matricule_candidat:
          type: string
        code_secteur_formation:
          type: string
        bureau_CDE:
          type: string
        created_at:
          type: string
          format: date-time
      required:
      - uuid
      - type_admission
      - sigle_doctorat
      - intitule_doctorat_fr
      - intitule_doctorat_en
      - matricule_candidat
      - code_secteur_formation
      - created_at
    PropositionDTO:
      type: object
      properties:
        type_admission:
          type: string
        justification:
          type: string
        sigle_doctorat:
          type: string
        annee_doctorat:
          type: integer
        intitule_doctorat_fr:
          type: string
        intitule_doctorat_en:
          type: string
        matricule_candidat:
          type: string
        code_secteur_formation:
          type: string
        bureau_CDE:
          type: string
        type_financement:
          type: string
        type_contrat_travail:
          type: string
        eft:
          type: integer
          nullable: true
        bourse_recherche:
          type: string
        duree_prevue:
          type: integer
          nullable: true
        temps_consacre:
          type: integer
          nullable: true
        titre_projet:
          type: string
        resume_projet:
          type: string
        documents_projet:
          type: array
          items:
            type: string
        graphe_gantt:
          type: array
          items:
            type: string
        proposition_programme_doctoral:
          type: array
          items:
            type: string
        projet_formation_complementaire:
          type: array
          items:
            type: string
        langue_redaction_these:
          type: string
        doctorat_deja_realise:
          type: string
        institution:
          type: string
        date_soutenance:
          type: string
          format: date
          nullable: true
        raison_non_soutenue:
          type: string
      required:
      - type_admission
      - sigle_doctorat
      - annee_doctorat
      - intitule_doctorat_fr
      - intitule_doctorat_en
      - matricule_candidat
      - code_secteur_formation
      - documents_projet
      - graphe_gantt
      - proposition_programme_doctoral
      - projet_formation_complementaire
      - langue_redaction_these
      - doctorat_deja_realise
    SectorDTO:
      type: object
      properties:
        sigle:
          type: string
          readOnly: true
        intitule_fr:
          type: string
          readOnly: true
        intitule_en:
          type: string
          readOnly: true
    DoctoratDTO:
      type: object
      properties:
        sigle:
          type: string
        annee:
          type: integer
        intitule_fr:
          type: string
        intitule_en:
          type: string
        sigle_entite_gestion:
          type: string
      required:
      - sigle
      - annee
      - intitule_fr
      - intitule_en
      - sigle_entite_gestion
    PropositionIdentityDTO:
      type: object
      properties:
        uuid:
          type: string
          readOnly: true
    InitierPropositionCommand:
      type: object
      properties:
        type_admission:
          $ref: '#/components/responses/AdmissionType'
        sigle_formation:
          type: string
        annee_formation:
          type: integer
        matricule_candidat:
          type: string
        justification:
          type: string
        bureau_CDE:
          $ref: '#/components/responses/ChoixBureauCDE'
          nullable: true
        type_financement:
          type: string
        type_contrat_travail:
          type: string
        eft:
          type: integer
          nullable: true
        bourse_recherche:
          type: string
        duree_prevue:
          type: integer
          nullable: true
        temps_consacre:
          type: integer
          nullable: true
        titre_projet:
          type: string
        resume_projet:
          type: string
        documents_projet:
          type: array
          items:
            type: string
        graphe_gantt:
          type: array
          items:
            type: string
        proposition_programme_doctoral:
          type: array
          items:
            type: string
        projet_formation_complementaire:
          type: array
          items:
            type: string
        langue_redaction_these:
          $ref: '#/components/responses/ChoixLangueRedactionThese'
          default: UNDECIDED
        doctorat_deja_realise:
          $ref: '#/components/responses/ChoixDoctoratDejaRealise'
          default: 'NO'
        institution:
          type: string
        date_soutenance:
          type: string
          format: date
          nullable: true
        raison_non_soutenue:
          type: string
      required:
      - type_admission
      - sigle_formation
      - annee_formation
      - matricule_candidat
      - documents_projet
      - graphe_gantt
      - proposition_programme_doctoral
      - projet_formation_complementaire
    AdmissionType:
      enum:
      - ADMISSION
      - PRE_ADMISSION
      type: string
    ChoixBureauCDE:
      enum:
      - ECONOMY
      - MANAGEMENT
      type: string
    ChoixLangueRedactionThese:
      enum:
      - FRENCH
      - ENGLISH
      - UNDECIDED
      type: string
    ChoixDoctoratDejaRealise:
      enum:
      - 'YES'
      - 'NO'
      - PARTIAL
      type: string
    CompleterPropositionCommand:
      type: object
      properties:
        uuid:
          type: string
        type_admission:
          $ref: '#/components/responses/AdmissionType'
        justification:
          type: string
        bureau_CDE:
          $ref: '#/components/responses/ChoixBureauCDE'
          nullable: true
        type_financement:
          type: string
        type_contrat_travail:
          type: string
        eft:
          type: integer
          nullable: true
        bourse_recherche:
          type: string
        duree_prevue:
          type: integer
          nullable: true
        temps_consacre:
          type: integer
          nullable: true
        titre_projet:
          type: string
        resume_projet:
          type: string
        documents_projet:
          type: array
          items:
            type: string
        graphe_gantt:
          type: array
          items:
            type: string
        proposition_programme_doctoral:
          type: array
          items:
            type: string
        projet_formation_complementaire:
          type: array
          items:
            type: string
        langue_redaction_these:
          $ref: '#/components/responses/ChoixLangueRedactionThese'
          default: UNDECIDED
        doctorat_deja_realise:
          $ref: '#/components/responses/ChoixDoctoratDejaRealise'
          default: 'NO'
        institution:
          type: string
        date_soutenance:
          type: string
          format: date
          nullable: true
        raison_non_soutenue:
          type: string
      required:
      - uuid
      - type_admission
      - documents_projet
      - graphe_gantt
      - proposition_programme_doctoral
      - projet_formation_complementaire
    DefinirCotutelleCommand:
      type: object
      properties:
        uuid_proposition:
          type: string
        motivation:
          type: string
        institution:
          type: string
        document_demande_ouverture:
          type: array
          items:
            type: string
      required:
      - uuid_proposition
      - document_demande_ouverture
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
      - code
      - message
    AcceptedLanguageEnum:
      type: string
      enum:
      - en
      - fr-be
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your token in the format **Token &lt;token>**
  parameters:
    X-User-FirstName:
      in: header
      name: X-User-FirstName
      schema:
        type: string
      required: false
    X-User-LastName:
      in: header
      name: X-User-LastName
      schema:
        type: string
      required: false
    X-User-Email:
      in: header
      name: X-User-Email
      schema:
        type: string
      required: false
    X-User-GlobalID:
      in: header
      name: X-User-GlobalID
      schema:
        type: string
      required: false
    Accept-Language:
      in: header
      name: Accept-Language
      description: The header advertises which languages the client is able to understand,
        and which locale variant is preferred. (By languages, we mean natural languages,
        such as English, and not programming languages.)
      schema:
        $ref: '#/components/schemas/AcceptedLanguageEnum'
      required: false
  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
servers:
- url: https://{environment}.osis.uclouvain.be/api/v1/admission/
  variables:
    environment:
      default: dev
      enum:
      - dev
      - qa
      - test
- url: https://osis.uclouvain.be/api/v1/admission/
  description: Production server
security:
- Token: []
