# Generated by Django 2.2.13 on 2021-03-29 18:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorateAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('ADMISSION', 'Admission'), ('PRE_ADMISSION', 'Pre-Admission')], db_index=True, max_length=255, verbose_name='Type')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='base.Person', verbose_name='Author')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='base.Person', verbose_name='Candidate')),
            ],
            options={
                'verbose_name': 'Doctorate admission',
                'ordering': ('-created',),
            },
        ),
    ]
