# Generated by Django 2.2.13 on 2021-10-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0004_supervision_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisionactor',
            name='type',
            field=models.CharField(default=(('PROMOTER', 'Supervisor'), ('CA_MEMBER', 'CA Member')), max_length=50),
        ),
    ]
