# Generated by Django 2.2.13 on 2021-11-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_remove_main_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorateadmission',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('SUBMITTED', 'SUBMITTED')], default='IN_PROGRESS', max_length=30),
        ),
    ]
