# Generated by Django 2.2.13 on 2021-11-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0007_doctorateadmission_cotutelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorateadmission',
            name='thesis_institute',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Thesis institute'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='thesis_location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Thesis location'),
        ),
    ]
