# Generated by Django 2.2.13 on 2021-11-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0008_thesis_location_institute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='thesis_language',
            field=models.CharField(blank=True, choices=[('FRENCH', 'French'), ('ENGLISH', 'English'), ('OTHER', 'Other'), ('UNDECIDED', 'Undecided')], default='', max_length=255, verbose_name='Thesis language'),
        ),
    ]
