# Generated by Django 2.2.13 on 2021-12-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_doctorateadmission_recommendation_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='status',
            field=models.CharField(choices=[('CANCELLED', 'CANCELLED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('SUBMITTED', 'SUBMITTED'), ('SIGNING_IN_PROGRESS', 'SIGNING_IN_PROGRESS')], default='IN_PROGRESS', max_length=30),
        ),
    ]
