# Generated by Django 2.2.24 on 2021-12-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0010_doctorateadmission_recommendation_letters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='thesis_institute',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='base.EntityVersion',
                verbose_name='Thesis institute',
            ),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='other_thesis_location',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                verbose_name='Other thesis location'
            ),
        ),
    ]
