# Generated by Django 2.2.24 on 2022-01-06 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20211216_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorateadmission',
            options={'ordering': ('-created',), 'permissions': [
                ('access_doctorateadmission', 'Can access doctorate admission list'),
                ('download_jury_approved_pdf', 'Can download jury-approved PDF'),
                ('upload_jury_approved_pdf', 'Can upload jury-approved PDF'),
                ('upload_signed_scholarship', 'Can upload signed scholarship'),
                ('check_publication_authorisation', 'Can check publication autorisation'),
                ('validate_registration', 'Can validate registration'), ('approve_jury', 'Can approve jury'),
                ('approve_confirmation_paper', 'Can approve confirmation paper'),
                ('validate_doctoral_training', 'Can validate doctoral training'),
                ('download_pdf_confirmation', 'Can download PDF confirmation'),
                ('upload_pdf_confirmation', 'Can upload PDF confirmation'), ('fill_thesis', 'Can fill thesis'),
                ('submit_thesis', 'Can submit thesis'), ('appose_cdd_notice', 'Can appose CDD notice'),
                ('appose_sic_notice', 'Can appose SIC notice'), ('upload_defense_report', 'Can upload defense report'),
                ('check_copyright', 'Can check copyright'), ('sign_diploma', 'Can sign diploma'),
                ('approve_proposition', 'Can approve proposition')], 'verbose_name': 'Doctorate admission'},
        ),
        migrations.AddField(
            model_name='supervisionactor',
            name='internal_comment',
            field=models.TextField(blank=True, default='', verbose_name='Internal comment'),
        ),
        migrations.AddField(
            model_name='supervisionactor',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rejection reason'),
        ),
    ]
