# Generated by Django 2.2.13 on 2022-01-03 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0011_auto_20211216_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorateadmission',
            old_name='bureau',
            new_name='proximity_commission_cde',
        ),
    ]
