# Generated by Django 2.2.24 on 2021-12-08 16:36

from django.db import migrations, models


def set_default_references(apps, schema_editor):
    # Assign a default value to the references of the admissions
    doctorate_admission_model = apps.get_model('admission', 'DoctorateAdmission')
    all_admissions = doctorate_admission_model.objects.all()
    for admission in all_admissions:
        admission.reference = "{}-{}".format(
            admission.doctorate.academic_year.year % 100,
            300000 + admission.id,
        )
    doctorate_admission_model.objects.bulk_update(all_admissions, ['reference'])


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0013_doctorateadmission_fk_thesis_institute'),
    ]

    default_args = {
        'editable': False,
        'max_length': 255,
        'unique': True,
        'verbose_name': 'Reference',
        'null': True,
    }

    operations = [
        # Create the new field
        migrations.AddField(
            model_name='doctorateadmission',
            name='reference',
            field=models.CharField(**default_args),
        ),
        # Assign a default value depending on the admission
        migrations.RunPython(set_default_references, migrations.RunPython.noop),
    ]
