# Generated by Django 2.2.13 on 2022-01-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_new_permission_and_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adre',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='adre',
            name='with_child',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='with_child',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='with_child',
        ),
        migrations.RemoveField(
            model_name='jurysecretary',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='jurysecretary',
            name='with_child',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='promoter',
            name='with_child',
        ),
        migrations.RemoveField(
            model_name='sceb',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='sceb',
            name='with_child',
        ),
        migrations.RemoveField(
            model_name='sicdirector',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='sicdirector',
            name='with_child',
        ),
        migrations.RemoveField(
            model_name='sicmanager',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='sicmanager',
            name='with_child',
        ),
    ]
