# Generated by Django 2.2.13 on 2022-01-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_auto_20211025_1239'),
        ('base', '0618_merge_20211215_1448'),
        ('admission', '0015_new_permission_and_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('institute', models.CharField(blank=True, default='', max_length=255, verbose_name='Institute')),
                ('city', models.CharField(blank=True, default='', max_length=255, verbose_name='City')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.Country', verbose_name='Country')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
        ),
    ]
