# Generated by Django 2.2.13 on 2022-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0015_new_permission_and_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='bureau',
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='proximity_commission',
            field=models.CharField(blank=True, choices=[('ECONOMY', 'ECONOMY'), ('MANAGEMENT', 'MANAGEMENT'), ('ECLI', 'Proximity commission for experimental and clinical research (ECLI)'), ('GIM', 'Proximity Commission for Genetics and Immunology (GIM)'), ('NRSC', 'Proximity Commission for Neuroscience (NRSC)'), ('BCM', 'Proximity commission for cellular and molecular biology, biochemistry (BCM)'), ('SPSS', 'Proximity commission for public health, health and society (SPSS)'), ('DENT', 'Proximity Commission for Dental Sciences (DENT)'), ('DFAR', 'Proximity Commission for Pharmaceutical Sciences (DFAR)'), ('MOTR', 'Proximity Commission for Motricity Sciences (MOTR)')], default='', max_length=255, verbose_name='Proximity commission'),
        ),
    ]
