# Generated by Django 2.2.13 on 2022-01-10 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_auto_20211025_1239'),
        ('admission', '0019_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='institute',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='promoter',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='promoter',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='promoter',
            name='institute',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='promoter',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promoter',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title'),
        ),
    ]
