# Generated by Django 2.2.13 on 2022-01-10 15:50

from django.db import migrations

from admission.contrib.models.enums.actor_type import ActorType


def forward(apps, schema_editor):
    SupervisionActor = apps.get_model('admission', 'SupervisionActor')
    Promoter = apps.get_model('admission', 'Promoter')
    CommitteeMember = apps.get_model('admission', 'CommitteeMember')

    Promoter.objects.bulk_create([
        Promoter(person_id=s.actor_ptr.person_id)
        for s in SupervisionActor.objects.filter(type=ActorType.PROMOTER.name).distinct('person')
    ])

    CommitteeMember.objects.bulk_create([
        CommitteeMember(person_id=s.actor_ptr.person_id)
        for s in SupervisionActor.objects.filter(type=ActorType.CA_MEMBER.name).distinct('person')
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('admission', '0020_external_promoter'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
