# Generated by Django 2.2.13 on 2022-01-11 10:21

from django.db import migrations


def forward(apps, schema_editor):
    DoctorateAdmission = apps.get_model('admission', 'DoctorateAdmission')
    Candidate = apps.get_model('admission', 'Candidate')

    candidates = DoctorateAdmission.objects.distinct('candidate_id').order_by('candidate_id').values_list(
        'candidate_id', flat=True,
    )
    Candidate.objects.bulk_create([
        Candidate(person_id=candidate_id)
        for candidate_id in candidates
    ])


class Migration(migrations.Migration):
    dependencies = [
        ('admission', '0022_request_signature_permission'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
