# Generated by Django 2.2.13 on 2022-01-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0024_meta_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='thesis_language',
            field=models.CharField(blank=True, choices=[('FRENCH', 'French'), ('ENGLISH', 'English'), ('OTHER', 'Other'), ('UNDECIDED', 'Undecided')], default='UNDECIDED', max_length=255, verbose_name='Thesis language'),
        ),
    ]
