# Generated by Django 2.2.24 on 2022-02-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0026_doctorateadmission_valuated_experiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='reference',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='Reference'),
        ),
    ]
