# Generated by Django 2.2.24 on 2022-02-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0028_add_submit_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorateadmission',
            name='admission_submission_date',
            field=models.DateField(null=True, verbose_name='Admission submission date'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='pre_admission_submission_date',
            field=models.DateField(null=True, verbose_name='Pre-admission submission date'),
        ),
    ]
