# Generated by Django 2.2.24 on 2022-02-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0029_add_submission_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='other_thesis_location',
        ),
    ]
