# Generated by Django 2.2.24 on 2022-03-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0030_remove_other_thesis_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='admission_submission_date',
            field=models.DateTimeField(null=True, verbose_name='Admission submission date'),
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='pre_admission_submission_date',
            field=models.DateTimeField(null=True, verbose_name='Pre-admission submission date'),
        ),
    ]
