# Generated by Django 2.2.24 on 2022-03-09 15:44

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0031_prefer_datetime_over_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionactor',
            name='pdf_from_candidate',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1, verbose_name='PDF file'),
        ),
    ]
