# Generated by Django 2.2.24 on 2022-03-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0032_remove_empty_contact_addresses'),
        ('admission', '0032_supervisionactor_pdf_from_candidate'),
    ]

    operations = [
    ]
