# Generated by Django 2.2.24 on 2022-03-07 13:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0033_merge_20220310_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorateadmission',
            name='submitted_profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Submitted profile'),
        ),
    ]
