# Generated by Django 2.2.24 on 2022-03-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0034_doctorateadmission_submitted_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admission.doctorateadmission',),
        ),
        migrations.CreateModel(
            name='PropositionProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admission.doctorateadmission',),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='status_cdd',
            field=models.CharField(choices=[('TO_BE_VERIFIED', 'TO_BE_VERIFIED'), ('TO_BE_COMPLETED', 'TO_BE_COMPLETED'), ('ACCEPTED', 'ACCEPTED'), ('REJECTED', 'REJECTED')], default='TO_BE_VERIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='status_sic',
            field=models.CharField(choices=[('TO_BE_VERIFIED', 'TO_BE_VERIFIED'), ('ACKNOWLEDGED', 'ACKNOWLEDGED'), ('TO_BE_COMPLETED', 'TO_BE_COMPLETED'), ('ADMISSIBLE', 'ADMISSIBLE'), ('TO_BE_VALIDATED', 'TO_BE_VALIDATED'), ('INVALID', 'INVALID'), ('VALID', 'VALID'), ('REJECTED', 'REJECTED')], default='TO_BE_VERIFIED', max_length=30),
        ),
    ]
