# Generated by Django 2.2.24 on 2022-03-21 18:37

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0035_demande_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='detailed_status',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
