# Generated by Django 2.2.24 on 2022-03-28 11:55

from django.db import migrations

from admission.mail_templates import (
    ADMISSION_EMAIL_MEMBER_REMOVED,
    ADMISSION_EMAIL_SIGNATURE_CANDIDATE,
    ADMISSION_EMAIL_SIGNATURE_REFUSAL,
    ADMISSION_EMAIL_SIGNATURE_REQUESTS_ACTOR,
    ADMISSION_EMAIL_SIGNATURE_REQUESTS_CANDIDATE,
    ADMISSION_EMAIL_SUBMISSION_CANDIDATE,
    ADMISSION_EMAIL_SUBMISSION_CDD,
    ADMISSION_EMAIL_SUBMISSION_MEMBER,
)
from osis_mail_template import MailTemplateMigration


class Migration(migrations.Migration):
    dependencies = [
        ('admission', '0036_detailed_status_encoder'),
        ('osis_mail_template', '0001_initial'),
    ]

    operations = [
        MailTemplateMigration(
            ADMISSION_EMAIL_SIGNATURE_REQUESTS_CANDIDATE,
            {
                'en': '[OSIS] Signature requests sent successfully',
                'fr-be': '[OSIS] Demande de signature envoyées avec succès',
            },
            {
                'en': '''<p>Hello {candidate_first_name} {candidate_last_name},</p>

<p>Requests for signatures concerning your application to {doctorate_title} have been sent.</p>

<ul>
<li>{actors_as_list_items}</li> 

<p>You will be notified for any action on their part (acceptance or refusal), you can also transfer a document 
attesting their approval for each of them.</p>

<p>---<br/>
The OSIS Team</p>
''',
                'fr-be': '''<p>Bonjour {candidate_first_name} {candidate_last_name},</p>

<p>Les demandes de signatures concernant votre demande d'admission en {doctorate_title} ont bien été envoyées.</p>

<ul>
<li>{actors_as_list_items}</li>
</ul>

<p>Vous serez notifiés pour toute action de leur part (acceptation ou refus), vous pouvez également transférer
un document attestant leur approbation pour chacun d'eux.

<p>---<br/>
L'équipe OSIS</p>
''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_SIGNATURE_REQUESTS_ACTOR,
            {
                'en': '[OSIS] Invite to supervise {candidate_first_name} {candidate_last_name} for {doctorate_title}',
                'fr-be': '[OSIS] Invitation à superviser {candidate_first_name} {candidate_last_name} '
                'pour un {doctorate_title}',
            },
            {
                'en': '''<p>Hello {signataire_first_name} {signataire_last_name},</p>

<p>{candidate_first_name} {candidate_last_name} has added you as {signataire_role} for {doctorate_title}.</p>

<p>Please indicate your approval or refusal and view the admission request by clicking 
on the {admission_link_front} link.</p>

<p>---<br/>
The OSIS Team</p>
''',
                'fr-be': '''<p>Bonjour {signataire_first_name} {signataire_last_name},</p>

<p>{candidate_first_name} {candidate_last_name} vous a ajouté en tant que {signataire_role} 
pour son {doctorate_title}.</p>

<p>Merci d'indiquer votre approbation ou refus et visualiser sa demande en cliquer sur le lien {admission_link_front}.

<p>---<br/>
L'équipe OSIS</p>
''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_SIGNATURE_CANDIDATE,
            {
                'en': '[OSIS] Answer from {signataire_first_name} {signataire_last_name} for {doctorate_title}',
                'fr-be': '[OSIS] Réponse de {signataire_first_name} {signataire_last_name} pour un {doctorate_title}',
            },
            {
                'en': '''<p>Hello {candidate_first_name} {candidate_last_name},</p>

<p>{signataire_first_name} {signataire_last_name} ({signataire_role}) has answered your request for {doctorate_title} 
with the following : {decision}.</p>

<p>---<br/>
The OSIS Team</p>
''',
                'fr-be': '''<p>Bonjour {candidate_first_name} {candidate_last_name},</p>

<p>{signataire_first_name} {signataire_last_name} ({signataire_role}) a répondu à votre demande de {doctorate_title} 
avec ce qui suit : {decision}.</p>

<p>---<br/>
L'équipe OSIS</p>
''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_SIGNATURE_REFUSAL,
            {
                'en': "[OSIS] Refusal from a member of the supervision group for the {doctorate_title} "
                      "of {candidate_first_name} {candidate_last_name}",
                'fr-be': "[OSIS] Refus d'un membre du groupe de supervision pour le {doctorate_title} "
                         "de {candidate_first_name} {candidate_last_name}",
            },
            {
                'en': '''<p>Hello {actor_first_name} {actor_last_name},</p>

<p>{signataire_first_name} {signataire_last_name} has refused being a member of the supervision group 
for {candidate_first_name} {candidate_last_name} ({doctorate_title}) with the following reason: {reason}.</p>

<p>Your decision is now on hold and you may be requested again once the candidate has made some changes.</p>

<p>---<br/>
The OSIS Team</p>
''',
                'fr-be': '''<p>Bonjour {actor_first_name} {actor_last_name},</p>

<p>{signataire_first_name} {signataire_last_name} a refusé de faire partie du groupe de supervision 
pour {candidate_first_name} {candidate_last_name} ({doctorate_title}) avec la raison suivante : {reason}.</p>

<p>Votre décision est maintenant en suspens et vous pourriez être sollicité à nouveau une fois que le candidat 
aura modifié le groupe de supervision.</p>

<p>---<br/>
L'équipe OSIS</p>
''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_SUBMISSION_CANDIDATE,
            {
                'en': '[OSIS] Admission request submitted successfully',
                'fr-be': "[OSIS] Demande d'admission soumise avec succès",
            },
            {
                'en': '''<p>Hello {candidate_first_name} {candidate_last_name},</p>

<p>Your application to {doctorate_title} have been submitted successfully.</p>

<p>---<br/>
The OSIS Team</p>
''',
                'fr-be': '''<p>Bonjour {candidate_first_name} {candidate_last_name},</p>

<p>Votre demande d'admission en {doctorate_title} a été soumise avec succès.</p>

<p>---<br/>
L'équipe OSIS</p>
''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_SUBMISSION_CDD,
            {
                'en': '[OSIS] Admission request submitted by {candidate_first_name} {candidate_last_name}',
                'fr-be': "[OSIS] Demande d'admission soumise par {candidate_first_name} {candidate_last_name}",
            },
            {
                'en': '''<p>Hello {actor_first_name} {actor_last_name},</p>

<p>{candidate_first_name} {candidate_last_name} has submitted an application to {doctorate_title}.</p>

<p>---<br/>
The OSIS Team</p>
''',
                'fr-be': '''<p>Bonjour {actor_first_name} {actor_last_name},</p>

<p>{candidate_first_name} {candidate_last_name} a soumis une demande d'admission en {doctorate_title}.</p>

<p>---<br/>
L'équipe OSIS</p>
''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_SUBMISSION_MEMBER,
            {
                'en': '[OSIS] Admission request submitted by {candidate_first_name} {candidate_last_name}',
                'fr-be': "[OSIS] Demande d'admission soumise par {candidate_first_name} {candidate_last_name}",
            },
            {
                'en': '''<p>Hello {actor_first_name} {actor_last_name},</p>

<p>{candidate_first_name} {candidate_last_name} has submitted an application to {doctorate_title}.</p>

<p>---<br/>
The OSIS Team</p>
''',
                'fr-be': '''<p>Bonjour {actor_first_name} {actor_last_name},</p>

<p>{candidate_first_name} {candidate_last_name} a soumis une demande d'admission en {doctorate_title}.</p>

<p>---<br/>
L'équipe OSIS</p>
''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_MEMBER_REMOVED,
            {
                'en': '[OSIS] Removal from supervision group by {candidate_first_name} {candidate_last_name}',
                'fr-be': "[OSIS] Retrait du groupe de supervision par {candidate_first_name} {candidate_last_name}",
            },
            {
                'en': '''<p>Hello {actor_first_name} {actor_last_name},</p>

<p>{candidate_first_name} {candidate_last_name} has removed you from 
the supervision group concerning {doctorate_title}.</p>

<p>---<br/>
The OSIS Team</p>
''',
                'fr-be': '''<p>Bonjour {actor_first_name} {actor_last_name},</p>

<p>{candidate_first_name} {candidate_last_name} vous a retiré du groupe de supervision 
concernant son {doctorate_title}.</p>

<p>---<br/>
L'équipe OSIS</p>
''',
            },
        ),
    ]
