# Generated by Django 2.2.24 on 2022-04-05 17:18

from django.db import migrations, models
import django.db.models.expressions
import osis_document.contrib.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0038_cddmailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorateadmission',
            name='post_enrolment_status',
            field=models.CharField(
                choices=[
                    ('ADMISSION_IN_PROGRESS', 'ADMISSION_IN_PROGRESS'),
                    ('ADMITTED', 'ADMITTED'),
                    ('SUBMITTED_CONFIRMATION', 'SUBMITTED_CONFIRMATION'),
                    ('PASSED_CONFIRMATION', 'PASSED_CONFIRMATION'),
                    ('NOT_ALLOWED_TO_CONTINUE', 'NOT_ALLOWED_TO_CONTINUE'),
                    ('CONFIRMATION_TO_BE_REPEATED', 'CONFIRMATION_TO_BE_REPEATED'),
                ],
                default='ADMISSION_IN_PROGRESS',
                max_length=30,
                verbose_name='Post-enrolment status',
            ),
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('CANCELLED', 'CANCELLED'),
                    ('IN_PROGRESS', 'IN_PROGRESS'),
                    ('SUBMITTED', 'SUBMITTED'),
                    ('SIGNING_IN_PROGRESS', 'SIGNING_IN_PROGRESS'),
                    ('ENROLLED', 'ENROLLED'),
                ],
                default='IN_PROGRESS',
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='ConfirmationPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('confirmation_date', models.DateField(blank=True, null=True, verbose_name='Confirmation exam date')),
                ('confirmation_deadline', models.DateField(blank=True, verbose_name='Confirmation deadline')),
                (
                    'research_report',
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(), default=list, size=1, verbose_name='Research report'
                    ),
                ),
                (
                    'supervisor_panel_report',
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=1,
                        verbose_name='Support Committee minutes',
                    ),
                ),
                (
                    'thesis_funding_renewal',
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        help_text='Only for FNRS, FRIA and FRESH scholarship students',
                        size=1,
                        verbose_name='Thesis funding renewal',
                    ),
                ),
                (
                    'research_mandate_renewal_opinion',
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=1,
                        verbose_name='Opinion on research mandate renewal',
                    ),
                ),
                (
                    'certificate_of_failure',
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(), default=list, size=None, verbose_name='Certificate of failure'
                    ),
                ),
                (
                    'certificate_of_achievement',
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(),
                        default=list,
                        size=None,
                        verbose_name='Certificate of achievement',
                    ),
                ),
                ('extended_deadline', models.DateField(blank=True, null=True, verbose_name='Deadline extended')),
                ('cdd_opinion', models.TextField(blank=True, default='', verbose_name='CDD opinion')),
                (
                    'justification_letter',
                    osis_document.contrib.fields.FileField(
                        base_field=models.UUIDField(), default=list, size=None, verbose_name='Justification letter'
                    ),
                ),
                (
                    'brief_justification',
                    models.TextField(blank=True, default='', max_length=2000, verbose_name='Brief justification'),
                ),
                (
                    'admission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='admission.DoctorateAdmission',
                        verbose_name='Admission',
                    ),
                ),
            ],
            options={
                'ordering': [
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F('confirmation_date'), descending=True, nulls_first=True
                    )
                ],
            },
        ),
    ]
