# Generated by Django 3.2.12 on 2022-04-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0039_confirmation_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorateadmission',
            name='cotutelle_institution_fwb',
            field=models.BooleanField(blank=True, null=True, verbose_name='Institution Federation Wallonie-Bruxelles'),
        ),
    ]
