# Generated by Django 2.2.24 on 2022-04-07 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0040_doctorateadmission_cotutelle_institution_fwb'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorateProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('admission.doctorateadmission',),
        ),
    ]
