# Generated by Django 3.2.12 on 2022-04-20 09:06

from django.db import migrations

from admission.mail_templates import ADMISSION_EMAIL_GENERIC_ONCE_ADMITTED
from osis_mail_template import MailTemplateMigration


class Migration(migrations.Migration):
    dependencies = [
        ('admission', '0042_confirmation_papers_permissions'),
    ]

    operations = [
        MailTemplateMigration(
            ADMISSION_EMAIL_GENERIC_ONCE_ADMITTED,
            {
                'en': "Information about your {training_title} enrollment",
                'fr-be': "Informations sur votre inscription au doctorat {training_title}",
            },
            {
                'en': '''<p>Hello {candidate_first_name} {candidate_last_name},</p>

<p>Here are some information about you enrollment in {training_title}.</p>

<p>---<br/>
The OSIS Team</p>''',
                'fr-be': '''<p>Bonjour {candidate_first_name} {candidate_last_name},</p>

<p>Voici quelques informations à propos de votre inscription en {training_title}.</p>

<p>---<br/>
L'équipe OSIS</p>''',
            }
        ),
    ]
