# Generated by Django 3.2.12 on 2022-05-09 15:12

from django.db import migrations, models
import django.db.models.deletion
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osis_async', '0001_initial'),
        ('admission', '0044_confirmation_mail_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorateadmission',
            name='archived_record_signatures_sent',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, editable=False, size=1, verbose_name='Archived record when signatures were sent'),
        ),
        migrations.CreateModel(
            name='AdmissionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ARCHIVE', 'PDF Export'), ('CANVAS', 'Canvas')], max_length=20)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.doctorateadmission')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osis_async.asynctask')),
            ],
        ),
    ]
