# Generated by Django 3.2.12 on 2022-05-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0630_person_last_registration_id'),
        ('admission', '0045_archived_record_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adre',
            new_name='AdreSecretary',
        ),
        migrations.AlterModelOptions(
            name='adresecretary',
            options={'verbose_name': 'Role: ADRE secretary', 'verbose_name_plural': 'Role: ADRE Secretaries'},
        ),
        migrations.CreateModel(
            name='DoctorateReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person')),
            ],
            options={
                'verbose_name': 'Role: Doctorate reader',
                'verbose_name_plural': 'Role: Doctorate readers',
            },
        ),
    ]
