# Generated by Django 3.2.12 on 2022-05-31 10:35

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0046_doctorate_roles_evolutions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmationpaper',
            name='thesis_funding_renewal',
        ),
        migrations.AddField(
            model_name='confirmationpaper',
            name='supervisor_panel_report_canvas',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1, verbose_name='Canvas of the report of the supervisory panel'),
        ),
    ]
