# Generated by Django 3.2.12 on 2022-06-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0630_person_last_registration_id'),
        ('admission', '0048_alter_admissiontask_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CddConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_types', models.JSONField(default={'en': ['Didactic supervision', 'Teaching activities', 'Popularisation of science', 'Writing a research project', 'Organisation of scientific events', 'Scientific expertise report (refering)', 'Supervision of dissertations', 'International cooperation'], 'fr-be': ['Encadrement didactique', "Activités d'enseignement", 'Vulgarisation scientifique', "Rédaction d'un projet de recherche", 'Organisation de manifestation scientifique', 'Rapport d’expertise scientifique (refering)', 'Supervision de mémoire', 'Coopération internationale']}, verbose_name='Service types')),
                ('seminar_types', models.JSONField(default={'en': ['Research seminar', "PhD students' day"], 'fr-be': ['Séminaire de recherche', 'Journée des doctorantes et des doctorants']}, verbose_name='Seminar types')),
                ('cdd', models.OneToOneField(limit_choices_to={'entityversion__entity_type': 'DOCTORAL_COMMISSION'}, on_delete=django.db.models.deletion.CASCADE, related_name='admission_config', to='base.entity')),
            ],
        ),
    ]
