# Generated by Django 3.2.12 on 2022-06-15 09:37

from django.db import migrations, models
import django.db.models.deletion
import osis_document.contrib.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0015_auto_20220525_1044'),
        ('admission', '0049_cddconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('ects', models.FloatField(blank=True, default=0, verbose_name='ECTS credits')),
                ('status', models.CharField(choices=[('NON_SOUMISE', 'NON_SOUMISE'), ('SOUMISE', 'SOUMISE'), ('ACCEPTEE', 'ACCEPTEE'), ('REFUSEE', 'REFUSEE')], default='NON_SOUMISE', max_length=20)),
                ('category', models.CharField(choices=[('CONFERENCE', 'CONFERENCE'), ('COMMUNICATION', 'COMMUNICATION'), ('SEMINAR', 'SEMINAR'), ('PUBLICATION', 'PUBLICATION'), ('SERVICE', 'SERVICE'), ('RESIDENCY', 'RESIDENCY'), ('VAE', 'VAE'), ('COURSE', 'COURSE'), ('PAPER', 'PAPER')], max_length=50)),
                ('type', models.CharField(blank=True, default='', max_length=100, verbose_name='Activity type')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Title')),
                ('participating_proof', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='Participation certification')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Begin date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('participating_days', models.SmallIntegerField(blank=True, null=True, verbose_name='Number of days participating')),
                ('is_online', models.BooleanField(blank=True, choices=[(False, 'In person'), (True, 'Online')], default=None, null=True, verbose_name='Online event')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('organizing_institution', models.CharField(blank=True, default='', max_length=100, verbose_name='Organizing institution')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('committee', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('NA', 'N/A')], max_length=100, default='')),
                ('dial_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Référence DIAL.Pr')),
                ('acceptation_proof', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='Participation certification')),
                ('summary', osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=1, verbose_name='Summary')),
                ('subtype', models.CharField(blank=True, default='', max_length=100, verbose_name='Activity subtype')),
                ('subtitle', models.TextField(blank=True, default='')),
                ('authors', models.CharField(blank=True, default='', max_length=100, verbose_name='Authors')),
                ('role', models.CharField(blank=True, default='', max_length=100, verbose_name='Role')),
                ('keywords', models.CharField(blank=True, default='', max_length=100, verbose_name='Keywords')),
                ('journal', models.CharField(blank=True, default='', max_length=100, verbose_name='Journal')),
                ('publication_status', models.CharField(blank=True, choices=[('UNSUBMITTED', 'Unsubmitted for publication'), ('SUBMITTED', 'Submitted for publication'), ('IN_REVIEW', 'In review'), ('ACCEPTED', 'Accepted'), ('PUBLISHED', 'Published')], max_length=100, default='')),
                ('hour_volume', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.country', verbose_name='Country')),
                ('doctorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.doctorateadmission')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='admission.activity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
