# Generated by Django 3.2.12 on 2022-06-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0051_activity_decimal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='confirmationpaper',
            options={'ordering': ['-id']},
        ),
    ]
