# Generated by Django 3.2.12 on 2022-07-12 20:00

import admission.contrib.models.cdd_config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0053_confirmation_mail_templates_evolutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cddconfiguration',
            name='communication_types',
            field=models.JSONField(default=admission.contrib.models.cdd_config.default_communication_types, verbose_name='Communication types'),
        ),
        migrations.AddField(
            model_name='cddconfiguration',
            name='conference_publication_types',
            field=models.JSONField(default=admission.contrib.models.cdd_config.default_conference_publication_types, verbose_name='Conference publication types'),
        ),
        migrations.AddField(
            model_name='cddconfiguration',
            name='conference_types',
            field=models.JSONField(default=admission.contrib.models.cdd_config.default_conference_types, verbose_name='Seminar types'),
        ),
        migrations.AddField(
            model_name='cddconfiguration',
            name='publication_types',
            field=models.JSONField(default=admission.contrib.models.cdd_config.default_publication_types, verbose_name='Publication types'),
        ),
        migrations.AddField(
            model_name='cddconfiguration',
            name='residency_types',
            field=models.JSONField(default=admission.contrib.models.cdd_config.default_residency_types, verbose_name='Residency types'),
        ),
    ]
