# Generated by Django 3.2.12 on 2022-07-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0053_confirmation_mail_templates_evolutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cddconfiguration',
            name='communication_types',
            field=models.JSONField(default=dict, verbose_name='COMMUNICATION types'),
        ),
        migrations.AddField(
            model_name='cddconfiguration',
            name='conference_publication_types',
            field=models.JSONField(default=dict, verbose_name='CONFERENCE PUBLICATION types'),
        ),
        migrations.AddField(
            model_name='cddconfiguration',
            name='conference_types',
            field=models.JSONField(default=dict, verbose_name='CONFERENCE types'),
        ),
        migrations.AddField(
            model_name='cddconfiguration',
            name='publication_types',
            field=models.JSONField(default=dict, verbose_name='PUBLICATION types'),
        ),
        migrations.AddField(
            model_name='cddconfiguration',
            name='residency_types',
            field=models.JSONField(default=dict, verbose_name='RESIDENCY types'),
        ),
    ]
