# Generated by Django 3.2.12 on 2022-07-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0054_config_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='cddconfiguration',
            name='course_types',
            field=models.JSONField(default=dict, verbose_name='COURSE types'),
        ),
    ]
