# Generated by Django 3.2.12 on 2022-07-20 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osis_profile', '0012_rename_institute_link_belgianhighschooldiploma_institute'),
        ('admission', '0055_course_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='valuated_experiences',
        ),
    ]
