# Generated by Django 3.2.12 on 2022-07-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_profile', '0013_cv_new_models'),
        ('admission', '0055_course_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorateadmission',
            name='educational_valuated_experiences',
            field=models.ManyToManyField(related_name='valuated_from', to='osis_profile.EducationalExperience', verbose_name='The educational experiences that have been valuated from this admission.'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='professional_valuated_experiences',
            field=models.ManyToManyField(related_name='valuated_from', to='osis_profile.ProfessionalExperience', verbose_name='The professional experiences that have been valuated from this admission.'),
        ),
    ]
