
# Generated by Django 3.2.12 on 2022-07-19 13:07

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0631_auto_20220613_1151'),
        ('admission', '0057_add_new_valuated_experiences'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalNote',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Created',
                    ),
                ),
                (
                    'text',
                    ckeditor.fields.RichTextField(
                        verbose_name='Text',
                    ),
                ),
                (
                    'admission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='admission.doctorateadmission',
                        verbose_name='Admission',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='base.person',
                        verbose_name='Author',
                    ),
                ),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
