# Generated by Django 3.2.12 on 2022-07-26 10:02

import admission.contrib.models.cdd_config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0058_internalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='cddconfiguration',
            name='category_labels',
            field=models.JSONField(default=admission.contrib.models.cdd_config.default_category_labels, verbose_name='Category labels'),
        ),
    ]
