# Generated by Django 3.2.12 on 2022-08-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0059_category_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='can_be_submitted',
            field=models.BooleanField(default=False, verbose_name='Can be submitted'),
        ),
    ]
