# Generated by Django 3.2.12 on 2022-08-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0060_activity_can_be_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisionactor',
            name='is_reference_promoter',
            field=models.BooleanField(default=False),
        ),
    ]
