# Generated by Django 3.2.12 on 2022-08-22 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('admission', '0061_supervisionactor_is_reference_promoter'),
    ]

    operations = [
    ]
