# Generated by Django 3.2.12 on 2022-08-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0062_training_mail_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cdd_comment',
            field=models.TextField(default='', verbose_name='CDD manager comment'),
        ),
        migrations.AddField(
            model_name='activity',
            name='reference_promoter_assent',
            field=models.BooleanField(null=True, verbose_name='Lead supervisor assent'),
        ),
        migrations.AddField(
            model_name='activity',
            name='reference_promoter_comment',
            field=models.TextField(default='', verbose_name='Lead supervisor comment'),
        ),
    ]
