# Generated by Django 3.2.12 on 2022-08-25 14:58

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0063_activity_process_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorateadmission',
            name='scholarship_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Scholarship end date'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='scholarship_proof',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Scholarship proof'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='scholarship_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Scholarship start date'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='phd_already_done_thesis_domain',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Thesis domain'),
        ),
    ]
