# Generated by Django 3.2.12 on 2022-09-12 10:52

import admission.contrib.models.form_item
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0632_alter_academiccalendar_reference'),
        ('admission', '0064_scholarship_data_thesis_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionTrainingConfiguration',
            fields=[
            ],
            options={
                'verbose_name': 'Training configuration for admission',
                'verbose_name_plural': 'Training configurations for admission',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.educationgroupyear',),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='form_item_answers',
            field=admission.contrib.models.form_item.ConfigurableModelFormItemField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.CreateModel(
            name='AdmissionFormItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('MESSAGE', 'Message'), ('TEXTE', 'Text'), ('DOCUMENT', 'Document')], max_length=30)),
                ('weight', models.PositiveIntegerField(verbose_name='Weight')),
                ('deleted', models.BooleanField(default=False, verbose_name='Soft deleted')),
                ('internal_label', models.CharField(max_length=255, verbose_name='Internal label')),
                ('required', models.BooleanField(default=False, verbose_name='Required')),
                ('title', models.JSONField(blank=True, default=dict, validators=[admission.contrib.models.form_item.is_valid_translated_json_field], verbose_name='Title')),
                ('text', models.JSONField(blank=True, default=dict, validators=[admission.contrib.models.form_item.is_valid_translated_json_field], verbose_name='Text')),
                ('help_text', models.JSONField(blank=True, default=dict, validators=[admission.contrib.models.form_item.is_valid_translated_json_field], verbose_name='Help text')),
                ('config', models.JSONField(blank=True, default=dict)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.educationgroupyear', verbose_name='Education')),
            ],
            options={
                'ordering': ['education', 'weight'],
            },
        ),
    ]
