# Generated by Django 3.2.16 on 2022-10-19 15:15

from django.db import migrations
from admission.mail_templates import (
    ADMISSION_EMAIL_CANDIDATE_COMPLEMENTARY_TRAINING_NEEDS_UPDATE,
    ADMISSION_EMAIL_CANDIDATE_COMPLEMENTARY_TRAINING_REFUSED,
    ADMISSION_EMAIL_CANDIDATE_COURSE_ENROLLMENT_NEEDS_UPDATE,
    ADMISSION_EMAIL_CANDIDATE_COURSE_ENROLLMENT_REFUSED,
    ADMISSION_EMAIL_CANDIDATE_DOCTORAL_TRAINING_NEEDS_UPDATE,
    ADMISSION_EMAIL_CANDIDATE_DOCTORAL_TRAINING_REFUSED,
    ADMISSION_EMAIL_REFERENCE_PROMOTER_COMPLEMENTARY_TRAININGS_SUBMITTED,
    ADMISSION_EMAIL_REFERENCE_PROMOTER_COURSE_ENROLLMENTS_SUBMITTED,
    ADMISSION_EMAIL_REFERENCE_PROMOTER_DOCTORAL_TRAININGS_SUBMITTED,
)

from osis_mail_template import MailTemplateMigration


def forwards(apps, schema_editor):
    # Reset old mail template
    MailTemplate = apps.get_model('osis_mail_template', 'MailTemplate')
    MailTemplate.objects.filter(
        identifier__in=[
            ADMISSION_EMAIL_REFERENCE_PROMOTER_DOCTORAL_TRAININGS_SUBMITTED,
            ADMISSION_EMAIL_CANDIDATE_DOCTORAL_TRAINING_NEEDS_UPDATE,
            ADMISSION_EMAIL_CANDIDATE_DOCTORAL_TRAINING_REFUSED,
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('admission', '0066_training_contexts'),
    ]

    operations = [
        migrations.RunPython(forwards, reverse_code=migrations.RunPython.noop),
        MailTemplateMigration(
            ADMISSION_EMAIL_REFERENCE_PROMOTER_DOCTORAL_TRAININGS_SUBMITTED,
            {
                'en': '[OSIS] New doctoral training activities been submitted by {student_first_name} {student_last_name}',
                'fr-be': "[OSIS] De nouvelles activités de formation doctorale ont été soumises par "
                "{student_first_name} {student_last_name}",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        {student_first_name} {student_last_name} have submitted new doctoral training activities for {doctorate_title}, 
        you can review them by following this link: {admission_link_front_doctoral_training}.
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        {student_first_name} {student_last_name} a soumis de nouvelles activités de formation doctorale 
        pour son {doctorate_title}, vous pouvez les consulter en suivant ce lien : {admission_link_front_doctoral_training}.
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_DOCTORAL_TRAINING_REFUSED,
            {
                'en': '[OSIS] A doctoral training activity has been refused',
                'fr-be': "[OSIS] Une activité de formation doctorale a été refusée",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted doctoral training activity entitled <em>{activity_title}</em> for your {doctorate_title} has been refused, 
        you can review all activities by following this link: {admission_link_front_doctoral_training}.

        Here's the reason for this refusal: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        L'activité de formation doctorale soumise intitulée <em>{activity_title}</em> pour votre {doctorate_title} a été refusée,
        vous pouvez la consulter en suivant ce lien : {admission_link_front_doctoral_training}.

        La raison invoquée pour ce refus : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_DOCTORAL_TRAINING_NEEDS_UPDATE,
            {
                'en': '[OSIS] A doctoral training activity needs to be updated',
                'fr-be': "[OSIS] Une activité de formation doctorale doit être mise à jour",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted doctoral training activity entitled <em>{activity_title}</em> for {doctorate_title} must be updated, 
        you can review all activities by following this link: {admission_link_front_doctoral_training}.

        Here's why it needs to be updated: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        L'activité de formation doctorale soumise intitulée <em>{activity_title}</em> doit être mise à jour 
        pour {doctorate_title}, vous pouvez la consulter en suivant ce lien : {admission_link_front_doctoral_training}.

        Voici ce pourquoi vous devez la modifier : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_REFERENCE_PROMOTER_COMPLEMENTARY_TRAININGS_SUBMITTED,
            {
                'en': '[OSIS] New complementary training activities been submitted by '
                '{student_first_name} {student_last_name}',
                'fr-be': "[OSIS] De nouvelles activités de formation complémentaire ont été soumises par {student_first_name} "
                "{student_last_name}",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        {student_first_name} {student_last_name} have submitted new complementary training activities for {doctorate_title}, 
        you can review them by following this link: {admission_link_front_complementary_training}.
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        {student_first_name} {student_last_name} a soumis de nouvelles activités de formation complémentaire pour son {doctorate_title},
        vous pouvez les consulter en suivant ce lien : {admission_link_front_complementary_training}.
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_COMPLEMENTARY_TRAINING_REFUSED,
            {
                'en': '[OSIS] A complementary training activity has been refused',
                'fr-be': "[OSIS] Une activité de formation complémentaire a été refusée",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted complementary training activity entitled <em>{activity_title}</em> for your {doctorate_title} has been refused, 
        you can review all activities by following this link: {admission_link_front_complementary_training}.

        Here's the reason for this refusal: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        L'activité de formation complémentaire soumise intitulée <em>{activity_title}</em> pour votre {doctorate_title} a été refusée,
        vous pouvez la consulter en suivant ce lien : {admission_link_front_complementary_training}.

        La raison invoquée pour ce refus : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_COMPLEMENTARY_TRAINING_NEEDS_UPDATE,
            {
                'en': '[OSIS] A complementary training activity needs to be updated',
                'fr-be': "[OSIS] Une activité de formation complémentaire doit être mise à jour",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted complementary training activity entitled <em>{activity_title}</em> for {doctorate_title} must be updated, 
        you can review them by following this link: {admission_link_front_complementary_training}.

        Here's why it needs to be updated: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        L'activité de formation complémentaire soumise intitulée <em>{activity_title}</em> doit être mise à jour pour {doctorate_title},
        vous pouvez la consulter en suivant ce lien : {admission_link_front_complementary_training}.

        Voici ce pourquoi vous devez la modifier : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_REFERENCE_PROMOTER_COURSE_ENROLLMENTS_SUBMITTED,
            {
                'en': '[OSIS] New course enrollments been submitted by {student_first_name} {student_last_name}',
                'fr-be': "[OSIS] Nouvelles inscriptions aux cours soumises par {student_first_name} "
                "{student_last_name}",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        {student_first_name} {student_last_name} have submitted new course enrollments for {doctorate_title}, 
        you can review them by following this link: {admission_link_front_course_enrollment}.
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        {student_first_name} {student_last_name} a soumis de nouvelles inscriptions aux cours pour son {doctorate_title},
        vous pouvez les consulter en suivant ce lien : {admission_link_front_course_enrollment}.
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_COURSE_ENROLLMENT_REFUSED,
            {
                'en': '[OSIS] A course enrollment has been refused',
                'fr-be': "[OSIS] Une inscription à un cours a été refusée",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted course enrollment entitled <em>{activity_title}</em> for your {doctorate_title} has been refused, 
        you can review all courses by following this link: {admission_link_front_course_enrollment}.

        Here's the reason for this refusal: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        Une inscription à un cours intitulé <em>{activity_title}</em> pour votre {doctorate_title} a été refusée,
        vous pouvez la consulter en suivant ce lien : {admission_link_front_course_enrollment}.

        La raison invoquée pour ce refus : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_CANDIDATE_COURSE_ENROLLMENT_NEEDS_UPDATE,
            {
                'en': '[OSIS] A course enrollment needs to be updated',
                'fr-be': "[OSIS] Une inscription à un cours doit être mise à jour",
            },
            {
                'en': '''<p>Hello,</p>

    <p>
        The submitted course enrollment entitled <em>{activity_title}</em> for {doctorate_title} must be updated, 
        you can review all courses by following this link: {admission_link_front_course_enrollment}.

        Here's why it needs to be updated: {reason}
    </p>

    <p>
        ---<br/>
        The OSIS Team
    </p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

    <p>
        Une inscription à un cours intitulé <em>{activity_title}</em> doit être mise à jour pour {doctorate_title},
        vous pouvez la consulter en suivant ce lien : {admission_link_front_course_enrollment}.

        Voici ce pourquoi vous devez la modifier : {reason}
    </p>

    <p>
        ---<br/>
        L'équipe OSIS
    </p>
    ''',
            },
        ),
    ]
