# Generated by Django 3.2.16 on 2022-10-19 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('admission', '0066_training_contexts'),
    ]

    operations = [
    ]
