# Generated by Django 3.2.12 on 2022-10-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0069_new_admission_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='valid_iban',
            field=models.BooleanField(blank=True, null=True, verbose_name='The IBAN account number is valid'),
        ),
    ]
