# Generated by Django 3.2.16 on 2022-10-21 16:46

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import uuid


def forward(apps, schema_editor):
    BaseAdmission = apps.get_model('admission', 'BaseAdmission')
    DoctorateAdmission = apps.get_model('admission', 'DoctorateAdmission')
    GeneralEducationAdmission = apps.get_model('admission', 'GeneralEducationAdmission')
    ContinuingEducationAdmission = apps.get_model('admission', 'ContinuingEducationAdmission')

    # Copy data from the 3 tables to BaseAdmission
    for AdmissionType in [DoctorateAdmission, GeneralEducationAdmission, ContinuingEducationAdmission]:
        for admission in AdmissionType.objects.all():
            base_admission = BaseAdmission.objects.create(
                uuid=admission.uuid,
                comment=admission.comment,
                created=admission.created,
                modified=admission.modified,
                detailed_status=admission.detailed_status,
                candidate_id=admission.candidate_id,
                training_id=admission.doctorate_id if AdmissionType == DoctorateAdmission else admission.training_id,
            )
            base_admission.educational_valuated_experiences.set(admission.educational_valuated_experiences.all())
            base_admission.professional_valuated_experiences.set(admission.professional_valuated_experiences.all())
            admission.baseadmission_ptr_id = base_admission.pk
            admission.save()


def backward(apps, schema_editor):
    BaseAdmission = apps.get_model('admission', 'BaseAdmission')
    DoctorateAdmission = apps.get_model('admission', 'DoctorateAdmission')
    GeneralEducationAdmission = apps.get_model('admission', 'GeneralEducationAdmission')
    ContinuingEducationAdmission = apps.get_model('admission', 'ContinuingEducationAdmission')

    # Copy data from BaseAdmission to the 3 tables
    bases = BaseAdmission.objects.in_bulk()
    for AdmissionType in [DoctorateAdmission, GeneralEducationAdmission, ContinuingEducationAdmission]:
        pk = 1
        for admission in AdmissionType.objects.all():
            base_admission = bases[admission.baseadmission_ptr_id]
            admission.uuid = base_admission.uuid
            admission.comment = base_admission.comment
            admission.created = base_admission.created
            admission.modified = base_admission.modified
            admission.detailed_status = base_admission.detailed_status
            admission.candidate_id = base_admission.candidate_id
            if AdmissionType == DoctorateAdmission:
                admission.doctorate_id = base_admission.training_id
            else:
                admission.training_id = base_admission.training_id
            admission.educational_valuated_experiences.set(
                base_admission.educational_valuated_experiences.all()
            )
            admission.professional_valuated_experiences.set(
                base_admission.professional_valuated_experiences.all()
            )
            admission.id = pk
            admission.save()
            pk += 1


class Migration(migrations.Migration):
    dependencies = [
        ('osis_profile', '0001_squashed_0015_alter_educationalexperience_study_system'),
        ('base', '0636_alter_academiccalendar_reference'),
        ('admission', '0070_accounting_valid_iban'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE', reverse_sql='SET CONSTRAINTS ALL DEFERRED'),
        migrations.CreateModel(
            name='BaseAdmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('comment', models.TextField(blank=True, default='', verbose_name='Comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                (
                    'detailed_status',
                    models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                (
                    'candidate',
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='baseadmissions',
                        to='base.person',
                        verbose_name='Candidate',
                    ),
                ),
                (
                    'educational_valuated_experiences',
                    models.ManyToManyField(
                        blank=True,
                        related_name='valuated_from_admission',
                        to='osis_profile.EducationalExperience',
                        verbose_name='The educational experiences that have been valuated from this admission.',
                    ),
                ),
                (
                    'professional_valuated_experiences',
                    models.ManyToManyField(
                        blank=True,
                        related_name='valuated_from_admission',
                        to='osis_profile.ProfessionalExperience',
                        verbose_name='The professional experiences that have been valuated from this admission.',
                    ),
                ),
                (
                    'training',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='base.educationgroupyear',
                        verbose_name='Training',
                    ),
                ),
            ],
        ),
        # Add pointer first with nullable
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='baseadmission_ptr',
            field=models.OneToOneField(
                auto_created=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                serialize=False,
                to='admission.baseadmission',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='baseadmission_ptr',
            field=models.OneToOneField(
                auto_created=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                serialize=False,
                to='admission.baseadmission',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='baseadmission_ptr',
            field=models.OneToOneField(
                auto_created=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                serialize=False,
                to='admission.baseadmission',
            ),
            preserve_default=False,
        ),
        # Set foreign keys to nullable
        migrations.AlterField(
            model_name='doctorateadmission',
            name='doctorate',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='base.educationgroupyear',
                verbose_name='Training',
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='training',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='base.educationgroupyear',
                verbose_name='Training',
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='training',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='base.educationgroupyear',
                verbose_name='Training',
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='candidate',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to='base.person',
                verbose_name='Candidate',
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='candidate',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to='base.person',
                verbose_name='Candidate',
                null=True,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='candidate',
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to='base.person',
                verbose_name='Candidate',
                null=True,
            ),
            preserve_default=False,
        ),
        # Set uuid to not unique
        migrations.AlterField(
            model_name='doctorateadmission',
            name='uuid',
            field=models.UUIDField(null=True, unique=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='uuid',
            field=models.UUIDField(null=True, unique=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='uuid',
            field=models.UUIDField(null=True, unique=False),
            preserve_default=False,
        ),
        # Set id to not primary key
        migrations.AlterField(
            model_name='doctorateadmission',
            name='id',
            field=models.AutoField(auto_created=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='id',
            field=models.AutoField(auto_created=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='id',
            field=models.AutoField(auto_created=True, serialize=False),
            preserve_default=False,
        ),
        # Actual work
        migrations.RunPython(forward, backward),
        # Remove old primary
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='id',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='id',
        ),
        # Set pointer to non-nullable
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='baseadmission_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                serialize=False,
                to='admission.baseadmission',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='baseadmission_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                serialize=False,
                to='admission.baseadmission',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='baseadmission_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                serialize=False,
                to='admission.baseadmission',
            ),
            preserve_default=False,
        ),
        # Set pointer to primary key
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='baseadmission_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='admission.baseadmission',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='baseadmission_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='admission.baseadmission',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='baseadmission_ptr',
            field=models.OneToOneField(
                auto_created=True,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to='admission.baseadmission',
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='created',
        ),
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='detailed_status',
        ),
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='educational_valuated_experiences',
        ),
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='professional_valuated_experiences',
        ),
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='training',
        ),
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='created',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='detailed_status',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='doctorate',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='educational_valuated_experiences',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='professional_valuated_experiences',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='created',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='detailed_status',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='educational_valuated_experiences',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='professional_valuated_experiences',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='training',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='uuid',
        ),
        migrations.RunSQL('SET CONSTRAINTS ALL DEFERRED', reverse_sql='SET CONSTRAINTS ALL IMMEDIATE'),
    ]
