# Generated by Django 3.2.16 on 2022-11-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0073_scholarships_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaleducationadmission',
            name='is_external_modification',
            field=models.BooleanField(null=True, verbose_name='Is an external modification'),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='is_external_reorientation',
            field=models.BooleanField(null=True, verbose_name='Is an external reorientation'),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='is_non_resident',
            field=models.BooleanField(null=True, verbose_name='Is non-resident (as defined in decree)'),
        ),
    ]
