# Generated by Django 3.2.16 on 2022-11-29 17:30

from django.db import migrations, models
import django.db.models.deletion
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0074_general_admission_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadmission',
            name='curriculum',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(), blank=True, default=list, size=None, verbose_name='Curriculum'
            ),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='diploma_equivalence',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(), blank=True, default=list, size=None, verbose_name='Diploma equivalence'
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='bachelor_cycle_continuation',
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name='Do you want, on the basis of this training, to realize a cycle continuation '
                             'for the bachelor you are registering for?',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='bachelor_cycle_continuation_certificate',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Certificate allowing the continuation of studies for a bachelor's degree",
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='diploma_equivalence',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(), blank=True, default=list, size=None, verbose_name='Diploma equivalence'
            ),
        ),
    ]
