# Generated by Django 3.2.16 on 2022-12-01 14:14

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0075_add_some_cv_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaleducationadmission',
            name='is_belgian_bachelor',
            field=models.BooleanField(null=True, verbose_name='Is belgian bachelor'),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='registration_change_form',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1, verbose_name='Change of enrolment form', blank=True),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='regular_registration_proof',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=1, verbose_name='Proof of regular registration', blank=True),
        ),
    ]
