# Generated by Django 3.2.16 on 2022-11-17 15:32

from django.db import migrations


def forward(apps, _):
    # Update the choices with the new ones
    doctorate_admission_model = apps.get_model('admission', 'DoctorateAdmission')
    doctorate_admission_model.objects.filter(financing_work_contract='UCLOUVAIN_ASSISTANT').update(
        financing_work_contract='UCLOUVAIN_SCIENTIFIC_STAFF'
    )


def backward(apps, _):
    # Update the choices with the older ones
    doctorate_admission_model = apps.get_model('admission', 'DoctorateAdmission')
    doctorate_admission_model.objects.filter(financing_work_contract='UCLOUVAIN_SCIENTIFIC_STAFF').update(
        financing_work_contract='UCLOUVAIN_ASSISTANT'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0076_pool_questions'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
