# Generated by Django 3.2.16 on 2022-12-06 17:29

import django.db.models.deletion
from django.db import migrations, models

from base.models.enums.academic_calendar_type import AcademicCalendarTypes


def forward(apps, schema_editor):
    # Reset some wrongly create calendars
    AcademicCalendar = apps.get_model('base', 'AcademicCalendar')
    AcademicCalendar.objects.filter(
        reference__in=[
            AcademicCalendarTypes.ADMISSION_POOL_UE5_NON_BELGIAN.name,
            AcademicCalendarTypes.ADMISSION_POOL_HUE5_BELGIUM_RESIDENCY.name,
            AcademicCalendarTypes.ADMISSION_POOL_HUE5_FOREIGN_RESIDENCY.name,
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0644_remove_person_curriculum'),
        ('admission', '0077_alter_working_contract_type'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
        migrations.AddField(
            model_name='baseadmission',
            name='determined_academic_year',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='base.academicyear',
            ),
        ),
        migrations.AddField(
            model_name='baseadmission',
            name='determined_pool',
            field=models.CharField(
                blank=True,
                choices=[
                    ('DELIBERATION', 'Deliberation'),
                    ('DISSERTATION_SUBMISSION', 'Dissertation submission'),
                    ('EXAM_ENROLLMENTS', 'Exam enrollments'),
                    ('SCORES_EXAM_DIFFUSION', 'Scores diffusion'),
                    ('SCORES_EXAM_SUBMISSION', 'Scores exam submission'),
                    ('ATTENDANCE_MARK', 'Attendance mark'),
                    ('TEACHING_CHARGE_APPLICATION', 'Application for vacant courses'),
                    ('ACCESS_SCHEDULE_CALENDAR', 'Access schedule calendar'),
                    ('COURSE_ENROLLMENT', 'Course enrollment'),
                    ('SUMMARY_COURSE_SUBMISSION', 'Summary course submission'),
                    ('SUMMARY_COURSE_SUBMISSION_FORCE_MAJEURE', 'Summary course submission force majeure'),
                    ('EDUCATION_GROUP_SWITCH', 'Education group switch'),
                    ('EDUCATION_GROUP_EDITION', 'Education group edition'),
                    ('EDUCATION_GROUP_EXTENDED_DAILY_MANAGEMENT', 'Education group extended daily management'),
                    ('EDUCATION_GROUP_LIMITED_DAILY_MANAGEMENT', 'Education group limited daily management'),
                    ('LEARNING_UNIT_EXTENDED_PROPOSAL_MANAGEMENT', 'Extended proposal management'),
                    ('LEARNING_UNIT_LIMITED_PROPOSAL_MANAGEMENT', 'Limited proposal management'),
                    ('PAYMENT_NOTICE_1_WARNING', 'Payment notice 1 warning'),
                    ('PAYMENT_NOTICE_2_WARNING', 'Payment notice 2 warning'),
                    ('COURSE_ENROLLMENT_SWITCHING_CALENDAR', 'Course enrollment switching'),
                    ('GENERAL_EDUCATION_ENROLLMENT', 'General education enrolment'),
                    ('DOCTORATE_EDUCATION_ENROLLMENT', 'Doctorate education enrolment'),
                    ('CONTINUING_EDUCATION_ENROLLMENT', 'Continuing education enrolment'),
                    ('ADMISSION_POOL_EXTERNAL_ENROLLMENT_CHANGE', 'Admission: pool External enrollment change'),
                    ('ADMISSION_POOL_EXTERNAL_REORIENTATION', 'Admission: pool External reorientation'),
                    ('ADMISSION_POOL_VIP', 'Admission: pool VIP'),
                    ('ADMISSION_POOL_HUE_UCL_PATHWAY_CHANGE', 'Admission: pool HUE UCL pathway change'),
                    ('ADMISSION_POOL_INSTITUT_CHANGE', 'Admission: pool Institute change'),
                    ('ADMISSION_POOL_UE5_BELGIAN', 'Admission: pool EU+5 nationality and Belgian access diploma'),
                    (
                        'ADMISSION_POOL_UE5_NON_BELGIAN',
                        'Admission: pool EU+5 nationality and non-Belgian access diploma',
                    ),
                    (
                        'ADMISSION_POOL_HUE5_BELGIUM_RESIDENCY',
                        'Admission: pool Nationality outside (EU+5) and residence in Belgium',
                    ),
                    (
                        'ADMISSION_POOL_HUE5_FOREIGN_RESIDENCY',
                        'Admission: pool Nationality outside (EU+5) and foreign residence',
                    ),
                    (
                        'ADMISSION_POOL_NON_RESIDENT_QUOTA',
                        'Admission: pool Non-resident quota holder (as defined in decree)',
                    ),
                    (
                        'ADMISSION_ACCESS_CONDITIONS_URL',
                        'Admission: publication of the training catalogue on the UCLouvain website',
                    ),
                ],
                max_length=70,
                null=True,
            ),
        ),
    ]
