# Generated by Django 3.2.16 on 2022-12-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0078_determined_acad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalnote',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.baseadmission', verbose_name='Admission'),
        ),
    ]
