# Generated by Django 3.2.16 on 2022-12-23 10:59

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0080_alter_accounting_admission'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadmission',
            name='confirmation_elements',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
