# Generated by Django 3.2.16 on 2023-01-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0646_person_graduated_from_high_school'),
        ('admission', '0082_email_confirm_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadmission',
            name='valuated_secondary_studies_person',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=models.deletion.SET_NULL,
                to='base.person',
                verbose_name='The person whose the secondary studies have been valuated by this admission',
            ),
        ),
        migrations.AddConstraint(
            model_name='baseadmission',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('valuated_secondary_studies_person_id', models.expressions.F('candidate_id'))
                ),
                name='only_candidate_can_be_valuated',
            ),
        ),
    ]
