# Generated by Django 3.2.16 on 2023-01-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0017_delete_highschool'),
        ('admission', '0084_add_selection_form_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='billing_address_city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Billing address city'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='billing_address_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reference.country', verbose_name='Billing address country'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='billing_address_place',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Billing address place'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='billing_address_postal_box',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Billing address postal box'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='billing_address_postal_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Billing address postal code'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='billing_address_recipient',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Billing address recipient'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='billing_address_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Billing address street'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='billing_address_street_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Billing address street number'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='billing_address_type',
            field=models.CharField(blank=True, choices=[('RESIDENTIEL', 'Legal domicile'), ('CONTACT', 'Postal address'), ('AUTRE', 'Other address')], default='', max_length=30, verbose_name='Billing address type'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='head_office_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Head office name'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='professional_email',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Professional email'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='registration_as',
            field=models.CharField(blank=True, choices=[('PRIVE', 'Private'), ('PROFESSIONNEL', 'Professional')], default='', max_length=30, verbose_name='Registration as'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='unique_business_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Unique business number'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='vat_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='VAT number'),
        ),
    ]
