# Generated by Django 3.2.16 on 2023-01-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0085_continuing_admission_evolutions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='deleted',
            new_name='disabled',
        ),
    ]
