# Generated by Django 3.2.16 on 2023-01-26 13:52

from django.db import migrations, models
from django.db.backends.postgresql.schema import DatabaseSchemaEditor
from django.db.models import F

from admission.models.base import REFERENCE_SEQ_NAME


OLD_REFERENCE_SEQ_NAME = 'admission_doctorateadmission_reference_seq'


def create_base_admission_reference_sequence(apps, schema_editor: DatabaseSchemaEditor):
    BaseAdmission = apps.get_model('admission', 'BaseAdmission')
    cursor = schema_editor.connection.cursor()

    # Delete the previous sequence(s)
    cursor.execute(schema_editor.sql_delete_sequence % {'sequence': OLD_REFERENCE_SEQ_NAME})
    cursor.execute(schema_editor.sql_delete_sequence % {'sequence': REFERENCE_SEQ_NAME})

    # Create the new sequence
    cursor.execute(schema_editor.sql_create_sequence % {'sequence': REFERENCE_SEQ_NAME})
    cursor.execute(schema_editor.sql_set_sequence_max % {
        'sequence': REFERENCE_SEQ_NAME,
        "table": BaseAdmission._meta.db_table,
        "column": 'id',
    })

    # Set a default reference value based on the id
    BaseAdmission.objects.all().update(reference=F('id'))


def delete_base_admission_reference_sequence(_, __):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0086_rename_deleted_scholarship_disabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='reference',
        ),
        migrations.AddField(
            model_name='baseadmission',
            name='reference',
            field=models.BigIntegerField(editable=False, null=True, unique=True, verbose_name='Reference'),
        ),
        migrations.RunPython(create_base_admission_reference_sequence, delete_base_admission_reference_sequence),
    ]
