# Generated by Django 3.2.16 on 2023-01-25 17:15

from django.db import migrations, models


def forward(apps, schema_editor):
    BaseAdmission = apps.get_model("admission", "BaseAdmission")
    DoctorateAdmission = apps.get_model("admission", "DoctorateAdmission")
    BaseAdmission.objects.alias(
        submission_date=models.Subquery(
            DoctorateAdmission.objects.filter(
                admission_submission_date__isnull=False,
                baseadmission_ptr_id=models.OuterRef('pk'),
            ).order_by().values('admission_submission_date')[:1]
        )
    ).filter(submission_date__isnull=False).update(
        submitted_at=models.F("submission_date"),
    )


def backward(apps, schema_editor):
    BaseAdmission = apps.get_model("admission", "BaseAdmission")
    DoctorateAdmission = apps.get_model("admission", "DoctorateAdmission")
    DoctorateAdmission.objects.alias(
        submission_date=models.Subquery(
            BaseAdmission.objects.filter(
                submitted_at__isnull=False,
                pk=models.OuterRef('baseadmission_ptr_id'),
            ).values('submitted_at')[:1]
        )
    ).filter(submission_date__isnull=False).update(
        admission_submission_date=models.F("submission_date"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('admission', '0087_new_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadmission',
            name='type_demande',
            field=models.CharField(
                choices=[('ADMISSION', 'ADMISSION'), ('INSCRIPTION', 'INSCRIPTION')],
                db_index=True,
                default='ADMISSION',
                max_length=255,
                verbose_name='Type',
            ),
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='type',
            field=models.CharField(
                choices=[('ADMISSION', 'ADMISSION'), ('PRE_ADMISSION', 'PRE_ADMISSION')],
                db_index=True,
                default='ADMISSION',
                max_length=255,
                verbose_name='Type',
            ),
        ),
        migrations.AddField(
            model_name='baseadmission',
            name='submitted_at',
            field=models.DateTimeField(null=True, verbose_name='Submission date'),
        ),
        migrations.RunPython(forward, reverse_code=backward),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='admission_submission_date',
        ),
    ]
