# Generated by Django 3.2.16 on 2023-02-09 15:30

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0090_move_external_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='residence_permit',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=None, verbose_name='Residence permit covering the entire course'),
        ),
    ]
