# Generated by Django 3.2.16 on 2023-02-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0091_continuingeducationadmission_residence_permit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='bachelor_cycle_continuation',
        ),
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='bachelor_cycle_continuation_certificate',
        ),
    ]
