# Generated by Django 3.2.16 on 2023-02-20 16:48

from django.db import migrations, models
import django.db.models.deletion

from admission.models import AdmissionTask


def forward(apps, schema_editor):
    """Remove previous tasks"""
    AdmissionTask.objects.all().delete()


def backward(apps, schema_editor):
    """Remove previous tasks"""
    AdmissionTask.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0093_pdf_recap'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
        migrations.AlterField(
            model_name='admissiontask',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admission.baseadmission'),
        ),
    ]
