# Generated by Django 3.2.17 on 2023-03-14 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0647_merge_20230113_1039'),
        ('admission', '0096_last_admission_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadmission',
            name='last_update_author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='base.person',
                verbose_name='Last update author',
            ),
        ),
    ]
