# Generated by Django 3.2.17 on 2023-03-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0097_last_update_admission_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaleducationadmission',
            name='late_enrollment',
            field=models.BooleanField(blank=True, null=True, verbose_name='Late enrollment'),
        ),
    ]
