# Generated by Django 3.2.18 on 2023-03-31 11:19

from django.db import migrations, models
import django.contrib.postgres.fields


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0647_merge_20230113_1039'),
        ('admission', '0098_generaleducationadmission_late_enrollment'),
    ]

    operations = [
        migrations.RenameModel('CddManager', 'CddConfigurator'),
        migrations.RenameModel('SicManager', 'CentralManager'),
        migrations.RenameModel('SicDirector', 'SicManagement'),
        migrations.AlterModelOptions(
            name='cddconfigurator',
            options={'verbose_name': 'Role: CDD configurator', 'verbose_name_plural': 'Role: CDD configurators'},
        ),
        migrations.AlterModelOptions(
            name='centralmanager',
            options={'verbose_name': 'Role: Central manager', 'verbose_name_plural': 'Role: Central managers'},
        ),
        migrations.AlterModelOptions(
            name='sicmanagement',
            options={'verbose_name': 'Role: SIC management', 'verbose_name_plural': 'Role: SIC management'},
        ),
        migrations.AddField(
            model_name='centralmanager',
            name='entity',
            field=models.ForeignKey(
                # Entité UCL
                default=2852, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.entity'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centralmanager',
            name='scopes',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[('ALL', 'ALL'), ('IUFC', 'IUFC'), ('DOCTORAT', 'DOCTORAT')], max_length=200
                ),
                blank=True,
                default=['ALL', 'DOCTORAT', 'IUFC'],
                size=None,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centralmanager',
            name='with_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sicmanagement',
            name='entity',
            field=models.ForeignKey(
                # Entité UCL
                default=2852, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.entity'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sicmanagement',
            name='with_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cddconfigurator',
            name='entity',
            field=models.ForeignKey(
                limit_choices_to={'entityversion__entity_type': 'DOCTORAL_COMMISSION'},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='base.entity',
            ),
        ),
        migrations.CreateModel(
            name='ProgramManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+',
                                                      to='base.educationgroup')),
                ('person',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.person')),
            ],
            options={
                'verbose_name': 'Role: Program manager',
                'verbose_name_plural': 'Role: Program managers',
                'unique_together': {('person', 'education_group')},
            },
        ),
    ]
