# Generated by Django 3.2.18 on 2023-04-28 17:48

from django.db import migrations, models


def forward(apps, schema_editor):
    BaseAdmission = apps.get_model("admission", "BaseAdmission")
    for admission in BaseAdmission.objects.filter(doctorateadmission__pk__isnull=False):
        admission.submitted_profile = admission.doctorateadmission.submitted_profile
        admission.save(update_fields=['submitted_profile'])


def backward(apps, schema_editor):
    BaseAdmission = apps.get_model("admission", "BaseAdmission")
    for admission in BaseAdmission.objects.filter(doctorateadmission__pk__isnull=False):
        admission.doctorateadmission.submitted_profile = admission.submitted_profile
        admission.doctorateadmission.save(update_fields=['submitted_profile'])


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0099_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadmission',
            name='submitted_profile',
            field=models.JSONField(default=dict, verbose_name='Submitted profile'),
        ),
        migrations.RunPython(code=forward, reverse_code=backward),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='submitted_profile',
        ),
    ]
