# Generated by Django 3.2.19 on 2023-07-24 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0100_submitted_profile_to_baseadmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('OUVERT', 'open'), ('ANNULE', 'cancelled'), ('EN_ATTENTE', 'pending'), ('EXPIRE', 'expired'), ('ECHOUE', 'failed'), ('PAYE', 'paid')], max_length=10)),
                ('expiration_date', models.DateTimeField(null=True)),
                ('method', models.CharField(choices=[('BANCONTACT', 'bancontact'), ('CARTE_DE_CREDIT', 'creditcard'), ('VIREMENT_BANCAIRE', 'banktransfer')], max_length=17, blank=True)),
                ('creation_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('dashboard_url', models.URLField()),
                ('checkout_url', models.URLField(blank=True)),
                ('payment_url', models.URLField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_payment', to='admission.baseadmission')),
            ],
        ),
    ]
