# Generated by Django 3.2.18 on 2023-06-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0647_merge_20230113_1039'),
        ('admission', '0101_jury'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='base.entity', verbose_name='Entity')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.person', verbose_name='Person')),
            ],
        ),
    ]
