# Generated by Django 3.2.18 on 2023-04-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0101_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionformiteminstantiation',
            name='admission',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='admission.baseadmission',
                verbose_name='Admission',
            ),
        ),
        migrations.AlterField(
            model_name='admissionformiteminstantiation',
            name='display_according_education',
            field=models.CharField(
                choices=[
                    ('TOUTE_FORMATION', 'Every education'),
                    ('TYPE_DE_FORMATION', 'An education type'),
                    ('UNE_FORMATION', 'A specific education'),
                    ('UNE_SEULE_ADMISSION', 'Only one admission'),
                ],
                max_length=30,
                verbose_name='Display according education',
            ),
        ),
        migrations.AlterField(
            model_name='admissionformiteminstantiation',
            name='tab',
            field=models.CharField(
                choices=[
                    ('ETUDES_SECONDAIRES', 'Secondary studies'),
                    ('CURRICULUM', 'Curriculum'),
                    ('CHOIX_FORMATION', 'Course choice'),
                    ('INFORMATIONS_ADDITIONNELLES', 'Additional information'),
                    ('DOCUMENTS', 'Documents'),
                ],
                max_length=30,
                verbose_name='Tab',
            ),
        ),
    ]
