# Generated by Django 3.2.18 on 2023-05-05 18:16

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0103_document_mail_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadmission',
            name='checklist',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
