# Generated by Django 3.2.18 on 2023-06-27 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0105_jury'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ects',
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                default=0,
                help_text='Consult the credits grid released by your domain doctoral commission. Refer to the website of your commission for more details.',
                max_digits=3,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name='ECTS credits',
            ),
        ),
    ]
