# Generated by Django 3.2.19 on 2023-06-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0107_checklist_application_fees_mail_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('EN_BROUILLON', 'In draft'),
                    ('FRAIS_DOSSIER_EN_ATTENTE', 'Pending application fees'),
                    ('CONFIRMEE', 'Confirmed application (by student)'),
                    ('COMPLETEE', 'Completed application'),
                    ('ANNULEE', 'Cancelled application'),
                    ('A_COMPLETER_POUR_SIC', 'To be completed (by student) for SIC'),
                    ('A_COMPLETER_POUR_FAC_CDD', 'To be completed (by student) for FAC/CDD'),
                    ('TRAITEMENT_SIC', 'Processing by SIC'),
                    ('TRAITEMENT_FAC_CDD', 'Processing by Fac/CDD'),
                    ('ATTENTE_VALIDATION_DIRECTION', 'Pending validation from management'),
                    ('INSCRIPTION_AUTORISEE', 'Enrollment allowed'),
                    ('INSCRIPTION_REFUSEE', 'Enrollment denied'),
                    ('CLOTUREE', 'Closed'),
                    ('EN_RECOURS', 'Under appeal'),
                ],
                default='EN_BROUILLON',
                max_length=30,
            ),
        ),
    ]
