# Generated by Django 3.2.18 on 2023-06-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0110_alter_document_mail_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaleducationadmission',
            name='cycle_pursuit',
            field=models.CharField(
                choices=[('TO_BE_DETERMINED', 'TO_BE_DETERMINED'), ('YES', 'YES'), ('NO', 'NO')],
                default='TO_BE_DETERMINED',
                max_length=30,
            ),
        ),
    ]
