# Generated by Django 3.2.20 on 2023-08-03 15:36

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import osis_document.contrib.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0650_remove_admissionconditionline_external_id'),
        ('admission', '0112_checklist_faculty_decision_mail_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalApprovalCondition',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name_fr', models.CharField(max_length=255, verbose_name='French name')),
                ('name_en', models.CharField(max_length=255, verbose_name='English name')),
            ],
            options={
                'verbose_name': 'Additional approval condition',
                'verbose_name_plural': 'Additional approval conditions',
            },
        ),
        migrations.CreateModel(
            name='RefusalReasonCategory',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name_fr', models.CharField(max_length=255, verbose_name='French name')),
                ('name_en', models.CharField(max_length=255, verbose_name='English name')),
            ],
            options={
                'verbose_name': 'Refusal reason category',
                'verbose_name_plural': 'Refusal reason categories',
            },
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='annual_program_contact_person_email',
            field=models.EmailField(
                blank=True,
                default='',
                max_length=254,
                verbose_name='Email of the contact person for the design of the annual program',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='annual_program_contact_person_name',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                verbose_name='Name of the contact person for the design of the annual program',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='fac_approval_certificate',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name='Approval certificate of faculty',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='fac_refusal_certificate',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name='Refusal certificate of faculty',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='free_additional_approval_conditions',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                default=list,
                size=None,
                verbose_name='Free additional approval conditions',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='join_program_fac_comment',
            field=models.TextField(
                blank=True, default='', verbose_name='Faculty comment about the collaborative program'
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='other_fac_refusal_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other faculty refusal reason'),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='other_training_accepted_by_fac',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='base.educationgroupyear',
                verbose_name='Other training accepted by the faculty',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='prerequisite_courses_fac_comment',
            field=models.TextField(blank=True, default='', verbose_name='Other information about prerequisite courses'),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='program_planned_years_number',
            field=models.SmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                verbose_name='Number of years required for the full program (including prerequisite courses)',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='with_additional_approval_conditions',
            field=models.BooleanField(
                blank=True, null=True, verbose_name='Are there any additional conditions (subject to ...)?'
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='with_prerequisite_courses',
            field=models.BooleanField(blank=True, null=True, verbose_name='Are there any prerequisite courses?'),
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('EN_BROUILLON', 'In draft'),
                    ('FRAIS_DOSSIER_EN_ATTENTE', 'Pending application fees'),
                    ('CONFIRMEE', 'Confirmed application (by student)'),
                    ('ANNULEE', 'Cancelled application'),
                    ('A_COMPLETER_POUR_SIC', 'To be completed (by student) for SIC'),
                    ('COMPLETEE_POUR_SIC', 'Completed (by student) for SIC'),
                    ('TRAITEMENT_FAC', 'Processing by Fac'),
                    ('A_COMPLETER_POUR_FAC', 'To be completed (by student) for FAC'),
                    ('COMPLETEE_POUR_FAC', 'Completed (by student) for FAC'),
                    ('RETOUR_DE_FAC', 'Feedback from FAC'),
                    ('ATTENTE_VALIDATION_DIRECTION', 'Pending validation from management'),
                    ('INSCRIPTION_AUTORISEE', 'Enrollment allowed'),
                    ('INSCRIPTION_REFUSEE', 'Enrollment denied'),
                    ('CLOTUREE', 'Closed'),
                ],
                default='EN_BROUILLON',
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name='RefusalReason',
            fields=[
                (
                    'uuid',
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name_fr', models.CharField(max_length=255, verbose_name='French name')),
                ('name_en', models.CharField(max_length=255, verbose_name='English name')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='admission.refusalreasoncategory',
                        verbose_name='Category',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Refusal reason',
                'verbose_name_plural': 'Refusal reasons',
            },
        ),
        migrations.CreateModel(
            name='AdmissionPrerequisiteCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'admission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='admission.generaleducationadmission'
                    ),
                ),
                (
                    'course',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='+',
                        to='base.learningunityear',
                        to_field='uuid',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='additional_approval_conditions',
            field=models.ManyToManyField(
                blank=True,
                related_name='_admission_generaleducationadmission_additional_approval_conditions_+',
                to='admission.AdditionalApprovalCondition',
                verbose_name='Additional approval conditions',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='fac_refusal_reason',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='admission.refusalreason',
                verbose_name='Faculty refusal reason',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='prerequisite_courses',
            field=models.ManyToManyField(
                blank=True,
                through='admission.AdmissionPrerequisiteCourses',
                to='base.LearningUnitYear',
                verbose_name='Prerequisite courses',
            ),
        ),
    ]
