# Generated by Django 3.2.20 on 2023-08-08 18:38

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0113_checklist_faculty_decision_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuingeducationadmission',
            name='billing_address_place',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='erasmus_mundus_scholarship',
        ),
        migrations.AddField(
            model_name='accounting',
            name='a_card',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='A card'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='stateless_person_proof',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), default=list, size=None, verbose_name='Copy of official document from the local authority or Foreign Nationals Office proving stateless status'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='additional_documents',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=None, verbose_name='Additional documents'),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='additional_documents',
            field=osis_document.contrib.fields.FileField(base_field=models.UUIDField(), blank=True, default=list, size=None, verbose_name='Additional documents'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='assimilation_2_situation_type',
            field=models.CharField(blank=True, choices=[('REFUGIE', 'I am a refugee'), ('DEMANDEUR_ASILE', 'I am an asylum seeker'), ('APATRIDE', 'I am a stateless person'), ('PROTECTION_SUBSIDIAIRE', 'I have been granted subsidiary protection'), ('PROTECTION_TEMPORAIRE', 'I have been granted temporary protection')], default='', max_length=64, verbose_name='Assimilation 2 situation types'),
        ),
    ]
