# Generated by Django 3.2.21 on 2023-09-14 15:47

from django.db import migrations, models
from django.db.models import Count, Value
from django.db.models.functions import Concat


def forward(apps, schema_editor):
    # Make the internal label unique for all items
    AdmissionFormItem = apps.get_model('admission', 'AdmissionFormItem')

    duplicated_labels = (
        AdmissionFormItem.objects.values_list('internal_label', flat=True)
        .alias(Count('id'))
        .order_by()
        .filter(id__count__gt=1)
    )

    AdmissionFormItem.objects.filter(internal_label__in=duplicated_labels).update(
        internal_label=Concat('internal_label', Value('.'), 'id'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0116_onlinepayment'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
        migrations.AddField(
            model_name='admissionformiteminstantiation',
            name='diploma_nationality',
            field=models.CharField(
                choices=[
                    ('BELGE', 'Belgian'),
                    ('NON_BELGE', 'Not Belgian'),
                    ('UE', 'UE'),
                    ('NON_UE', 'Not UE'),
                    ('TOUS', 'All'),
                ],
                default='TOUS',
                max_length=30,
                verbose_name='Diploma nationality',
                help_text="Takes into account the nationality of higher education diplomas. "
                          "'Not Belgian' means that the candidate hasn't got any Belgian diploma but has a foreign "
                          "diploma. Similarly, 'Not UE' means that the candidate hasn't got any UE diploma but "
                          "has a non-UE diploma.",
            ),
        ),
        migrations.AlterField(
            model_name='admissionformitem',
            name='internal_label',
            field=models.CharField(max_length=255, unique=True, verbose_name='Internal label'),
        ),
    ]
