# Generated by Django 3.2.21 on 2023-09-14 15:47
import datetime

from django.db import migrations, transaction

from base.models.enums.academic_calendar_type import AcademicCalendarTypes


def forward(apps, schema_editor):
    AcademicCalendar = apps.get_model('base', 'AcademicCalendar')

    with transaction.atomic():
        for calendar in AcademicCalendar.objects.filter(
            reference=AcademicCalendarTypes.ADMISSION_POOL_HUE5_FOREIGN_RESIDENCY.name,
        ):
            calendar.end_date = datetime.date(calendar.end_date.year, 3, 31)
            calendar.save()


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0118_alter_accounting_sport_affiliation'),
        ('base', '0656_auto_20230906_1550'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
