# Generated by Django 3.2.21 on 2023-09-21 13:38

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0119_change_pool_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiontask',
            name='type',
            field=models.CharField(
                choices=[
                    ('ARCHIVE', 'PDF Export'),
                    ('CANVAS', 'Canvas'),
                    ('CONFIRMATION_SUCCESS', 'Confirmation success attestation'),
                    ('GENERAL_RECAP', 'PDF recap for a general education admission'),
                    ('CONTINUING_RECAP', 'PDF recap for a continuing education admission'),
                    ('DOCTORATE_RECAP', 'PDF recap for a doctorate education admission'),
                    ('GENERAL_MERGE', 'Merging of each document field of a general proposition into one PDF'),
                    ('CONTINUING_MERGE', 'Merging of each document field of a continuing proposition into one PDF'),
                    ('DOCTORATE_MERGE', 'Merging of each document field of a doctorate proposition into one PDF'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='baseadmission',
            name='curriculum',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=1,
                verbose_name='Curriculum',
            ),
        ),
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='additional_documents',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=10,
                verbose_name='Additional documents',
            ),
        ),
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='residence_permit',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=1,
                verbose_name='Residence permit covering the entire course',
            ),
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='additional_documents',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=10,
                verbose_name='Additional documents',
            ),
        ),
    ]
