# Generated by Django 3.2.21 on 2023-09-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0120_update_max_file_fields_and_async_task_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinepayment',
            name='method',
            field=models.CharField(
                blank=True,
                choices=[
                    ('BANCONTACT', 'bancontact'),
                    ('CREDIT_CARD', 'creditcard'),
                    ('BANK_TRANSFER', 'banktransfer'),
                ],
                default='',
                max_length=17,
            ),
        ),
    ]
