# Generated by Django 3.2.21 on 2023-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0122_diplomaticpost'),
    ]

    operations = [
        # These fields will be removed in the next migration so we define empty values in case of reverse migration
        migrations.AlterField(
            model_name='refusalreason',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='English name', default=''),
        ),
        migrations.AlterField(
            model_name='refusalreasoncategory',
            name='name_en',
            field=models.CharField(max_length=255, verbose_name='English name', default=''),
        ),
    ]
