# Generated by Django 3.2.21 on 2023-10-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osis_profile', '0015_alter_professionalexperience_external_id'),
        ('base', '0656_auto_20230906_1550'),
        ('admission', '0125_checklist_faculty_decision_mail_templates_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadmission',
            name='are_secondary_studies_access_title',
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name='Are the secondary studies the access title for this admission?',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='admission_requirement',
            field=models.CharField(
                blank=True,
                choices=[
                    ('NON_CONCERNE', 'Non concerné'),
                    ('SNU_PASSERELLE_1', 'SNU Passerelle 1'),
                    ('SNU_PASSERELLE_3', 'SNU Passerelle 3'),
                    ('VAE', 'VAE'),
                    ('PROGRAMME_AMENAGE', 'Progr. aménagé'),
                    ('VALORISATION_180_ECTS', 'Valorisation 180 ECTS'),
                    ('VALORISATION_240_ECTS', 'Valorisation 240 ECTS'),
                    ('VALORISATION_300_ECTS', 'Valorisation 300 ECTS'),
                    ('SECONDAIRE', 'SEC'),
                    ('BAC', 'BAC'),
                    ('BAC_EPM', 'BAC - EPM'),
                    ('BAMA15', 'BAMA15'),
                    ('MASTER', 'Master'),
                    ('UNI_SNU_AUTRE', 'UNI/SNU Autres'),
                    ('PARCOURS', 'Parcours'),
                    ('EXAMEN_ADMISSION', 'Examen admission'),
                    ('SNU_TYPE_COURT', 'SNU Type court'),
                    ('SNU_TYPE_LONG_1ER_CYCLE', 'SNU Type long 1er cycle'),
                    ('SNU_TYPE_LONG_2EME_CYCLE', 'SNU Type long 2ème cycle'),
                    ('MASTER_EPM', 'Master - EPM'),
                    ('BAC_MASTER_ANTICIPE', 'BAC (Master anticipé)'),
                    ('INDETERMINE', 'indéterminé'),
                ],
                default='',
                max_length=30,
                verbose_name='Admission requirement',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='admission_requirement_year',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='base.academicyear',
                verbose_name='Admission requirement year',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='foreign_access_title_equivalency_effective_date',
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name='Foreign access title equivalence effective date',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='foreign_access_title_equivalency_state',
            field=models.CharField(
                blank=True,
                choices=[('DEFINITIVE', 'Definitive'), ('PROVISOIRE', 'Provisional')],
                default='',
                max_length=30,
                verbose_name='Foreign access title equivalence state',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='foreign_access_title_equivalency_status',
            field=models.CharField(
                blank=True,
                choices=[
                    ('COMPLETE', 'Completed'),
                    ('RESTRICTIVE', 'Restricted'),
                    ('EN_ATTENTE', 'Waiting'),
                    ('NON_RENSEIGNE', 'Not specified'),
                ],
                default='',
                max_length=30,
                verbose_name='Foreign access title equivalence status',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='foreign_access_title_equivalency_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('NON_CONCERNE', 'Not concerned'),
                    ('EQUIVALENCE_CESS', 'CESS equivalence'),
                    ('EQUIVALENCE_GRADE_ACADEMIQUE_FWB', 'FWB academic degree equivalence'),
                    ('EQUIVALENCE_DE_NIVEAU', 'Level equivalence'),
                    ('NON_RENSEIGNE', 'Not specified'),
                ],
                default='',
                max_length=50,
                verbose_name='Foreign access title equivalence type',
            ),
        ),
        migrations.CreateModel(
            name='AdmissionProfessionalValuatedExperiences',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_access_title',
                    models.BooleanField(
                        default=False,
                        verbose_name='Is access title of the proposition?',
                    ),
                ),
                (
                    'baseadmission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='admission.baseadmission',
                        to_field='uuid',
                    ),
                ),
                (
                    'professionalexperience',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='professional_valuated_experiences',
                        to='osis_profile.professionalexperience',
                        to_field='uuid',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionEducationalValuatedExperiences',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_access_title',
                    models.BooleanField(
                        default=False,
                        verbose_name='Is access title of the proposition?',
                    ),
                ),
                (
                    'baseadmission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='admission.baseadmission',
                        to_field='uuid',
                    ),
                ),
                (
                    'educationalexperience',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='educational_valuated_experiences',
                        to='osis_profile.educationalexperience',
                        to_field='uuid',
                    ),
                ),
            ],
        ),
    ]
