# Generated by Django 3.2.21 on 2023-10-24 14:32

from django.db import migrations, transaction


def initialize_new_models_for_valuated_experiences(apps, schema_editor):
    BaseAdmission = apps.get_model('admission', 'BaseAdmission')
    AdmissionEducationalValuatedExperiences = apps.get_model('admission', 'AdmissionEducationalValuatedExperiences')
    AdmissionProfessionalValuatedExperiences = apps.get_model('admission', 'AdmissionProfessionalValuatedExperiences')

    admission_valuated_educational_experiences = BaseAdmission.educational_valuated_experiences.through.objects.all()
    admission_valuated_professional_experiences = BaseAdmission.professional_valuated_experiences.through.objects.all()

    with transaction.atomic():
        for admission_experience in admission_valuated_educational_experiences:
            AdmissionEducationalValuatedExperiences.objects.create(
                baseadmission=admission_experience.baseadmission,
                educationalexperience=admission_experience.educationalexperience,
            )

        for admission_experience in admission_valuated_professional_experiences:
            AdmissionProfessionalValuatedExperiences.objects.create(
                baseadmission=admission_experience.baseadmission,
                professionalexperience=admission_experience.professionalexperience,
            )


def initialize_old_models_for_valuated_experiences(apps, schema_editor):
    AdmissionEducationalValuatedExperiences = apps.get_model('admission', 'AdmissionEducationalValuatedExperiences')
    AdmissionProfessionalValuatedExperiences = apps.get_model('admission', 'AdmissionProfessionalValuatedExperiences')

    admission_valuated_educational_experiences = AdmissionEducationalValuatedExperiences.objects.select_related(
        'baseadmission',
        'educationalexperience',
    ).all()
    admission_valuated_professional_experiences = AdmissionProfessionalValuatedExperiences.objects.select_related(
        'baseadmission',
        'professionalexperience',
    ).all()

    with transaction.atomic():
        for admission_experience in admission_valuated_educational_experiences:
            admission_experience.baseadmission.educational_valuated_experiences.add(
                admission_experience.educationalexperience,
            )

        for admission_experience in admission_valuated_professional_experiences:
            admission_experience.baseadmission.professional_valuated_experiences.add(
                admission_experience.professionalexperience,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0126_admission_access_fields_and_valuated_experiences_evolutions_1'),
    ]

    operations = [
        migrations.RunPython(
            initialize_new_models_for_valuated_experiences,
            initialize_old_models_for_valuated_experiences,
        ),
    ]
