# Generated by Django 3.2.21 on 2023-10-24 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0127_valuated_experiences_evolutions_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseadmission',
            name='educational_valuated_experiences',
        ),
        migrations.RemoveField(
            model_name='baseadmission',
            name='professional_valuated_experiences',
        ),
    ]
