# Generated by Django 3.2.21 on 2023-10-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osis_profile', '0015_alter_professionalexperience_external_id'),
        ('admission', '0128_valuated_experiences_evolutions_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadmission',
            name='educational_valuated_experiences',
            field=models.ManyToManyField(
                blank=True,
                related_name='valuated_from_admission',
                through='admission.AdmissionEducationalValuatedExperiences',
                to='osis_profile.EducationalExperience',
                verbose_name='The educational experiences that have been valuated from this admission.',
            ),
        ),
        migrations.AddField(
            model_name='baseadmission',
            name='professional_valuated_experiences',
            field=models.ManyToManyField(
                blank=True,
                related_name='valuated_from_admission',
                through='admission.AdmissionProfessionalValuatedExperiences',
                to='osis_profile.ProfessionalExperience',
                verbose_name='The professional experiences that have been valuated from this admission.',
            ),
        ),
    ]
