# Generated by Django 3.2.21 on 2023-10-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0656_auto_20230906_1550'),
        ('admission', '0131_alter_email_confirm_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaleducationadmission',
            name='financability_computed_rule',
            field=models.CharField(
                choices=[
                    ('PREMIERE_INSCRIPTION_MEME_CYCLE', 'PREMIERE_INSCRIPTION_MEME_CYCLE'),
                    ('SECONDE_INSCRIPTION_MEME_CYCLE', 'SECONDE_INSCRIPTION_MEME_CYCLE'),
                    (
                        'TROISIEME_INSCRIPTION_PREMIER_CYCLE_AVEC_REORIENTATION',
                        'TROISIEME_INSCRIPTION_PREMIER_CYCLE_AVEC_REORIENTATION',
                    ),
                    ('SUR_3_ANS_45_CREDITS_MEME_CYCLE', 'SUR_3_ANS_45_CREDITS_MEME_CYCLE'),
                    ('SUR_2_ANS_45_CREDITS_MEME_CYCLE', 'SUR_2_ANS_45_CREDITS_MEME_CYCLE'),
                    ('ACQUIS_75_POURCENTS_CREDITS', 'ACQUIS_75_POURCENTS_CREDITS'),
                    ('SUR_3_ANS_MOITIE_CREDITS', 'SUR_3_ANS_MOITIE_CREDITS'),
                    ('SUR_2_ANS_MOITIE_CREDITS', 'SUR_2_ANS_MOITIE_CREDITS'),
                    ('SUR_3_ANS_45_CREDITS_11BA', 'SUR_3_ANS_45_CREDITS_11BA'),
                    ('SUR_2_ANS_45_CREDITS_11BA', 'SUR_2_ANS_45_CREDITS_11BA'),
                    ('CENT_VINGT_CREDITS_NON_ENCORE_ACQUIS', 'CENT_VINGT_CREDITS_NON_ENCORE_ACQUIS'),
                    ('PREMIERE_REORIENTATION_SUR_5_ANS', 'PREMIERE_REORIENTATION_SUR_5_ANS'),
                    ('CINQ_G_1ERE_INSCRIPTION_MEME_CYCLE', 'CINQ_G_1ERE_INSCRIPTION_MEME_CYCLE'),
                    ('CINQ_G_2EME_INSCRIPTION_MEME_CYCLE', 'CINQ_G_2EME_INSCRIPTION_MEME_CYCLE'),
                    ('CINQ_G_2EME_INSCRIPTION_AVEC_REORIENTATION', 'CINQ_G_2EME_INSCRIPTION_AVEC_REORIENTATION'),
                    ('INDISPONIBLE', 'INDISPONIBLE'),
                    ('NON_CONCERNE', 'NON_CONCERNE'),
                    ('NON_FINANCABLE', 'NON_FINANCABLE'),
                    ('A_CLARIFIER', 'A_CLARIFIER'),
                ],
                default='',
                editable=False,
                max_length=100,
                verbose_name='Financability computed rule',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='financability_computed_rule_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Financability computed rule on'),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='financability_rule',
            field=models.CharField(
                choices=[
                    ('PREMIERE_INSCRIPTION_MEME_CYCLE', 'PREMIERE_INSCRIPTION_MEME_CYCLE'),
                    ('SECONDE_INSCRIPTION_MEME_CYCLE', 'SECONDE_INSCRIPTION_MEME_CYCLE'),
                    (
                        'TROISIEME_INSCRIPTION_PREMIER_CYCLE_AVEC_REORIENTATION',
                        'TROISIEME_INSCRIPTION_PREMIER_CYCLE_AVEC_REORIENTATION',
                    ),
                    ('SUR_3_ANS_45_CREDITS_MEME_CYCLE', 'SUR_3_ANS_45_CREDITS_MEME_CYCLE'),
                    ('SUR_2_ANS_45_CREDITS_MEME_CYCLE', 'SUR_2_ANS_45_CREDITS_MEME_CYCLE'),
                    ('ACQUIS_75_POURCENTS_CREDITS', 'ACQUIS_75_POURCENTS_CREDITS'),
                    ('SUR_3_ANS_MOITIE_CREDITS', 'SUR_3_ANS_MOITIE_CREDITS'),
                    ('SUR_2_ANS_MOITIE_CREDITS', 'SUR_2_ANS_MOITIE_CREDITS'),
                    ('SUR_3_ANS_45_CREDITS_11BA', 'SUR_3_ANS_45_CREDITS_11BA'),
                    ('SUR_2_ANS_45_CREDITS_11BA', 'SUR_2_ANS_45_CREDITS_11BA'),
                    ('CENT_VINGT_CREDITS_NON_ENCORE_ACQUIS', 'CENT_VINGT_CREDITS_NON_ENCORE_ACQUIS'),
                    ('PREMIERE_REORIENTATION_SUR_5_ANS', 'PREMIERE_REORIENTATION_SUR_5_ANS'),
                    ('CINQ_G_1ERE_INSCRIPTION_MEME_CYCLE', 'CINQ_G_1ERE_INSCRIPTION_MEME_CYCLE'),
                    ('CINQ_G_2EME_INSCRIPTION_MEME_CYCLE', 'CINQ_G_2EME_INSCRIPTION_MEME_CYCLE'),
                    ('CINQ_G_2EME_INSCRIPTION_AVEC_REORIENTATION', 'CINQ_G_2EME_INSCRIPTION_AVEC_REORIENTATION'),
                ],
                default='',
                max_length=100,
                verbose_name='Financability rule',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='financability_rule_established_by',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='base.person',
                verbose_name='Financability rule established by',
            ),
        ),
    ]
