# Generated by Django 3.2.12 on 2022-08-22 15:19

from django.db import migrations

from admission.mail_templates import (
    ADMISSION_EMAIL_REQUEST_FAC_DOCUMENTS_GENERAL,
    ADMISSION_EMAIL_REQUEST_SIC_DOCUMENTS_GENERAL,
    ADMISSION_EMAIL_REQUEST_FAC_DOCUMENTS_DOCTORATE,
    ADMISSION_EMAIL_REQUEST_SIC_DOCUMENTS_DOCTORATE,
    ADMISSION_EMAIL_REQUEST_FAC_DOCUMENTS_CONTINUING,
    ADMISSION_EMAIL_SUBMISSION_CONFIRM_WITH_SUBMITTED_AND_NOT_SUBMITTED_GENERAL,
    ADMISSION_EMAIL_SUBMISSION_CONFIRM_WITH_SUBMITTED_GENERAL,
)
from osis_mail_template import MailTemplateMigration


class Migration(migrations.Migration):
    dependencies = [
        ('admission', '0132_checklist_financability'),
    ]

    SIC_OBJECT_TEMPLATE = {
        'en': 'Complete your UCLouvain application ({admission_reference})',
        'fr-be': "Inscription UCLouvain – compléter votre dossier ({admission_reference})",
    }

    SIC_CONTENT_TEMPLATE = {
        'en': '''<p>{salutation} {candidate_first_name} {candidate_last_name},</p>

                <p>
                    Thank you for sending your application for admission to the {training_title} ({training_campus}) - 
                    {training_acronym} course beginning in the {training_year} academic year.
                </p>
        
                <p>
                    Your application is still missing essential documents.
                </p>
        
                <div>
                    <p>
                        First, in order to evaluate your application for admission, <span style="font-weight:bold">
                        the documents listed below must be added to your <a href="{admissions_link_front}">online 
                        application file</a> by {request_deadline}</span> :
                    </p>
        
                    {requested_documents}
                    
                    <p>
                        Your application will no longer be considered if you do not provide the above documents by 
                        {request_deadline}. No action will be taken on documents received by email.
                    </p>

                </div>
                
                <div>
                    <p>
                        Second, the documents listed below must be provided as soon as possible via your 
                        <a href="{admissions_link_front}">online application file</a>.
                    </p>
                    
                    {later_requested_documents}
                </div>
                
                <p>
                    Sincerely,
                </p>
        
                <p>
                    The Enrolment Office
                </p>

                        ''',
        'fr-be': '''<p>{salutation} {candidate_first_name} {candidate_last_name},</p>

        <p>
            Votre demande d'inscription au programme {training_title} ({training_campus}) - {training_acronym} pour
            l'année académique {training_year} nous est bien parvenue et nous vous en remercions.
        </p>

        <p>
            Après vérification, nous constatons qu'il manque encore certains éléments indispensables à votre dossier.
        </p>

        <div>
            <p>
                Afin de pouvoir poursuivre l’analyse de votre demande d’admission, <span style="font-weight:bold">les 
                documents ci-dessous  doivent être ajoutés obligatoirement à <a href="{admissions_link_front}">votre 
                dossier en ligne</a> pour le {request_deadline}</span> :
            </p>

            {requested_documents}
            
            <p>
                Nous vous invitons vivement à respecter ce délai du {request_deadline}. En effet, votre dossier sera 
                administrativement clôturé si vous ne fournissez pas les documents dans les délais mentionnés. Aucune 
                suite ne sera donnée aux documents envoyés par mail.
            </p>

        </div>
        
        <div>
            <p>
                Par ailleurs, nous profitons de ce courrier pour vous signaler que les documents complémentaires 
                ci-dessous sont à nous fournir dès que possible. Si vous êtes déjà en possession de ceux-ci nous vous 
                invitons à nous les faire parvenir sans attendre via <a href="{admissions_link_front}">votre dossier 
                en ligne</a>.
            </p>
            
            {later_requested_documents}
        </div>
        
        <p>
            Veuillez agréer l'expression de nos salutations distinguées.
        </p>

        <p>
            Le Service des inscriptions
        </p>
        ''',
    }

    FAC_OBJECT_TEMPLATE = SIC_OBJECT_TEMPLATE

    FAC_CONTENT_TEMPLATE = {
        'en': '''<p>{salutation} {candidate_first_name} {candidate_last_name},</p>

                <p>
                    Thank you for sending your application for admission to the {training_title} ({training_campus}) - 
                    {training_acronym} course beginning in the {training_year} academic year.
                </p>

                <p>
                    Your application is still missing essential documents.
                </p>

                <div>
                    <p>
                        First, in order to evaluate your application for admission, <span style="font-weight:bold">the 
                        documents listed below must be added to your <a href="{admissions_link_front}">online 
                        application file</a> by {request_deadline}</span> :
                    </p>

                    {requested_documents}

                    <p>
                        Your application will no longer be considered if you do not provide the above documents by 
                        {request_deadline}. No action will be taken on documents received by email.
                    </p>
                </div>

                <div>
                    <p>
                        Second, the documents listed below must be provided as soon as possible via your 
                        <a href="{admissions_link_front}">online application file</a>.
                    </p>

                    {later_requested_documents}
                </div>

                <p>
                    Sincerely,
                </p>

                <p>
                    The UCLouvain
                </p>

                        ''',
        'fr-be': '''<p>{salutation} {candidate_first_name} {candidate_last_name},</p>

        <p>
            Votre demande d'inscription au programme {training_title} ({training_campus}) - {training_acronym} pour
            l'année académique {training_year} nous est bien parvenue et nous vous en remercions.
        </p>

        <p>
            Après vérification, nous constatons qu'il manque encore certains éléments indispensables à votre dossier.
        </p>

        <div>
            <p>
                Afin de pouvoir poursuivre l’analyse de votre demande d’admission, <span style="font-weight:bold">les 
                documents ci-dessous doivent être ajoutés obligatoirement à <a href="{admissions_link_front}">votre 
                dossier en ligne</a> pour le {request_deadline}</span> :
            </p>

            {requested_documents}

            <p>
                Nous vous invitons vivement à respecter ce délai du {request_deadline}. En effet, votre dossier sera 
                administrativement clôturé si vous ne fournissez pas les documents dans les délais mentionnés. Aucune 
                suite ne sera donnée aux documents envoyés par mail.
            </p>
        </div>

        <div>
            <p>
                Par ailleurs, nous profitons de ce courrier pour vous signaler que les documents complémentaires 
                ci-dessous sont à nous fournir dès que possible. Si vous êtes déjà en possession de ceux-ci nous vous 
                invitons à nous les faire parvenir sans attendre via <a href="{admissions_link_front}">votre dossier 
                en ligne</a>.
            </p>

            {later_requested_documents}
        </div>

        <p>
            Veuillez agréer l'expression de nos salutations distinguées.
        </p>

        <p>
            L'UCLouvain
        </p>
        ''',
    }

    DOCUMENT_SUBMISSION_CONFIRM_TEMPLATE_OBJECT = {
        'en': 'UCLouvain enrolment ({admission_reference}) : acknowledgement of receipt of your documents',
        'fr-be': "Inscription UCLouvain – accusé de réception de vos documents ({admission_reference})",
    }

    DOCUMENT_SUBMISSION_CONFIRM_CONTENT_TEMPLATE_WITH_SUBMITTED_AND_NOT_SUBMITTED = {
        'en': '''<p>{salutation} {candidate_first_name} {candidate_last_name},</p>

                <p>
                    Concerning your application for admission to the {training_title} ({training_campus}) 
                    ({training_acronym}) course for the {training_year} academic year, we confirm receipt of the 
                    following required documents:
                </p>

                {requested_submitted_documents}
                
                <p>
                    We will evaluate your documents as quickly as possible and get back to you if they are incomplete 
                    or incorrect.
                </p>

                <p>
                    We remind you that the documents listed below have not yet been received. Please send them as soon 
                    as possible to <a href="mailto:{enrolment_service_email}">{enrolment_service_email}</a>:
                </p>

                {requested_not_submitted_documents}

                <p>
                    Sincerely,
                </p>

                <p>
                    The Enrolment Office
                </p>

                        ''',
        'fr-be': '''<p>{salutation} {candidate_first_name} {candidate_last_name},</p>

        <p>
            Dans le cadre de votre demande d'inscription au programme {training_title} ({training_campus}) - 
            {training_acronym} pour l'année académique {training_year}, nous vous confirmons avoir bien reçu les 
            documents suivants indispensables à l’analyse de votre inscription :
        </p>

        {requested_submitted_documents}
        
        <p>
            Nous procéderons à l’analyse de vos documents dans les meilleurs délais. Nous reviendrons vers vous si vos documents 
            s’avéraient être incomplets ou incorrects.
        </p>

        <p>
            Nous vous rappelons que certains documents n’ont pas été fournis à ce jour, et vous invitons à les fournir 
            dès que possible à l’adresse <a href="mailto:{enrolment_service_email}">{enrolment_service_email}</a> :
        </p>

        {requested_not_submitted_documents}

        <p>
            Veuillez agréer l'expression de nos salutations distinguées.
        </p>

        <p>
            Le Service des inscriptions
        </p>
        ''',
    }
    DOCUMENT_SUBMISSION_CONFIRM_CONTENT_TEMPLATE_WITH_SUBMITTED = {
        'en': '''<p>{salutation} {candidate_first_name} {candidate_last_name},</p>

                <p>
                    Concerning your application for admission to the {training_title} ({training_campus}) 
                    ({training_acronym}) course for the {training_year} academic year, we confirm receipt of the 
                    following required documents:
                </p>

                {requested_submitted_documents}
                
                <p>
                    We will evaluate your documents as quickly as possible and get back to you if they are incomplete 
                    or incorrect.
                </p>

                <p>
                    Sincerely,
                </p>

                <p>
                    The Enrolment Office
                </p>

                        ''',
        'fr-be': '''<p>{salutation} {candidate_first_name} {candidate_last_name},</p>

        <p>
            Dans le cadre de votre demande d'inscription au programme {training_title} ({training_campus}) - 
            {training_acronym} pour l'année académique {training_year}, nous vous confirmons avoir bien reçu les 
            documents suivants indispensables à l’analyse de votre inscription :
        </p>

        {requested_submitted_documents}
        
        <p>
            Nous procéderons à l’analyse de vos documents dans les meilleurs délais. Nous reviendrons vers vous si vos documents 
            s’avéraient être incomplets ou incorrects.
        </p>

        <p>
            Veuillez agréer l'expression de nos salutations distinguées.
        </p>

        <p>
            Le Service des inscriptions
        </p>
        ''',
    }
    operations = [
        MailTemplateMigration(
            ADMISSION_EMAIL_REQUEST_SIC_DOCUMENTS_GENERAL,
            SIC_OBJECT_TEMPLATE,
            SIC_CONTENT_TEMPLATE,
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_REQUEST_FAC_DOCUMENTS_GENERAL,
            FAC_OBJECT_TEMPLATE,
            FAC_CONTENT_TEMPLATE,
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_REQUEST_SIC_DOCUMENTS_DOCTORATE,
            SIC_OBJECT_TEMPLATE,
            SIC_CONTENT_TEMPLATE,
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_REQUEST_FAC_DOCUMENTS_DOCTORATE,
            FAC_OBJECT_TEMPLATE,
            FAC_CONTENT_TEMPLATE,
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_REQUEST_FAC_DOCUMENTS_CONTINUING,
            FAC_OBJECT_TEMPLATE,
            FAC_CONTENT_TEMPLATE,
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_SUBMISSION_CONFIRM_WITH_SUBMITTED_AND_NOT_SUBMITTED_GENERAL,
            DOCUMENT_SUBMISSION_CONFIRM_TEMPLATE_OBJECT,
            DOCUMENT_SUBMISSION_CONFIRM_CONTENT_TEMPLATE_WITH_SUBMITTED_AND_NOT_SUBMITTED,
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_SUBMISSION_CONFIRM_WITH_SUBMITTED_GENERAL,
            DOCUMENT_SUBMISSION_CONFIRM_TEMPLATE_OBJECT,
            DOCUMENT_SUBMISSION_CONFIRM_CONTENT_TEMPLATE_WITH_SUBMITTED,
        ),
    ]
