# Generated by Django 3.2.23 on 2023-12-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0133_alter_document_mail_templates_3'),
        ('admission', '0133_fix_notifications'),
    ]

    operations = [
    ]
