# Generated by Django 3.2.23 on 2023-12-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0134_merge_20231208_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseadmission',
            name='determined_pool',
            field=models.CharField(
                blank=True,
                choices=[
                    ('DELIBERATION', 'Deliberation'),
                    ('DISSERTATION_SUBMISSION', 'Dissertation submission'),
                    ('EXAM_ENROLLMENTS', 'Exam enrollments'),
                    ('BASCULEMENT_INSCRIPTION_EVALUATION', 'Exam enrollments period switching'),
                    ('SCORES_EXAM_DIFFUSION', 'Scores diffusion'),
                    ('SCORES_EXAM_SUBMISSION', 'Scores exam submission'),
                    ('ATTENDANCE_MARK', 'Attendance mark'),
                    ('TEACHING_CHARGE_APPLICATION', 'Application for vacant courses'),
                    ('ACCESS_SCHEDULE_CALENDAR', 'Access schedule calendar'),
                    ('COURSE_ENROLLMENT', 'Course enrollment'),
                    ('SUMMARY_COURSE_SUBMISSION', 'Summary course submission'),
                    ('SUMMARY_COURSE_SUBMISSION_FORCE_MAJEURE', 'Summary course submission force majeure'),
                    ('EDUCATION_GROUP_SWITCH', 'Education group switch'),
                    ('EDUCATION_GROUP_EDITION', 'Education group edition'),
                    ('EDUCATION_GROUP_EXTENDED_DAILY_MANAGEMENT', 'Education group extended daily management'),
                    ('EDUCATION_GROUP_LIMITED_DAILY_MANAGEMENT', 'Education group limited daily management'),
                    ('LEARNING_UNIT_EXTENDED_PROPOSAL_MANAGEMENT', 'Extended proposal management'),
                    ('LEARNING_UNIT_LIMITED_PROPOSAL_MANAGEMENT', 'Limited proposal management'),
                    ('PAYMENT_NOTICE_1_WARNING', 'Payment notice 1 warning'),
                    ('PAYMENT_NOTICE_2_WARNING', 'Payment notice 2 warning'),
                    ('COURSE_ENROLLMENT_SWITCHING_CALENDAR', 'Course enrollment switching'),
                    ('GENERAL_EDUCATION_ENROLLMENT', 'General education enrolment'),
                    ('DOCTORATE_EDUCATION_ENROLLMENT', 'Doctorate education enrolment'),
                    ('CONTINUING_EDUCATION_ENROLLMENT', 'Continuing education enrolment'),
                    ('ADMISSION_POOL_EXTERNAL_ENROLLMENT_CHANGE', 'Admission: pool External enrollment change'),
                    ('ADMISSION_POOL_EXTERNAL_REORIENTATION', 'Admission: pool External reorientation'),
                    ('ADMISSION_POOL_VIP', 'Admission: pool VIP'),
                    ('ADMISSION_POOL_HUE_UCL_PATHWAY_CHANGE', 'Admission: pool HUE UCL pathway change'),
                    ('ADMISSION_POOL_INSTITUT_CHANGE', 'Admission: pool Institute change'),
                    ('ADMISSION_POOL_UE5_BELGIAN', 'Admission: pool EU+5 nationality and Belgian access diploma'),
                    (
                        'ADMISSION_POOL_UE5_NON_BELGIAN',
                        'Admission: pool EU+5 nationality and non-Belgian access diploma',
                    ),
                    (
                        'ADMISSION_POOL_HUE5_BELGIUM_RESIDENCY',
                        'Admission: pool Nationality outside (EU+5) and residence in Belgium',
                    ),
                    (
                        'ADMISSION_POOL_HUE5_FOREIGN_RESIDENCY',
                        'Admission: pool Nationality outside (EU+5) and foreign residence',
                    ),
                    (
                        'ADMISSION_POOL_NON_RESIDENT_QUOTA',
                        'Admission: pool Non-resident quota holder (as defined in decree)',
                    ),
                    (
                        'ADMISSION_ACCESS_CONDITIONS_URL',
                        'Admission: publication of the training catalogue on the UCLouvain website',
                    ),
                ],
                max_length=70,
                null=True,
            ),
        ),
    ]
