# Generated by Django 3.2.23 on 2023-12-12 16:22
import contextlib
import logging

from django.conf import settings
from django.db import migrations

from admission.contrib.models.online_payment import PaymentStatus
from admission.ddd.admission.formation_generale.domain.model.proposition import PropositionIdentity
from admission.infrastructure.admission.formation_generale.domain.service.reference import ReferenceTranslator
from ddd.logic.comptabilite.commands import CreationClientCommand, PasserEcritureComptableFraisDossierAdmissionCommand
from ddd.logic.comptabilite.domain.validator.exceptions import ClientDejaExistant

logger = logging.getLogger(settings.DEFAULT_LOGGER)


def migrate_online_payment_to_sap_transactions(apps, schema_editor):
    from infrastructure.messages_bus import message_bus_instance

    OnlinePayment = apps.get_model('admission', 'OnlinePayment')
    qs = OnlinePayment.objects.filter(
        status=PaymentStatus.PAID.name
    ).values(
        'amount',
        'admission__candidate__global_id',
        'admission__uuid',
    )
    for online_payment in qs:
        numero_dossier = ReferenceTranslator().get_reference(
            entity_id=PropositionIdentity(uuid=online_payment['admission__uuid'])
        )

        with contextlib.suppress(ClientDejaExistant):
            logger.info(f"Creation client pour matricule: {online_payment['admission__candidate__global_id']}")
            cmd = CreationClientCommand(matricule=online_payment['admission__candidate__global_id'])
            message_bus_instance.invoke(cmd)

        logger.info(f"Passer écriture comptable frais dossier "
                    f"pour matricule: {online_payment['admission__candidate__global_id']}")
        cmd = PasserEcritureComptableFraisDossierAdmissionCommand(
            matricule=online_payment['admission__candidate__global_id'],
            numero_dossier=numero_dossier,
            montant=online_payment['amount'],
        )
        message_bus_instance.invoke(cmd)


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0135_alter_baseadmission_determined_pool'),
        ('base', '0661_sapclient_saptransaction'),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_online_payment_to_sap_transactions,
            reverse_code=migrations.RunPython.noop
        )
    ]
