# Generated by Django 3.2.16 on 2022-12-27 16:05

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from admission.mail_templates import ADMISSION_EMAIL_CONFIRM_SUBMISSION_CONTINUING


class Migration(migrations.Migration):
    dependencies = [
        ('admission', '0137_sic_decision'),
    ]

    operations = [
        MailTemplateMigration(
            ADMISSION_EMAIL_CONFIRM_SUBMISSION_CONTINUING,
            {
                'en': 'In response to your application ({admission_reference} {candidate_last_name} '
                '{candidate_first_name} {training_acronym})',
                'fr-be': "Suite de votre demande d'inscription ({admission_reference} {candidate_last_name} "
                "{candidate_first_name} {training_acronym})",
            },
            {
                'en': '''
    <p>{salutation} {candidate_first_name} {candidate_last_name},</p>

    <p>
        Thank you for submitting your application for admission to the {training_acronym} - {training_title} course. 
        Your application reference number is {admission_reference}.
    </p>

    <p>
        We will get back to you as soon as possible. If you wish to modify your application or have any further 
        questions, please contact the course administrator: {program_managers_emails}.
    </p>

    <p>
        Thank you for your interest in UCLouvain.
    </p>

    <p>
        Your application file can be accessed at the following address: 
        <a href="{recap_link}" target="_blank">{recap_link}</a>.
    </p>

    <p>
        {program_managers_names}
    </p>

                ''',
                'fr-be': '''
    <p>
        {salutation} {candidate_first_name} {candidate_last_name},
    </p>

    <p>
        Nous vous remercions pour votre demande d'admission à la formation {training_acronym} - {training_title}.
        Celle-ci porte le numéro de réference {admission_reference}.
    </p>

    <p>
        Nous reviendrons vers vous dans les meilleurs délais. Si vous souhaitez encore modifier votre dossier
        d'admission ou pour toute question complémentaire, veuillez prendre contact avec le·a gestionnaire de la
        formation : {program_managers_emails}.
    </p>

    <p>
        Veuillez agréer l’expression de nos salutations distinguées.
    </p>

    <p>
        Votre dossier est accessible via l'adresse suivante : 
        <a href="{recap_link}" target="_blank">{recap_link}</a>.
    </p>

    <p>
        {program_managers_names}
    </p>
                ''',
            },
        ),
    ]
