# Generated by Django 3.2.23 on 2024-01-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0139_checklist_send_to_faculty_mail_template_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='refusalreason',
            name='order',
            field=models.FloatField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='refusalreasoncategory',
            name='order',
            field=models.FloatField(default=0, verbose_name='Order'),
        ),
        migrations.AlterModelOptions(
            name='refusalreason',
            options={
                'ordering': ['order'],
                'verbose_name': 'Refusal reason',
                'verbose_name_plural': 'Refusal reasons',
            },
        ),
        migrations.AlterModelOptions(
            name='refusalreasoncategory',
            options={
                'ordering': ['order'],
                'verbose_name': 'Refusal reason category',
                'verbose_name_plural': 'Refusal reason categories',
            },
        ),
    ]
