# Generated by Django 3.2.23 on 2024-01-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0142_alter_admission_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='communication_to_the_candidate',
            field=models.TextField(blank=True, default='', verbose_name='Communication to the candidate'),
        ),
    ]
