# Generated by Django 3.2.23 on 2024-02-02 13:08

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0143_alter_generaleducationadmission_communication_to_the_candidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaleducationadmission',
            name='must_provide_student_visa_d',
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name='The candidate must provide a student visa',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='signed_enrollment_authorization',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name='Signed enrollment authorization',
            ),
        ),
        migrations.AddField(
            model_name='generaleducationadmission',
            name='student_visa_d',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name='Student visa D',
            ),
        ),
    ]
