# Generated by Django 3.2.23 on 2024-01-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0143_alter_generaleducationadmission_communication_to_the_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiontask',
            name='type',
            field=models.CharField(
                choices=[
                    ('ARCHIVE', 'PDF Export'),
                    ('CANVAS', 'Canvas'),
                    ('CONFIRMATION_SUCCESS', 'Confirmation success attestation'),
                    ('GENERAL_RECAP', 'PDF recap for a general education admission'),
                    ('CONTINUING_RECAP', 'PDF recap for a continuing education admission'),
                    ('DOCTORATE_RECAP', 'PDF recap for a doctorate education admission'),
                    ('GENERAL_MERGE', 'Merging of each document field of a general proposition into one PDF'),
                    ('CONTINUING_MERGE', 'Merging of each document field of a continuing proposition into one PDF'),
                    ('DOCTORATE_MERGE', 'Merging of each document field of a doctorate proposition into one PDF'),
                    ('GENERAL_FOLDER', 'Analysis folder for a general education admission'),
                ],
                max_length=20,
            ),
        ),
    ]
