# Generated by Django 3.2.23 on 2024-02-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0667_educationgrouptype_cycle'),
        ('admission', '0147_sic_refusal_mail_template_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionReader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(blank=True, choices=[('FIRST_YEAR', 'First year bachelor')], default='', max_length=25)),
                ('changed', models.DateTimeField(auto_now=True, null=True)),
                ('education_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.educationgroup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.person')),
            ],
            options={
                'verbose_name': 'Role: Admission reader',
                'verbose_name_plural': 'Role: Admission readers',
                'abstract': False,
                'unique_together': {('person', 'education_group', 'cohort')},
            },
        ),
    ]
