# Generated by Django 3.2.23 on 2024-02-12 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0668_registrationcounteryear'),
        ('admission', '0148_admissionreader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionreader',
            name='education_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.educationgroup'),
        ),
    ]
