# Generated by Django 3.2.23 on 2024-02-13 15:56

import admission.contrib.models.form_item
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0149_alter_admissionreader_education_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingList',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        verbose_name='order',
                    ),
                ),
                (
                    'name',
                    admission.contrib.models.form_item.TranslatedJSONField(
                        default=dict,
                        validators=[admission.contrib.models.form_item.is_valid_translated_json_field],
                        verbose_name='Name of the working list',
                    ),
                ),
                (
                    'checklist_filters_mode',
                    models.CharField(
                        blank=True,
                        choices=[('INCLUSION', 'Include'), ('EXCLUSION', 'Exclude')],
                        default='',
                        max_length=16,
                        verbose_name='Checklist filters mode',
                    ),
                ),
                (
                    'checklist_filters',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name='Checklist filters',
                    ),
                ),
                (
                    'admission_statuses',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('EN_BROUILLON', 'In draft form'),
                                ('EN_ATTENTE_DE_SIGNATURE', 'Waiting for signature'),
                                ('FRAIS_DOSSIER_EN_ATTENTE', 'Pending application fee'),
                                ('CONFIRMEE', 'Application confirmed'),
                                ('ANNULEE', 'Cancelled application'),
                                ('A_COMPLETER_POUR_SIC', 'To be completed for the Enrolment Office (SIC)'),
                                ('COMPLETEE_POUR_SIC', 'Completed for SIC'),
                                ('TRAITEMENT_FAC', 'Processing by Fac'),
                                ('A_COMPLETER_POUR_FAC', 'To be completed for Fac'),
                                ('COMPLETEE_POUR_FAC', 'Completed for Fac'),
                                ('RETOUR_DE_FAC', 'Feedback from Fac'),
                                ('ATTENTE_VALIDATION_DIRECTION', 'Awaiting management approval'),
                                ('INSCRIPTION_AUTORISEE', 'Application accepted'),
                                ('INSCRIPTION_REFUSEE', 'Application denied'),
                                ('CLOTUREE', 'Closed'),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name='Admission statuses',
                    ),
                ),
                (
                    'admission_type',
                    models.CharField(
                        blank=True,
                        choices=[('ADMISSION', 'ADMISSION'), ('INSCRIPTION', 'INSCRIPTION')],
                        default='',
                        max_length=16,
                        verbose_name='Admission type',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Working list',
                'verbose_name_plural': 'Working lists',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
