# Generated by Django 3.2.23 on 2024-02-08 17:17

from django.db import migrations


def fix_birth_date_in_submitted_profile(apps, schema_editor):
    BaseAdmission = apps.get_model('admission', 'BaseAdmission')

    for admission in BaseAdmission.objects.all().select_related('candidate').only('submitted_profile', 'candidate'):
        if (
            admission.submitted_profile
            and admission.submitted_profile['identification']
            and admission.candidate.birth_date
        ):
            admission.submitted_profile['identification']['birth_date'] = admission.candidate.birth_date.isoformat()
            admission.save(update_fields=['submitted_profile'])


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0149_alter_admissionreader_education_group'),
    ]

    operations = [
        migrations.RunPython(fix_birth_date_in_submitted_profile, reverse_code=migrations.RunPython.noop),
    ]
