# Generated by Django 3.2.23 on 2024-02-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0154_admissionviewer_remove_duplicates'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='admissionviewer',
            constraint=models.UniqueConstraint(fields=('person', 'admission'), name='admission_viewer_unique'),
        ),
    ]
