# Generated by Django 3.2.23 on 2024-02-20 13:31

from django.db import migrations


def remove_duplicates(apps, schema_editor):
    AdmissionViewer = apps.get_model('admission', 'AdmissionViewer')

    # Delete all the entries (including the duplicates)
    AdmissionViewer.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0155_sic_approval_mail_eu_remove_images'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, reverse_code=migrations.RunPython.noop),
    ]
