# Generated by Django 3.2.24 on 2024-02-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_interne', '0004_alter_parcoursviewer_unique_together'),
        ('admission', '0157_admissionviewer_admission_viewer_unique'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdmissionReader',
        ),
        migrations.CreateModel(
            name='AdmissionReader',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('parcours_interne.parcoursviewer',),
        ),
    ]
