# Generated by Django 3.2.24 on 2024-02-23 12:35
from django.conf import settings
from django.db import migrations, models
from django.db.models import Value, QuerySet

from admission.models.checklist import FREE_ADDITIONAL_APPROVAL_CONDITION_FIELD_BY_LANGUAGE


def initialize_translated_conditions(apps, schema_editor):
    """
    Initialize the translated free approval conditions of the general education admissions based on the single ones.
    """
    FreeAdditionalApprovalCondition = apps.get_model('admission', 'FreeAdditionalApprovalCondition')
    GeneralEducationAdmission = apps.get_model('admission', 'GeneralEducationAdmission')
    free_approval_conditions = []

    admissions = GeneralEducationAdmission.objects.filter(free_additional_approval_conditions__len__gt=0).annotate(
        created_at=Value(''),
        candidate_language=models.F('baseadmission_ptr__candidate__language'),
    )

    for admission in admissions:
        field_name = FREE_ADDITIONAL_APPROVAL_CONDITION_FIELD_BY_LANGUAGE[
            admission.candidate_language or settings.LANGUAGE_CODE
        ]

        for condition in admission.free_additional_approval_conditions:
            free_approval_conditions.append(
                FreeAdditionalApprovalCondition(
                    **{
                        'admission': admission,
                        field_name: condition,
                    }
                )
            )

    FreeAdditionalApprovalCondition.objects.bulk_create(free_approval_conditions, batch_size=1000)


def initialize_single_conditions(apps, schema_editor):
    """
    Initialize the single free approval conditions of the general education admissions based on the translated ones.
    """
    GeneralEducationAdmission = apps.get_model('admission', 'GeneralEducationAdmission')
    FreeAdditionalApprovalCondition = apps.get_model('admission', 'FreeAdditionalApprovalCondition')

    free_conditions: QuerySet[FreeAdditionalApprovalCondition] = (
        FreeAdditionalApprovalCondition.objects.all()
        .select_related('admission')
        .annotate(
            candidate_language=models.F('admission__baseadmission_ptr__candidate__language'),
        )
    )

    admissions = set()

    for condition in free_conditions:
        condition.admission.free_additional_approval_conditions.append(
            getattr(
                condition,
                FREE_ADDITIONAL_APPROVAL_CONDITION_FIELD_BY_LANGUAGE[
                    condition.candidate_language or settings.LANGUAGE_CODE
                ],
            )
        )
        admissions.add(condition.admission)

    GeneralEducationAdmission.objects.bulk_update(admissions, ['free_additional_approval_conditions'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0159_freeadditionalapprovalcondition'),
    ]

    operations = [
        migrations.RunPython(
            code=initialize_translated_conditions,
            reverse_code=initialize_single_conditions,
        )
    ]
