# Generated by Django 3.2.24 on 2024-02-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0160_freeadditionalapprovalcondition_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaleducationadmission',
            name='free_additional_approval_conditions',
        ),
    ]
