# Generated by Django 3.2.23 on 2024-02-13 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0162_workinglist'),
    ]

    operations = [
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
