# Generated by Django 3.2.25 on 2024-03-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0163_sic_refusal_mail_director_gender'),
        ('admission', '0164_default_workinglists'),
    ]

    operations = [
    ]
