# Generated by Django 3.2.23 on 2024-03-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0164_default_workinglists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseAdmissionProxy',
        ),
    ]
