# Generated by Django 3.2.25 on 2024-03-21 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0164_default_workinglists'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCInjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('OK', 'OK'), ('ERROR', 'ERROR')], default='', max_length=5)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('epc_responses', models.JSONField(blank=True, default=list)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epc_injection', to='admission.baseadmission')),
            ],
        ),
    ]
