# Generated by Django 3.2.25 on 2024-03-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0166_epcinjection'),
        ('admission', '0167_sic_refusal_mail_signature_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseadmission',
            name='determined_pool',
            field=models.CharField(
                blank=True,
                choices=[
                    ('GENERAL_EDUCATION_ENROLLMENT', 'General education enrolment'),
                    ('DOCTORATE_EDUCATION_ENROLLMENT', 'Doctorate education enrolment'),
                    ('CONTINUING_EDUCATION_ENROLLMENT', 'Continuing education enrolment'),
                    ('ADMISSION_POOL_EXTERNAL_ENROLLMENT_CHANGE', 'Admission: pool External enrollment change'),
                    ('ADMISSION_POOL_EXTERNAL_REORIENTATION', 'Admission: pool External reorientation'),
                    ('ADMISSION_POOL_VIP', 'Admission: pool VIP'),
                    ('ADMISSION_POOL_HUE_UCL_PATHWAY_CHANGE', 'Admission: pool HUE UCL pathway change'),
                    ('ADMISSION_POOL_INSTITUT_CHANGE', 'Admission: pool Institute change'),
                    ('ADMISSION_POOL_UE5_BELGIAN', 'Admission: pool EU+5 nationality and Belgian access diploma'),
                    (
                        'ADMISSION_POOL_UE5_NON_BELGIAN',
                        'Admission: pool EU+5 nationality and non-Belgian access diploma',
                    ),
                    (
                        'ADMISSION_POOL_HUE5_BELGIUM_RESIDENCY',
                        'Admission: pool Nationality outside (EU+5) and residence in Belgium',
                    ),
                    (
                        'ADMISSION_POOL_HUE5_FOREIGN_RESIDENCY',
                        'Admission: pool Nationality outside (EU+5) and foreign residence',
                    ),
                    (
                        'ADMISSION_POOL_NON_RESIDENT_QUOTA',
                        'Admission: pool Non-resident quota holder (as defined in decree)',
                    ),
                ],
                max_length=70,
                null=True,
            ),
        ),
    ]
