# Generated by Django 3.2.25 on 2024-03-25 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0168_alter_baseadmission_determined_pool'),
        ('admission', '0166_epcinjection'),
    ]

    operations = [
    ]
