# Generated by Django 3.2.25 on 2024-03-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0169_auto_20240325_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresecretary',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cddconfigurator',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centralmanager',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctoratereader',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jurysecretary',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programmanager',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='promoter',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sceb',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sicmanagement',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
