# Generated by Django 3.2.23 on 2024-01-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0170_auto_20240327_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='assessment_test_presented',
            field=models.BooleanField(null=True, verbose_name='Assessment test presented'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='assessment_test_succeeded',
            field=models.BooleanField(null=True, verbose_name='Assessment test succeeded'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='cep',
            field=models.BooleanField(null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='certificate_provided',
            field=models.BooleanField(null=True, verbose_name='Certificate provided'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='edition',
            field=models.CharField(
                blank=True,
                choices=[('UN', '1'), ('DEUX', '2'), ('TROIS', '3'), ('QUATRE', '4'), ('CINQ', '5'), ('SIX', '6')],
                default='',
                max_length=30,
                verbose_name='Edition',
            ),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='experience_knowledge_valorisation',
            field=models.BooleanField(null=True, verbose_name='Experience knowledge valorisation'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='in_payement_order',
            field=models.BooleanField(null=True, verbose_name='In payement order'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='interested_mark',
            field=models.BooleanField(null=True, verbose_name='Interested mark'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='payed_by_training_cheque',
            field=models.BooleanField(null=True, verbose_name='Payed by training cheque'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='payement_spread',
            field=models.BooleanField(null=True, verbose_name='Payement spread'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='reduced_rights',
            field=models.BooleanField(null=True, verbose_name='Reduced rights'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='tff_label',
            field=models.TextField(blank=True, default='', verbose_name='TFF label'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='training_spread',
            field=models.BooleanField(null=True, verbose_name='Training spread'),
        ),
    ]
