# Generated by Django 3.2.25 on 2024-04-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0171_continuing_education_checklist_student_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continuingeducationadmission',
            old_name='payed_by_training_cheque',
            new_name='pay_by_training_cheque',
        ),
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='pay_by_training_cheque',
            field=models.BooleanField(null=True, verbose_name='Pay by training cheque'),
        ),
    ]
