# Generated by Django 3.2.25 on 2024-04-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0171_initial_categorized_free_documents'),
        ('admission', '0172_continuing_education_rename_pay_by_training_cheque'),
    ]

    operations = [
    ]
