# Generated by Django 3.2.23 on 2024-01-16 17:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0173_merge_20240408_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='ways_to_find_out_about_the_course',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('SITE_WEB_UCLOUVAIN', 'UCLouvain website'),
                        ('SITE_FORMATION_CONTINUE', 'Continuing education website'),
                        ('PRESSE', 'In the press'),
                        ('FACEBOOK', 'Facebook'),
                        ('LINKEDIN', 'Linkedin'),
                        ('COURRIER_PERSONNALISE', 'Personalised mail'),
                        ('EMAILING', 'Email'),
                        ('BOUCHE_A_OREILLE', 'Word of mouth'),
                        ('AMIS', 'Friends'),
                        ('ANCIENS_ETUDIANTS', 'Former students'),
                        ('MOOCS', 'MOOCs'),
                        ('AUTRE', 'Other'),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name='How did the candidate find out about this course?',
            ),
        ),
    ]
