# Generated by Django 3.2.25 on 2024-04-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0173_merge_20240408_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epcinjection',
            name='status',
            field=models.CharField(blank=True, choices=[('OK', 'OK'), ('ERROR', 'ERROR'), ('PENDING', 'PENDING')], default='', max_length=7),
        ),
    ]
