# Generated by Django 3.2.25 on 2024-04-03 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0674_alter_academiccalendar_reference'),
        ('admission', '0174_alter_epcinjection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='status',
            field=models.CharField(choices=[('EN_BROUILLON', 'In draft form'), ('CONFIRMEE', 'Application confirmed'),
                                            ('EN_ATTENTE', 'On hold'), ('INSCRIPTION_REFUSEE', 'Application denied'),
                                            ('ANNULEE', 'Cancelled application'),
                                            ('INSCRIPTION_AUTORISEE', 'Application accepted'), ('CLOTUREE', 'Closed'),
                                            ('ANNULEE_PAR_GESTIONNAIRE', 'Cancelled application by a manager')],
                                   default='EN_BROUILLON', max_length=30),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='approval_condition_by_faculty',
            field=models.TextField(blank=True, default='', verbose_name='Approval condition by faculty'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', verbose_name='Cancel reason'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='last_email_sent_at',
            field=models.DateTimeField(null=True, verbose_name='Last email sent the'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='last_email_sent_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='base.person',
                verbose_name='Last email sent by',
            ),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='on_hold_reason',
            field=models.TextField(
                blank=True,
                choices=[
                    ('COMPLET', 'The programme is already full'),
                    ('VERIFICATION', 'Your application is currently being reviewed by the course exam board'),
                    ('AUTRE', 'Other'),
                ],
                verbose_name='On hold reason',
            ),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='on_hold_reason_other',
            field=models.TextField(blank=True, default='', verbose_name='On hold other reason'),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='refusal_reason',
            field=models.TextField(
                blank=True,
                choices=[
                    ('PARCOURS_NON_ADAPTE', 'Your background is not suited to this course'),
                    ('CONDITIONS', 'You do not meet the admission requirements'),
                    ('FULL', 'The programme is already full'),
                    ('EXPERIENCE', 'Your experience and reasons for undertaking this programme are insufficient'),
                    ('AUTRE', 'Other'),
                ],
                verbose_name='Refusal reason',
            ),
        ),
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='refusal_reason_other',
            field=models.TextField(blank=True, default='', verbose_name='Refusal reason other'),
        ),
    ]
