# Generated by Django 3.2.25 on 2024-04-26 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0174_alter_continuingeducationadmission_ways_to_find_out_about_the_course'),
        ('admission', '0174_alter_epcinjection_status'),
    ]

    operations = [
    ]
