# Generated by Django 3.2.25 on 2024-03-25 11:16

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from admission.mail_templates.checklist.continuing_education import (
    ADMISSION_EMAIL_DECISION_FAC_APPROVAL_WITH_CONDITION,
    ADMISSION_EMAIL_DECISION_FAC_APPROVAL_WITHOUT_CONDITION,
    ADMISSION_EMAIL_DECISION_DENY,
    ADMISSION_EMAIL_DECISION_ON_HOLD,
    ADMISSION_EMAIL_DECISION_CANCEL,
    ADMISSION_EMAIL_DECISION_VALIDATION,
    ADMISSION_EMAIL_DECISION_IUFC_COMMENT_FOR_FAC,
)


MAIL_HEADER_EN = '''<p>Dear {candidate_first_name} {candidate_last_name},</p>
'''

MAIL_FOOTER_EN = '''<p>Thank you for your interest in UCLouvain.
If you have any questions, please contact your course administrator(s): {managers_emails}</p>

<p>Your application file can be accessed at the following address: {application_link}</p>

<p>{sender_name}</p>
'''

MAIL_HEADER_FR = '''<p>{greetings} {candidate_first_name} {candidate_last_name},</p>
'''

MAIL_FOOTER_FR = '''<p>Veuillez agréer l’expression de nos salutations distinguées.</p>

<p>Pour toute question, veuillez contacter le(s) gestionnaire(s) de votre formation : {managers_emails}.</p>

<p>Votre dossier est accessible via l'adresse suivante : {application_link}</p>

<p>{sender_name}</p>
'''


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0175_continuing_education_decision_fields'),
    ]

    operations = [
        MailTemplateMigration(
            ADMISSION_EMAIL_DECISION_FAC_APPROVAL_WITH_CONDITION,
            {
                'en': 'UCLouvain Continuing Education: application accepted ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})',
                'fr-be': "Formation Continue UCLouvain - Demande d'admission acceptée ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})",
            },
            {
                'en': MAIL_HEADER_EN
                + '''<p>We are pleased to inform you that your application for admission to the
                    {training_acronym} - {training_title} programme has been accepted at the academic level on the 
                    following condition(s): {conditions}.</p>
                    <p>Your application still needs to be analysed/validated at the administrative level.</p>
                '''
                + MAIL_FOOTER_EN,
                'fr-be': MAIL_HEADER_FR
                + '''<p>En réponse à votre demande d’admission au programme 
                    {training_acronym} - {training_title}, nous avons le plaisir de vous informer que celle-ci a été
                    acceptée au niveau académique avec la (les) condition(s) suivante(s) : {conditions}.</p>
                    <p>Votre dossier doit encore être analysé/validé au niveau administratif.</p>
                '''
                + MAIL_FOOTER_FR,
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_DECISION_FAC_APPROVAL_WITHOUT_CONDITION,
            {
                'en': 'UCLouvain Continuing Education: application accepted ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})',
                'fr-be': "Formation Continue UCLouvain - Demande d'admission acceptée ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})",
            },
            {
                'en': MAIL_HEADER_EN
                + '''<p>We are pleased to inform you that your application for admission to the
                    {training_acronym} - {training_title} programme has been accepted at the academic level
                    unconditionally.</p>
                    <p>Your application still needs to be analysed/validated at the administrative level.</p>
                '''
                + MAIL_FOOTER_EN,
                'fr-be': MAIL_HEADER_FR
                + '''<p>En réponse à votre demande d’admission au programme 
                    {training_acronym} - {training_title}, nous avons le plaisir de vous informer que celle-ci a été
                    acceptée au niveau académique sans condition.</p>
                    <p>Votre dossier doit encore être analysé/validé au niveau administratif.</p>
                '''
                + MAIL_FOOTER_FR,
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_DECISION_DENY,
            {
                'en': 'UCLouvain Continuing Education: application not accepted ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})',
                'fr-be': "Formation Continue UCLouvain - Demande d'admission refusée ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})",
            },
            {
                'en': MAIL_HEADER_EN
                + '''<p>We regret to inform you that we are unable to accept your application
                    for admission to the {training_acronym} - {training_title} course for the following reason(s): 
                    {reasons}</p>
                '''
                + MAIL_FOOTER_EN,
                'fr-be': MAIL_HEADER_FR
                + '''<p>En réponse à votre demande d’admission pour la formation 
                    {training_acronym} - {training_title}, nous avons le regret de vous informer que nous ne pouvons pas 
                    donner une suite favorable pour la (les) raison(s) suivante(s) : {reasons}</p>
                '''
                + MAIL_FOOTER_FR,
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_DECISION_ON_HOLD,
            {
                'en': 'UCLouvain Continuing Education: application on hold ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})',
                'fr-be': "Formation Continue UCLouvain - Demande d'admission mise en attente ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})",
            },
            {
                'en': MAIL_HEADER_EN
                + '''<p>Your application for admission to the {training_acronym} - {training_title} 
                    course has been placed on hold for the following reason(s): {reasons}.</p>
                '''
                + MAIL_FOOTER_EN,
                'fr-be': MAIL_HEADER_FR
                + '''<p>En réponse à votre demande d’admission  pour la formation 
                    {training_acronym} - {training_title}, nous vous informons que celle-ci est mise en attente pour 
                    la (les) raison(s) suivante(s) : {reasons}.</p>
                '''
                + MAIL_FOOTER_FR,
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_DECISION_CANCEL,
            {
                'en': 'UCLouvain Continuing Education: your application has been cancelled ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})',
                'fr-be': "Formation Continue UCLouvain - Votre demande d'admission a été annulée ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})",
            },
            {
                'en': MAIL_HEADER_EN
                + '''<p>Your application for the course {training_acronym} - {training_title} is 
                    now cancelled.</p>
                '''
                + MAIL_FOOTER_EN,
                'fr-be': MAIL_HEADER_FR
                + '''<p>Votre demande d'inscription pour la formation {training_acronym} 
                    - {training_title} est maintenant en état 'Annulé'.</p>
                '''
                + MAIL_FOOTER_FR,
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_DECISION_VALIDATION,
            {
                'en': 'UCLouvain Continuing Education: application validated ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})',
                'fr-be': "Formation Continue UCLouvain - Demande d'admission validée ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})",
            },
            {
                'en': MAIL_HEADER_EN
                + '''<p>We are pleased to inform you that your application for admission to the
                    {training_acronym} - {training_title} programme has been accepted.</p>
                '''
                + MAIL_FOOTER_EN,
                'fr-be': MAIL_HEADER_FR
                + '''En réponse à votre demande d’admission au programme 
                    {training_acronym} - {training_title}, nous avons le plaisir de vous informer que celle-ci a été validée.</p>
                '''
                + MAIL_FOOTER_FR,
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_DECISION_IUFC_COMMENT_FOR_FAC,
            {
                'en': '',
                'fr-be': "Formation Continue UCLouvain - Compléter la demande ({application_reference} {candidate_last_name} {candidate_first_name} {training_acronym})",
            },
            {
                'en': '',
                'fr-be': '''<p>Bonjour,</p>
                    <p>Pouvez-vous demander au candidat les informations suivantes :</p>
                    <p>{comment}</p>
                    <p>La demande est accessible via l'adresse suivante {application_link}</p>
                    <p>{sender_name}</p>
                ''',
            },
        ),
    ]
