# Generated by Django 3.2.25 on 2024-04-24 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0177_continuing_checklist_mail_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinglist',
            name='admission_statuses',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('EN_BROUILLON', 'In draft form'),
                        ('EN_ATTENTE_DE_SIGNATURE', 'Waiting for signature'),
                        ('FRAIS_DOSSIER_EN_ATTENTE', 'Pending application fee'),
                        ('CONFIRMEE', 'Application confirmed'),
                        ('EN_ATTENTE', 'On hold'),
                        ('ANNULEE', 'Cancelled application'),
                        ('ANNULEE_PAR_GESTIONNAIRE', 'Cancelled application by a manager'),
                        ('A_COMPLETER_POUR_SIC', 'To be completed for the Enrolment Office (SIC)'),
                        ('COMPLETEE_POUR_SIC', 'Completed for SIC'),
                        ('TRAITEMENT_FAC', 'Processing by Fac'),
                        ('A_COMPLETER_POUR_FAC', 'To be completed for Fac'),
                        ('COMPLETEE_POUR_FAC', 'Completed for Fac'),
                        ('RETOUR_DE_FAC', 'Feedback from Fac'),
                        ('ATTENTE_VALIDATION_DIRECTION', 'Awaiting management approval'),
                        ('INSCRIPTION_AUTORISEE', 'Application accepted'),
                        ('INSCRIPTION_REFUSEE', 'Application denied'),
                        ('CLOTUREE', 'Closed'),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name='Admission statuses',
            ),
        ),
    ]
