# Generated by Django 3.2.25 on 2024-05-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0178_update_working_list_admission_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaleducationadmission',
            name='foreign_access_title_equivalency_restriction_about',
            field=models.TextField(blank=True, null=True, verbose_name='Information about the restriction'),
        ),
    ]
