# Generated by Django 3.2.25 on 2024-05-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0179_continuing_documents_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissiontask',
            name='type',
            field=models.CharField(
                choices=[
                    ('ARCHIVE', 'PDF Export'),
                    ('CANVAS', 'Canvas'),
                    ('CONFIRMATION_SUCCESS', 'Confirmation success attestation'),
                    ('GENERAL_RECAP', 'PDF recap for a general education admission'),
                    ('CONTINUING_RECAP', 'PDF recap for a continuing education admission'),
                    ('DOCTORATE_RECAP', 'PDF recap for a doctorate education admission'),
                    ('GENERAL_MERGE', 'Merging of each document field of a general proposition into one PDF'),
                    ('CONTINUING_MERGE', 'Merging of each document field of a continuing proposition into one PDF'),
                    ('DOCTORATE_MERGE', 'Merging of each document field of a doctorate proposition into one PDF'),
                    ('GENERAL_FOLDER', 'Analysis folder for a general education admission'),
                    ('CONTINUING_FOLDER', 'Analysis folder for a continuing education admission'),
                    ('DOCTORATE_FOLDER', 'Analysis folder for a doctorate education admission'),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('EN_BROUILLON', 'In draft form'),
                    ('CONFIRMEE', 'Application confirmed'),
                    ('EN_ATTENTE', 'On hold'),
                    ('INSCRIPTION_REFUSEE', 'Application denied'),
                    ('ANNULEE', 'Cancelled application'),
                    ('A_COMPLETER_POUR_FAC', 'To be completed for Fac'),
                    ('COMPLETEE_POUR_FAC', 'Completed for Fac'),
                    ('INSCRIPTION_AUTORISEE', 'Application accepted'),
                    ('CLOTUREE', 'Closed'),
                    ('ANNULEE_PAR_GESTIONNAIRE', 'Cancelled application by a manager'),
                ],
                default='EN_BROUILLON',
                max_length=30,
            ),
        ),
    ]
