# Generated by Django 3.2.25 on 2024-05-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0179_alter_email_confirm_enrolment_submission'),
        ('admission', '0179_alter_generaleducationadmission_refusal_type'),
        ('admission', '0179_generaleducationadmission_foreign_access_title_equivalency_restriction_about'),
    ]

    operations = [
    ]
