# Generated by Django 3.2.25 on 2024-05-21 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0683_personmergeproposal_validation'),
        ('admission', '0179_alter_email_confirm_enrolment_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseadmission',
            name='valuated_secondary_studies_person',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='base.person',
                verbose_name='The person whose the secondary studies have been valuated by this admission',
            ),
        ),
    ]
