# Generated by Django 3.2.25 on 2024-05-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0183_update_continuing_status_and_admission_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorizedfreedocument',
            name='checklist_tab',
            field=models.CharField(
                blank=True,
                choices=[
                    ('donnees_personnelles', 'Personal data'),
                    ('assimilation', 'Belgian student status'),
                    ('frais_dossier', 'Application fee'),
                    ('parcours_anterieur', 'Previous experience'),
                    ('experiences_parcours_anterieur', 'Previous experiences'),
                    ('financabilite', 'Financeability'),
                    ('choix_formation', 'Course choice'),
                    ('specificites_formation', 'Training specificities'),
                    ('decision_facultaire', 'Decision of the faculty'),
                    ('decision_sic', 'Decision of SIC'),
                ],
                default='',
                max_length=255,
            ),
        ),
    ]
