# Generated by Django 3.2.25 on 2024-06-18 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0187_initial_categorized_free_documents_for_iufc'),
        ('admission', '0188_financability_dispensation'),
    ]

    operations = [
    ]
