# Generated by Django 3.2.25 on 2024-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0090_alter_inscriptionprogrammeannuel_statut'),
        ('admission', '0189_merge_20240618_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseadmission',
            name='internal_access_titles',
            field=models.ManyToManyField(
                blank=True,
                related_name='_admission_baseadmission_internal_access_titles_+',
                to='epc.InscriptionProgrammeCycle',
                verbose_name='The internal experiences chosen as access titles of this admission.',
            ),
        ),
    ]
