# Generated by Django 3.2.25 on 2024-06-19 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0192_fix_missing_country_of_citizenship'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuingeducationadmission',
            name='other_way_to_find_out_about_the_course',
            field=models.TextField(
                blank=True,
                default='',
                max_length=1000,
                verbose_name='How else did the candidate hear about this course?',
            ),
        ),
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='ways_to_find_out_about_the_course',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('SITE_WEB_UCLOUVAIN', 'UCLouvain website'),
                        ('SITE_FORMATION_CONTINUE', 'UCLouvain continuing education website'),
                        ('PRESSE', 'In the press'),
                        ('FACEBOOK', 'Facebook'),
                        ('LINKEDIN', 'Linkedin'),
                        ('COURRIER_PERSONNALISE', 'Personalised mail'),
                        ('EMAILING', 'Email'),
                        ('BOUCHE_A_OREILLE', 'Word of mouth (family, friends, colleagues, ...)'),
                        ('ANCIENS_ETUDIANTS', 'By someone who has already taken this course in a previous edition'),
                        ('MOOCS', 'MOOCs'),
                        ('AUTRE', 'Other'),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name='How did the candidate hear about this course?',
            ),
        ),
    ]
