# Generated by Django 3.2.25 on 2024-07-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0195_financabilite_use_base_enum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinglist',
            name='quarantine',
            field=models.BooleanField(null=True),
        ),
    ]
