# Generated by Django 3.2.25 on 2024-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0195_financabilite_use_base_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='epcinjection',
            name='type',
            field=models.CharField(blank=True, choices=[('DEMANDE', 'Demande'), ('SIGNALETIQUE', 'Signalétique')], default='', max_length=12),
        ),
    ]
