# Generated by Django 3.2.25 on 2024-07-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0196_unique_candidate_data_migration'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('person',), name='unique_candidate'),
        ),
    ]
