# Generated by Django 3.2.25 on 2024-07-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0196_epcinjection_type'),
        ('admission', '0197_financabilite_blank'),
    ]

    operations = [
    ]
