# Generated by Django 3.2.25 on 2024-07-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0197_unique_candidate_constraint'),
        ('admission', '0198_merge_0196_epcinjection_type_0197_financabilite_blank'),
    ]

    operations = [
    ]
