# Generated by Django 3.2.25 on 2024-06-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0199_merge_20240711_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('EN_BROUILLON', 'In draft form'),
                    ('EN_ATTENTE_DE_SIGNATURE', 'Waiting for signature'),
                    ('CONFIRMEE', 'Application confirmed'),
                    ('ANNULEE', 'Cancelled application'),
                    ('TRAITEMENT_FAC', 'Processing by Fac'),
                    ('A_COMPLETER_POUR_FAC', 'To be completed for Fac'),
                    ('COMPLETEE_POUR_FAC', 'Completed for Fac'),
                    ('RETOUR_DE_FAC', 'Feedback from Fac'),
                    ('A_COMPLETER_POUR_SIC', 'To be completed for the Enrolment Office (SIC)'),
                    ('COMPLETEE_POUR_SIC', 'Completed for SIC'),
                    ('ATTENTE_VALIDATION_DIRECTION', 'Awaiting management approval'),
                    ('CLOTUREE', 'Closed'),
                    ('INSCRIPTION_AUTORISEE', 'Application accepted'),
                    ('INSCRIPTION_REFUSEE', 'Application denied'),
                ],
                default='EN_BROUILLON',
                max_length=30,
            ),
        ),
    ]
