# Generated by Django 3.2.25 on 2024-07-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0203_auto_20240712_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaleducationadmission',
            name='financability_rule_established_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Financability rule established on'),
        ),
    ]
