# Generated by Django 3.2.25 on 2024-07-17 09:39

from django.db import migrations


def create_academic_calendar(apps, schema_editor):
    from admission.calendar.admission_digit_ticket_submission import AdmissionDigitTicketSubmissionCalendar
    from django.utils import timezone

    AcademicYear = apps.get_model('base', 'AcademicYear')
    current_academic_year = AcademicYear.objects.filter(
        start_date__lte=timezone.now(), end_date__gte=timezone.now()
    ).last()
    if current_academic_year is not None:
        AdmissionDigitTicketSubmissionCalendar.ensure_consistency_until_n_plus_6()


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0203_auto_20240712_1536'),
    ]

    operations = [
        migrations.RunPython(create_academic_calendar, reverse_code=migrations.RunPython.noop),
    ]
