# Generated by Django 3.2.25 on 2024-07-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0204_alter_doctorateadmission_thesis_language'),
        ('admission', '0204_auto_20240717_0939'),
    ]

    operations = [
    ]
