# Generated by Django 3.2.25 on 2024-07-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0205_merge_20240717_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorateadmission',
            name='financing_comment',
            field=models.TextField(blank=True, default='', verbose_name='Financing comment'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='is_fnrs_fria_fresh_csc_linked',
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name='Is your admission request linked with a FNRS, FRIA, FRESH or CSC application?',
            ),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='phd_alread_started',
            field=models.BooleanField(blank=True, null=True, verbose_name='Has your PhD project already started?'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='phd_alread_started_institute',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Institution'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='work_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Work start date'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='cotutelle_other_institution_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other institution address'),
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='cotutelle_other_institution_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Other institution name'),
        ),
    ]
