# Generated by Django 3.2.25 on 2024-07-10 11:07

import django.contrib.postgres.fields
from django.db import migrations, models

from admission.ddd.admission.formation_continue.domain.model.enums import ChoixStatutPropositionContinue


def remove_cancelled_by_manager_continuing_status(apps, schema_editor):
    """Update the 'ANNULEE_PAR_GESTIONNAIRE' status to 'ANNULEE' for the continuing education admissions."""
    ContinuingEducationAdmission = apps.get_model('admission', 'ContinuingEducationAdmission')
    ContinuingEducationAdmission.objects.filter(status='ANNULEE_PAR_GESTIONNAIRE').update(
        status=ChoixStatutPropositionContinue.ANNULEE.name,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0205_merge_20240717_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuingeducationadmission',
            name='status',
            field=models.CharField(
                choices=[
                    ('EN_BROUILLON', 'In draft form'),
                    ('CONFIRMEE', 'Application confirmed'),
                    ('EN_ATTENTE', 'On hold'),
                    ('INSCRIPTION_REFUSEE', 'Application denied'),
                    ('ANNULEE', 'Cancelled application'),
                    ('A_COMPLETER_POUR_FAC', 'To be completed for Fac'),
                    ('COMPLETEE_POUR_FAC', 'Completed for Fac'),
                    ('INSCRIPTION_AUTORISEE', 'Application accepted'),
                    ('CLOTUREE', 'Closed'),
                ],
                default='EN_BROUILLON',
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name='workinglist',
            name='admission_statuses',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ('EN_BROUILLON', 'In draft form'),
                        ('EN_ATTENTE_DE_SIGNATURE', 'Waiting for signature'),
                        ('FRAIS_DOSSIER_EN_ATTENTE', 'Pending application fee'),
                        ('CONFIRMEE', 'Application confirmed'),
                        ('EN_ATTENTE', 'On hold'),
                        ('ANNULEE', 'Cancelled application'),
                        ('A_COMPLETER_POUR_SIC', 'To be completed for the Enrolment Office (SIC)'),
                        ('COMPLETEE_POUR_SIC', 'Completed for SIC'),
                        ('TRAITEMENT_FAC', 'Processing by Fac'),
                        ('A_COMPLETER_POUR_FAC', 'To be completed for Fac'),
                        ('COMPLETEE_POUR_FAC', 'Completed for Fac'),
                        ('RETOUR_DE_FAC', 'Feedback from Fac'),
                        ('ATTENTE_VALIDATION_DIRECTION', 'Awaiting management approval'),
                        ('INSCRIPTION_AUTORISEE', 'Application accepted'),
                        ('INSCRIPTION_REFUSEE', 'Application denied'),
                        ('CLOTUREE', 'Closed'),
                    ],
                    max_length=30,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name='Admission statuses',
            ),
        ),
        migrations.RunPython(
            code=remove_cancelled_by_manager_continuing_status,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
