# Generated by Django 3.2.25 on 2024-06-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0206_remove_cancelled_by_manager_continuing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorizedfreedocument',
            name='admission_context',
            field=models.CharField(
                choices=[
                    ('general-education', 'General education'),
                    ('continuing-education', 'Continuing education'),
                    ('doctorate', 'Doctorate education'),
                ],
                default='',
                max_length=20,
                verbose_name='Admission context',
            ),
        ),
        migrations.AlterField(
            model_name='categorizedfreedocument',
            name='checklist_tab',
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        'General education',
                        (
                            ('donnees_personnelles', 'Personal data'),
                            ('assimilation', 'Belgian student status'),
                            ('frais_dossier', 'Application fee'),
                            ('parcours_anterieur', 'Previous experience'),
                            ('experiences_parcours_anterieur', 'Previous experiences'),
                            ('financabilite', 'Financeability'),
                            ('choix_formation', 'Course choice'),
                            ('specificites_formation', 'Training specificities'),
                            ('decision_facultaire', 'Decision of the faculty'),
                            ('decision_sic', 'Decision of SIC'),
                        ),
                    ),
                    (
                        'Continuing education',
                        (
                            ('fiche_etudiant', 'Student report'),
                            ('decision', 'Decision'),
                        ),
                    ),
                    (
                        'Doctorate education',
                        (
                            ('donnees_personnelles', 'Personal data'),
                            ('assimilation', 'Belgian student status'),
                            ('parcours_anterieur', 'Previous experience'),
                            ('experiences_parcours_anterieur', 'Previous experiences'),
                            ('financabilite', 'Financeability'),
                            ('choix_formation', 'Course choice'),
                            ('projet_recherche', 'Research project'),
                            ('decision_facultaire', 'Decision of the faculty'),
                            ('decision_sic', 'Decision of SIC'),
                        ),
                    ),
                ],
                default='',
                max_length=255,
                verbose_name='Checklist tab',
            ),
        ),
    ]
