# Generated by Django 3.2.25 on 2024-06-27 17:54

from django.db import migrations
from django.db.models import Case, When, Value

from admission.constants import CONTEXT_GENERAL, CONTEXT_CONTINUING
from admission.ddd.admission.formation_continue.domain.model.enums import OngletsChecklist as OngletsChecklistContinue
from admission.ddd.admission.formation_generale.domain.model.enums import OngletsChecklist as OngletsChecklistGenerale


def initialize_categorized_free_documents_admission_context(apps, schema_editor):
    """Initialize the categorized free documents admission context."""

    CategorizedFreeDocument = apps.get_model('admission', 'CategorizedFreeDocument')

    CategorizedFreeDocument.objects.update(
        admission_context=Case(
            When(
                checklist_tab__in=OngletsChecklistGenerale.get_names(),
                then=Value(CONTEXT_GENERAL),
            ),
            When(
                checklist_tab__in=OngletsChecklistContinue.get_names(),
                then=Value(CONTEXT_CONTINUING),
            ),
            default=Value(CONTEXT_GENERAL),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0207_categorized_documents_by_context'),
    ]

    operations = [
        migrations.RunPython(
            code=initialize_categorized_free_documents_admission_context,
            reverse_code=migrations.RunPython.noop,
        )
    ]
