# Generated by Django 3.2.25 on 2024-07-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0210_generaleducationadmission_financability_rule_established_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='epcinjection',
            name='last_attempt_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='epcinjection',
            name='last_response_date',
            field=models.DateTimeField(null=True),
        ),
    ]
