# Generated by Django 3.2.25 on 2024-08-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0212_alter_epcinjection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epcinjection',
            name='status',
            field=models.CharField(blank=True, choices=[('OK', 'Injecté'), ('ERROR', 'Erreur'), ('NO_SENT', 'Pas encore envoyé dans EPC'), ('PENDING', "En attente du retour d'EPC")], default='', max_length=7),
        ),
    ]
