# Generated by Django 3.2.25 on 2024-08-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0213_alter_epcinjection_status'),
        ('admission', '0214_change_cdd_submission_mail_template'),
    ]

    operations = [
    ]
