# Generated by Django 3.2.25 on 2024-08-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0215_merge_20240809_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epcinjection',
            name='status',
            field=models.CharField(blank=True, choices=[('OK', 'Injecté'), ('ERROR', 'Erreur'), ('NO_SENT', 'Pas encore envoyé dans EPC'), ('PENDING', "En attente du retour d'EPC"), ('OSIS_ERROR', 'Erreur OSIS')], default='', max_length=10),
        ),
    ]
