# Generated by Django 4.2.16 on 2024-09-04 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference", "0018_country_active"),
        ("epc", "0095_alter_inscriptionprogrammeannuel_admission_uuid"),
        ("base", "0700_alter_examenrollment_date_enrollment_and_more"),
        ("admission", "0216_alter_epcinjection_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionformitem",
            name="academic_years",
            field=models.ManyToManyField(
                related_name="+",
                through="admission.AdmissionFormItemInstantiation",
                to="base.academicyear",
            ),
        ),
        migrations.AlterField(
            model_name="baseadmission",
            name="candidate",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="base.person",
                verbose_name="Candidate",
            ),
        ),
        migrations.AlterField(
            model_name="baseadmission",
            name="internal_access_titles",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="epc.inscriptionprogrammecycle",
                verbose_name="The internal experiences chosen as access titles of this admission.",
            ),
        ),
        migrations.AlterField(
            model_name="diplomaticpost",
            name="countries",
            field=models.ManyToManyField(
                related_name="+", to="reference.country", verbose_name="Countries"
            ),
        ),
        migrations.AlterField(
            model_name="generaleducationadmission",
            name="additional_approval_conditions",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="admission.additionalapprovalcondition",
                verbose_name="Additional approval conditions",
            ),
        ),
        migrations.AlterField(
            model_name="generaleducationadmission",
            name="refusal_reasons",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                to="admission.refusalreason",
                verbose_name="Refusal reasons",
            ),
        ),
    ]
