# Generated by Django 3.2.25 on 2024-08-28 10:51

from django.db import migrations

def copier_gestionnaires_iufc(apps, schema_editor):
    ContinuingEducationTrainingManager = apps.get_model('continuing_education', 'ContinuingEducationTrainingManager')
    ProgramManager = apps.get_model('admission', 'ProgramManager')
    gestionnaires_iufc = ContinuingEducationTrainingManager.objects.all().select_related(
        'training__education_group',
        'person',
    )
    print(f"{gestionnaires_iufc.count()} gestionnaires IUFC a copier")
    gestionnaires_admission_programme = []
    for gestionnaire in gestionnaires_iufc:
        gestionnaires_admission_programme.append(
            ProgramManager(
                education_group=gestionnaire.training.education_group,
                person=gestionnaire.person,
            )
        )
    ProgramManager.objects.bulk_create(gestionnaires_admission_programme, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0217_alter_accounting_sport_affiliation'),
    ]

    operations = [
        migrations.RunPython(copier_gestionnaires_iufc, reverse_code=migrations.RunPython.noop)
    ]
