# Generated by Django 3.2.25 on 2024-08-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0219_change_cdd_submission_mail_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='pre_admission_submission_date',
        ),
    ]
