# Generated by Django 3.2.25 on 2024-09-11 15:13

import admission.contrib.models.form_item
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0220_remove_doctorateadmission_pre_admission_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuingWorkingList',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'order',
                    models.PositiveIntegerField(
                        db_index=True,
                        editable=False,
                        verbose_name='order',
                    ),
                ),
                (
                    'name',
                    admission.contrib.models.form_item.TranslatedJSONField(
                        default=dict,
                        validators=[admission.contrib.models.form_item.is_valid_translated_json_field],
                        verbose_name='Name of the working list',
                    ),
                ),
                (
                    'checklist_filters_mode',
                    models.CharField(
                        blank=True,
                        choices=[('INCLUSION', 'Include'), ('EXCLUSION', 'Exclude')],
                        default='',
                        max_length=16,
                        verbose_name='Checklist filters mode',
                    ),
                ),
                (
                    'checklist_filters',
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name='Checklist filters',
                    ),
                ),
                (
                    'admission_statuses',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ('EN_BROUILLON', 'In draft form'),
                                ('CONFIRMEE', 'Application confirmed'),
                                ('EN_ATTENTE', 'On hold'),
                                ('INSCRIPTION_REFUSEE', 'Application denied'),
                                ('ANNULEE', 'Cancelled application'),
                                ('A_COMPLETER_POUR_FAC', 'To be completed for Fac'),
                                ('COMPLETEE_POUR_FAC', 'Completed for Fac'),
                                ('INSCRIPTION_AUTORISEE', 'Application accepted'),
                                ('CLOTUREE', 'Closed'),
                            ],
                            max_length=30,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name='Admission statuses',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Continuing working list',
                'verbose_name_plural': 'Continuing working lists',
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
