# Generated by Django 3.2.25 on 2024-09-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0224_add_doctorate_checklist_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='cotutelle_institution',
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='cotutelle_institution',
            field=models.UUIDField(blank=True, default=None, null=True, verbose_name='Institution'),
        ),
    ]
