# Generated by Django 3.2.25 on 2024-09-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0224_add_doctorate_checklist_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='epcinjection',
            name='osis_error_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='epcinjection',
            name='osis_stacktrace',
            field=models.TextField(blank=True, default=''),
        ),
    ]
