# Generated by Django 3.2.25 on 2024-09-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0224_add_doctorate_checklist_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='additional_approval_conditions',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='fac_refusal_certificate',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='first_year_inscription_and_status',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='other_training_accepted_by_fac',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='particular_cost',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='rebilling_or_third_party_payer',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='refusal_type',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='sic_refusal_certificate',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='with_additional_approval_conditions',
        ),
        migrations.DeleteModel(
            name='DoctorateFreeAdditionalApprovalCondition',
        ),
    ]
