# Generated by Django 3.2.25 on 2024-09-24 10:50

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from admission.mail_templates import ADMISSION_EMAIL_SUPERVISION_MODIFICATION_DOCTORATE


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0225_alter_doctorateadmission_cotutelle_institution'),
    ]

    operations = [
        MailTemplateMigration(
            ADMISSION_EMAIL_SUPERVISION_MODIFICATION_DOCTORATE,
            {
                'en': "[OSIS] UCLouvain - suivi de votre demande d'admission - {admission_reference}",
                'fr-be': "[OSIS] UCLouvain - suivi de votre demande d'admission - {admission_reference}",
            },
            {
                'en': '''Dear {candidate_first_name} {candidate_last_name},

Thank you for your enrolment application to the {training_title} - {training_acronym} programme for the {academic_year} academic year.

We note that some elements are missing.

Please modify your supervisory committee as follows:

------- via your online application dashboard: {admissions_dashboard_link_front}.

Please request signatures for any additional supervisory committee members in the same way as when you compiled your application.

{sender_name} {phd_committee}
    ''',
                'fr-be': '''Cher, Chère, Cher.ère, {candidate_first_name} {candidate_last_name},

Votre demande d'inscription au programme {training_title} - {training_acronym} pour l'année académique {academic_year} nous est bien parvenue et nous vous en remercions.

Après vérification, nous constatons qu'il manque encore certains éléments.

Veuillez modifier votre comité d’accompagnement de la manière suivante :

-------, obligatoirement via votre tableau de bord de votre demande en ligne : {admissions_dashboard_link_front}.

Veuillez demander les signatures pour les éventuels membres du comité d’accompagnement ajoutés, en procédant de la même façon que lors de la constitution de votre dossier.

{sender_name} {phd_committee}
    ''',
            },
        ),
    ]
