# Generated by Django 3.2.25 on 2024-07-08 15:17
from django.conf import settings
from django.db import migrations

from admission.ddd.admission.domain.enums import TypeFormation
from admission.ddd.admission.enums import (
    TypeItemFormulaire,
    CleConfigurationItemFormulaire,
    TypeChampTexteFormulaire,
    TypeChampSelectionFormulaire, CritereItemFormulaireFormation, Onglets,
)
from admission.infrastructure.admission.domain.service.annee_inscription_formation import (
    AnneeInscriptionFormationTranslator,
)
from base.models.enums.education_group_categories import Categories
from base.models.utils.utils import ChoiceEnum


class SpecificQuestionToInit(ChoiceEnum):
    IUFC_ANNEXES = 'IUFC-Annexes'
    IUFC_BIM1 = 'IUFC-BIM1'
    IUFC_BIM2 = 'IUFC-BIM2'
    IUFC_BIM3 = 'IUFC-BIM3'
    IUFC_BURNOUT = 'IUFC-Burnout'
    IUFC_CHEQUES_FORMATION1 = 'IUFC-Chèques formation1'
    IUFC_CHEQUES_FORMATION2 = 'IUFC-Chèques formation2'
    IUFC_CONGES_EDUCATION = 'IUFC-Congés éducation'
    IUFC_CONGES_EDUCATION_DOC = 'IUFC-Congés éducation doc'
    IUFC_ETALEMENT_PAIEMENT = 'IUFC-Etalement paiement'
    IUFC_HOTEL = 'IUFC-Hôtel'
    IUFC_INAMI = 'IUFC-INAMI'
    IUFC_LANGAGE_PROGR = 'IUFC-Langage progr'
    IUFC_LOGICIELS_STAT = 'IUFC-Logiciels stat'
    IUFC_MEDIATION_ST_LOUIS = 'IUFC-Médiation St Louis'
    IUFC_NIV_ANGLAIS = 'IUFC-Niv anglais'
    IUFC_PC = 'IUFC-PC'
    IUFC_PREREQUIS_STAT = 'IUFC-Prérequis stat'
    IUFC_SECTEUR_ASSOCIATIF_QUESTION = 'IUFC-Secteur associatif question'
    IUFC_SECTEUR_ASSOCIATIF_DOC = 'IUFC-Secteur associatif doc'
    IUFC_TITRE_PEDAGOGIQUE_QUESTION = 'IUFC-Titre pédagogique question'
    IUFC_TITRE_PEDAGOGIQUE_DOC = 'IUFC-Titre pédagogique doc'


def initialize_iufc_specific_questions(apps, schema_editor):
    AdmissionFormItem = apps.get_model('admission', 'AdmissionFormItem')
    AdmissionFormItemInstantiation = apps.get_model('admission', 'AdmissionFormItemInstantiation')
    AcademicYear = apps.get_model('base', 'AcademicYear')
    EducationGroupYear = apps.get_model('base', 'EducationGroupYear')

    if settings.TESTING:
        return

    current_academic_year = AcademicYear.objects.get(year=2024)

    admission_form_items = {
        SpecificQuestionToInit.IUFC_ANNEXES.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_ANNEXES.value,
            type=TypeItemFormulaire.DOCUMENT.name,
            title={
                settings.LANGUAGE_CODE_EN: "Please enclose: \r\n- a copy of the SPF Health visa authorising you to practise as a clinical psychologist; \r\n- a copy of the certificate from the Commission des Psychologues; \r\n- proof of your professional practice (employment contract or sworn statement of independent practice).",
                settings.LANGUAGE_CODE_FR: "Veuillez annexer : \r\n- la copie du visa du SPF santé vous autorisant à exercer la profession de psychologue clinicien, \r\n- la copie du certificat de la Commission des Psychologues, \r\n- une preuve de votre pratique professionnelle (contrat de travail ou déclaration sur l’honneur d’une pratique indépendante).",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={},
        ),
        SpecificQuestionToInit.IUFC_BIM1.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_BIM1.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "Experience using BIM Revit software: please enter your level in one of the boxes below:",
                settings.LANGUAGE_CODE_FR: "Expériences dans l’usage du logiciel BIM Revit : veuillez renseigner votre niveau dans une des cases ci-dessous :",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'A',
                    settings.LANGUAGE_CODE_EN: 'Thorough knowledge',
                    settings.LANGUAGE_CODE_FR: 'Bonne connaissance',
                },
                {
                    'key': 'B',
                    settings.LANGUAGE_CODE_EN: 'Average knowledge',
                    settings.LANGUAGE_CODE_FR: 'Connaissance moyenne',
                },
                {
                    'key': 'C',
                    settings.LANGUAGE_CODE_EN: 'No knowledge',
                    settings.LANGUAGE_CODE_FR: 'Pas de connaissance',
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.CASES_A_COCHER.name,
            },
        ),
        SpecificQuestionToInit.IUFC_BIM2.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_BIM2.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "Experience using Archicad BIM software: please enter your level in one of the boxes below:",
                settings.LANGUAGE_CODE_FR: "Expériences dans l’usage du logiciel BIM Archicad : veuillez renseigner votre niveau dans une des cases ci-dessous :",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'A',
                    settings.LANGUAGE_CODE_EN: 'Thorough knowledge',
                    settings.LANGUAGE_CODE_FR: 'Bonne connaissance',
                },
                {
                    'key': 'B',
                    settings.LANGUAGE_CODE_EN: 'Average knowledge',
                    settings.LANGUAGE_CODE_FR: 'Connaissance moyenne',
                },
                {
                    'key': 'C',
                    settings.LANGUAGE_CODE_EN: 'No knowledge',
                    settings.LANGUAGE_CODE_FR: 'Pas de connaissance',
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.CASES_A_COCHER.name,
            },
        ),
        SpecificQuestionToInit.IUFC_BIM3.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_BIM3.value,
            type=TypeItemFormulaire.TEXTE.name,
            title={
                settings.LANGUAGE_CODE_EN: "If you know other software, please indicate them here, with your level of knowledge for each (A = Thorough knowledge B = Average knowledge). If you do not know any, please indicate \"NA\".",
                settings.LANGUAGE_CODE_FR: "Si vous connaissez d'autres logiciels, merci de les indiquer ici, avec votre niveau de connaissance pour chacun (A = Bonne connaissance B = Connaissance moyenne). Si vous n'en connaissez pas, veuillez indiquer \"NA\".",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TAILLE_TEXTE.name: TypeChampTexteFormulaire.LONG.name,
            },
        ),
        SpecificQuestionToInit.IUFC_BURNOUT.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_BURNOUT.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "Have you already taken the Burnout Academy course and would like to obtain the university certificate (regularisation)? In this case, you will not attend the course and will only pay the registration fee at UCLouvain (€66). Please indicate whether this applies to you.",
                settings.LANGUAGE_CODE_FR: "Vous avez déjà suivi la formation à l'Académie Burnout et vous souhaitez obtenir le certificat d'université (régularisation) ? Dans ce cas, vous ne participez pas aux cours et ne payez que l'inscription au rôle à l'UCLouvain (66€). Veuillez indiquer si vous êtes concerné.e par cette situation.",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'YES',
                    settings.LANGUAGE_CODE_EN: 'yes',
                    settings.LANGUAGE_CODE_FR: 'oui',
                },
                {
                    'key': 'NO',
                    settings.LANGUAGE_CODE_EN: 'no',
                    settings.LANGUAGE_CODE_FR: 'non',
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.BOUTONS_RADIOS.name,
            },
        ),
        SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "Would you like to pay with Chèques-Formation?",
                settings.LANGUAGE_CODE_FR: "Souhaitez-vous payer par Chèques-Formation ?",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'YES',
                    settings.LANGUAGE_CODE_EN: 'yes',
                    settings.LANGUAGE_CODE_FR: 'oui',
                },
                {
                    'key': 'NO',
                    settings.LANGUAGE_CODE_EN: 'no',
                    settings.LANGUAGE_CODE_FR: 'non',
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.BOUTONS_RADIOS.name,
            },
        ),
        SpecificQuestionToInit.IUFC_CHEQUES_FORMATION2.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_CHEQUES_FORMATION2.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "Would you like to pay with Chèques-Formation? (No discount available.)",
                settings.LANGUAGE_CODE_FR: "Souhaitez-vous payer par Chèques-Formation ? (pas de réduction disponible)",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'YES',
                    settings.LANGUAGE_CODE_EN: 'yes',
                    settings.LANGUAGE_CODE_FR: 'oui',
                },
                {
                    'key': 'NO',
                    settings.LANGUAGE_CODE_EN: 'no',
                    settings.LANGUAGE_CODE_FR: 'non',
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.BOUTONS_RADIOS.name,
            },
        ),
        SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_CONGES_EDUCATION.value,
            type=TypeItemFormulaire.TEXTE.name,
            title={
                settings.LANGUAGE_CODE_EN: "If you wish to take educational leave, please indicate the number of the joint committee to which you belong. If this does not apply to you, please indicate \"NA\":",
                settings.LANGUAGE_CODE_FR: "Si vous souhaitez bénéficier de congés éducation, veuillez indiquer le n° de la commission paritaire dont vous dépendez. Si vous n'êtes pas concerné, veuillez indiquer \"NA\" :",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TAILLE_TEXTE.name: TypeChampTexteFormulaire.COURT.name,
            },
        ),
        SpecificQuestionToInit.IUFC_CONGES_EDUCATION_DOC.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_CONGES_EDUCATION_DOC.value,
            type=TypeItemFormulaire.TEXTE.name,
            title={
                settings.LANGUAGE_CODE_EN: "If you would like to receive documents for paid educational leave, please indicate your company's headquarters here. If this does not apply to you, please indicate \"NA\":",
                settings.LANGUAGE_CODE_FR: "Si vous souhaitez bénéficier des documents pour les Congés-Education Payés veuillez indiquer ici le siège social de votre société. Si vous n'êtes pas concerné, veuillez indiquer \"NA\" :",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TAILLE_TEXTE.name: TypeChampTexteFormulaire.COURT.name,
            },
        ),
        SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.value,
            type=TypeItemFormulaire.TEXTE.name,
            title={
                settings.LANGUAGE_CODE_EN: "If you wish to benefit from deferred payment, please justify your request here. If this does not apply to you, please indicate \"NA\":",
                settings.LANGUAGE_CODE_FR: "Si vous souhaitez bénéficier d'un étalement de paiement, veuillez justifier ici votre demande. Si vous n'êtes pas concerné, veuillez indiquer \"NA\" :",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TAILLE_TEXTE.name: TypeChampTexteFormulaire.LONG.name,
            },
        ),
        SpecificQuestionToInit.IUFC_HOTEL.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_HOTEL.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "Are you staying in a hotel (attendance of all courses from 8.30am to 9.30pm is compulsory)?",
                settings.LANGUAGE_CODE_FR: "Logez-vous à l’hôtel ? (la présence à l’ensemble des cours de 8h30 à 21h30 est obligatoire)",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'YES',
                    settings.LANGUAGE_CODE_EN: 'yes',
                    settings.LANGUAGE_CODE_FR: 'oui',
                },
                {
                    'key': 'NO',
                    settings.LANGUAGE_CODE_EN: 'no',
                    settings.LANGUAGE_CODE_FR: 'non',
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.BOUTONS_RADIOS.name,
            },
        ),
        SpecificQuestionToInit.IUFC_INAMI.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_INAMI.value,
            type=TypeItemFormulaire.TEXTE.name,
            title={
                settings.LANGUAGE_CODE_EN: "If you have a Belgian INAMI doctor's number, please enter it here, without spaces or dashes. If you are not a doctor, please indicate \"NA\":",
                settings.LANGUAGE_CODE_FR: "Si vous possédez un n° de médecin INAMI belge, merci de l'indiquer ici, sans espace ni tiret. Si vous n'êtes pas médecin, veuillez indiquer \"NA\" :",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TAILLE_TEXTE.name: TypeChampTexteFormulaire.COURT.name,
            },
        ),
        SpecificQuestionToInit.IUFC_LANGAGE_PROGR.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_LANGAGE_PROGR.value,
            type=TypeItemFormulaire.TEXTE.name,
            title={
                settings.LANGUAGE_CODE_EN: "Please indicate below your knowledge of programming languages:",
                settings.LANGUAGE_CODE_FR: "Veuillez indiquer ci-dessous vos connaissances en langages de programmations :",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TAILLE_TEXTE.name: TypeChampTexteFormulaire.LONG.name,
            },
        ),
        SpecificQuestionToInit.IUFC_LOGICIELS_STAT.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_LOGICIELS_STAT.value,
            type=TypeItemFormulaire.TEXTE.name,
            title={
                settings.LANGUAGE_CODE_EN: "Please indicate below your knowledge of statistical software:",
                settings.LANGUAGE_CODE_FR: "Veuillez indiquer ci-dessous vos connaissances en logiciels de statistique :",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TAILLE_TEXTE.name: TypeChampTexteFormulaire.LONG.name,
            },
        ),
        SpecificQuestionToInit.IUFC_MEDIATION_ST_LOUIS.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_MEDIATION_ST_LOUIS.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "Have you taken the general mediation course at Université Saint-Louis (interuniversity certificate)?",
                settings.LANGUAGE_CODE_FR: "Avez-vous suivi la formation à la médiation générale à l'Université Saint-Louis (certificat interuniversitaire) ?",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'YES',
                    settings.LANGUAGE_CODE_EN: 'yes',
                    settings.LANGUAGE_CODE_FR: 'oui',
                },
                {
                    'key': 'NO',
                    settings.LANGUAGE_CODE_EN: 'no',
                    settings.LANGUAGE_CODE_FR: 'non',
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.BOUTONS_RADIOS.name,
            },
        ),
        SpecificQuestionToInit.IUFC_NIV_ANGLAIS.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_NIV_ANGLAIS.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "Please indicate your level of English below:",
                settings.LANGUAGE_CODE_FR: "Veuillez indiquer ci-dessous votre niveau d'anglais :",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'A1',
                    settings.LANGUAGE_CODE_EN: 'A1',
                    settings.LANGUAGE_CODE_FR: 'A1',
                },
                {
                    'key': 'A2',
                    settings.LANGUAGE_CODE_EN: 'A2',
                    settings.LANGUAGE_CODE_FR: 'A2',
                },
                {
                    'key': 'B1',
                    settings.LANGUAGE_CODE_EN: 'B1',
                    settings.LANGUAGE_CODE_FR: 'B1',
                },
                {
                    'key': 'B2',
                    settings.LANGUAGE_CODE_EN: 'B2',
                    settings.LANGUAGE_CODE_FR: 'B2',
                },
                {
                    'key': 'C1',
                    settings.LANGUAGE_CODE_EN: 'C1',
                    settings.LANGUAGE_CODE_FR: 'C1',
                },
                {
                    'key': 'C2',
                    settings.LANGUAGE_CODE_EN: 'C2',
                    settings.LANGUAGE_CODE_FR: 'C2',
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.CASES_A_COCHER.name,
            },
        ),
        SpecificQuestionToInit.IUFC_PC.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_PC.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "PC for the training:",
                settings.LANGUAGE_CODE_FR: "PC pour la formation :",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'NO_BORROWING',
                    settings.LANGUAGE_CODE_EN: "I will use my own computer (software provided, but you have to do the registration and installation yourself)",
                    settings.LANGUAGE_CODE_FR: "J'utilise mon ordinateur (logiciels fournis mais procédures d'enregistrements et d'installation à faire soi même)",
                },
                {
                    'key': 'SHORT_BORROWING',
                    settings.LANGUAGE_CODE_EN: "I will borrow a laptop for the two weeks of training",
                    settings.LANGUAGE_CODE_FR: "J'emprunte un PC portable pour les deux semaines de formation",
                },
                {
                    'key': 'LONG_BORROWING',
                    settings.LANGUAGE_CODE_EN: "I will borrow a laptop for the six months of training (€400 deposit)",
                    settings.LANGUAGE_CODE_FR: "J'emprunte un PC portable pour les 6 mois de formation (caution de 400€)",
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.CASES_A_COCHER.name,
            },
        ),
        SpecificQuestionToInit.IUFC_PREREQUIS_STAT.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_PREREQUIS_STAT.value,
            type=TypeItemFormulaire.TEXTE.name,
            title={
                settings.LANGUAGE_CODE_EN: "Please indicate below your statistics prerequisites:",
                settings.LANGUAGE_CODE_FR: "Veuillez indiquer ci-dessous vos prérequis en statistique :",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TAILLE_TEXTE.name: TypeChampTexteFormulaire.LONG.name,
            },
        ),
        SpecificQuestionToInit.IUFC_SECTEUR_ASSOCIATIF_QUESTION.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_SECTEUR_ASSOCIATIF_QUESTION.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "Do you work in the non-profit sector? If so, please provide proof below:",
                settings.LANGUAGE_CODE_FR: "Êtes vous membre du secteur associatif ? Si oui, veuillez fournir un justificatif ci-dessous :",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'YES',
                    settings.LANGUAGE_CODE_EN: 'yes',
                    settings.LANGUAGE_CODE_FR: 'oui',
                },
                {
                    'key': 'NO',
                    settings.LANGUAGE_CODE_EN: 'no',
                    settings.LANGUAGE_CODE_FR: 'non',
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.BOUTONS_RADIOS.name,
            },
        ),
        SpecificQuestionToInit.IUFC_SECTEUR_ASSOCIATIF_DOC.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_SECTEUR_ASSOCIATIF_DOC.value,
            type=TypeItemFormulaire.DOCUMENT.name,
            title={
                settings.LANGUAGE_CODE_EN: "Proof non-profit-sector",
                settings.LANGUAGE_CODE_FR: "Justificatif secteur associatif",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={},
        ),
        SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_QUESTION.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_QUESTION.value,
            type=TypeItemFormulaire.SELECTION.name,
            title={
                settings.LANGUAGE_CODE_EN: "Do you have a teaching qualification? If so, please provide it below:",
                settings.LANGUAGE_CODE_FR: "Possédez-vous un titre pédagogique ? Si oui, veuillez le fournir ci-dessous :",
            },
            text={},
            help_text={},
            values=[
                {
                    'key': 'YES',
                    settings.LANGUAGE_CODE_EN: 'yes',
                    settings.LANGUAGE_CODE_FR: 'oui',
                },
                {
                    'key': 'NO',
                    settings.LANGUAGE_CODE_EN: 'no',
                    settings.LANGUAGE_CODE_FR: 'non',
                },
            ],
            active=True,
            configuration={
                CleConfigurationItemFormulaire.TYPE_SELECTION.name: TypeChampSelectionFormulaire.BOUTONS_RADIOS.name,
            },
        ),
        SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_DOC.name: AdmissionFormItem(
            internal_label=SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_DOC.value,
            type=TypeItemFormulaire.DOCUMENT.name,
            title={
                settings.LANGUAGE_CODE_EN: "Teaching qualification",
                settings.LANGUAGE_CODE_FR: "Titre pédagogique",
            },
            text={},
            help_text={},
            values=[],
            active=True,
            configuration={},
        ),
    }

    # All education group years
    education_group_id_by_acronym = {
        training['acronym']: training['education_group_id']
        for training in EducationGroupYear.objects.filter(
            academic_year=current_academic_year,
            education_group_type__category=Categories.TRAINING.name,
            education_group_type__name__in=AnneeInscriptionFormationTranslator.OSIS_ADMISSION_EDUCATION_TYPES_MAPPING[
                TypeFormation.FORMATION_CONTINUE.name
            ],
            enrollment_enabled=True,
        ).values('acronym', 'education_group_id')
    }

    AdmissionFormItem.objects.bulk_create(list(admission_form_items.values()))

    questions_by_education_acronym = {
        'ACPA2FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'ACSP2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
        ],
        'ACTI2FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
            SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.name,
        ],
        'ANMS2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'ANPC2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'ASBL2FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
            SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.name,
            SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.name,
        ],
        'ATTA2FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'BIMM2FC': [
            SpecificQuestionToInit.IUFC_BIM1.name,
            SpecificQuestionToInit.IUFC_BIM2.name,
            SpecificQuestionToInit.IUFC_BIM3.name,
            SpecificQuestionToInit.IUFC_PC.name,
            SpecificQuestionToInit.IUFC_HOTEL.name,
            SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.name,
        ],
        'COWE2FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
            SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.name,
            SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.name,
        ],
        'DIIS1FC': [
            SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_QUESTION.name,
            SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_DOC.name,
        ],
        'DIOR1FC': [
            SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_QUESTION.name,
            SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_DOC.name,
        ],
        'DIRI1FC': [
            SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_QUESTION.name,
            SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_DOC.name,
        ],
        'DTCM7FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'BUPP2FC': [
            SpecificQuestionToInit.IUFC_BURNOUT.name,
        ],
        'EEDI2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'EMAN2FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
            SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.name,
            SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.name,
        ],
        'EXME2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'FISC8FC': [
            SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.name,
        ],
        'GOTE2FC': [
            SpecificQuestionToInit.IUFC_SECTEUR_ASSOCIATIF_QUESTION.name,
            SpecificQuestionToInit.IUFC_SECTEUR_ASSOCIATIF_DOC.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION_DOC.name,
            SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.name,
            SpecificQuestionToInit.IUFC_CHEQUES_FORMATION2.name,
        ],
        'HFIN8FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'HGES2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'HUSU2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'HYHO2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'INCL2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'LEAD2FC': [
            SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.name,
        ],
        'MAFI2FC': [
            SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.name,
        ],
        'MAIJ2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'MARH1FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION_DOC.name,
            SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.name,
            SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.name,
        ],
        'MCRI2FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION_DOC.name,
            SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.name,
        ],
        'MEFA2FC': [
            SpecificQuestionToInit.IUFC_MEDIATION_ST_LOUIS.name,
        ],
        'MMPE2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'NUCL2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'PERI2FC': [
            SpecificQuestionToInit.IUFC_INAMI.name,
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
        ],
        'PLPA2FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION_DOC.name,
            SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.name,
        ],
        'PRAS2FC': [
            SpecificQuestionToInit.IUFC_CHEQUES_FORMATION1.name,
        ],
        'PSPE2FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION.name,
            SpecificQuestionToInit.IUFC_ANNEXES.name,
        ],
        'STAT2FC': [
            SpecificQuestionToInit.IUFC_CONGES_EDUCATION_DOC.name,
            SpecificQuestionToInit.IUFC_ETALEMENT_PAIEMENT.name,
            SpecificQuestionToInit.IUFC_PREREQUIS_STAT.name,
            SpecificQuestionToInit.IUFC_LOGICIELS_STAT.name,
            SpecificQuestionToInit.IUFC_LANGAGE_PROGR.name,
            SpecificQuestionToInit.IUFC_NIV_ANGLAIS.name,
        ],
    }

    facultative_questions = {
        SpecificQuestionToInit.IUFC_SECTEUR_ASSOCIATIF_DOC.name,
        SpecificQuestionToInit.IUFC_TITRE_PEDAGOGIQUE_DOC.name,
    }

    admission_form_items_instantiations = []
    for acronym, questions in questions_by_education_acronym.items():
        if acronym not in education_group_id_by_acronym:
            continue

        education_group_id = education_group_id_by_acronym[acronym]

        for index, question in enumerate(questions):
            admission_form_items_instantiations.append(
                AdmissionFormItemInstantiation(
                    form_item=admission_form_items[question],
                    academic_year=current_academic_year,
                    weight=index,
                    required=question not in facultative_questions,
                    display_according_education=CritereItemFormulaireFormation.UNE_FORMATION.name,
                    education_group_id=education_group_id,
                    admission=None,
                    tab=Onglets.INFORMATIONS_ADDITIONNELLES.name,
                )
            )

    AdmissionFormItemInstantiation.objects.bulk_create(admission_form_items_instantiations)

class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0225_auto_20240917_1044'),
    ]

    operations = [
        migrations.RunPython(code=initialize_iufc_specific_questions, reverse_code=migrations.RunPython.noop),
    ]
