# Generated by Django 3.2.25 on 2024-07-08 15:17

from django.db import migrations
from django.db.migrations import RunPython
from osis_mail_template import MailTemplateMigration

from admission.mail_templates import (
    ADMISSION_EMAIL_FAC_REFUSAL_DOCTORATE,
    ADMISSION_EMAIL_FAC_APPROVAL_DOCTORATE_WITHOUT_BELGIAN_DIPLOMA,
    ADMISSION_EMAIL_FAC_APPROVAL_DOCTORATE_WITH_BELGIAN_DIPLOMA,
)


def remove_unused_emails(apps, schema_editor):
    MailTemplate = apps.get_model('osis_mail_template', 'MailTemplate')
    MailTemplate.objects.filter(identifier='osis-admission-send-to-fac-at-fac-decision-doctorate').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0225_doctorate_delete_unused_fields'),
    ]

    operations = [
        MailTemplateMigration(
            identifier=ADMISSION_EMAIL_FAC_REFUSAL_DOCTORATE,
            subjects={
                'en': "UCLouvain - admission application {admission_reference} follow-up",
                'fr-be': "UCLouvain - suivi de votre demande d'admission - {admission_reference}",
            },
            contents={
                'en': '''<p>{greetings} {candidate_first_name} {candidate_last_name},</p>

                <p>Thank you for your admission application to the {training_acronym} / {training_title} programme
                  for the {academic_year} academic year.</p>

                <p>After evaluating your application, we regret to inform you that your application for admission 
                  has not been accepted.</p>
                  
                <p><strong>(motif : texte à insérer par gestionnaire)</strong></p>
                  
                <p>{sender_name} - {doctoral_commission}</p>
                ''',
                'fr-be': '''<p>{greetings} {candidate_first_name} {candidate_last_name},</p>

                <p>Votre demande d'admission à l'année académique {academic_year} au programme {training_acronym} / {training_title}
                  nous est bien parvenue et nous vous en remercions.</p>

                <p>Après analyse de votre dossier, nous sommes au regret de vous informer que votre demande d'admission n'a
                  pu faire l'objet d'une réponse favorable.</p>
                  
                <p><strong>(motif : texte à insérer par gestionnaire)</strong></p>
                  
                <p>{sender_name} - {doctoral_commission}</p>
                ''',
            },
        ),
        MailTemplateMigration(
            identifier=ADMISSION_EMAIL_FAC_APPROVAL_DOCTORATE_WITH_BELGIAN_DIPLOMA,
            subjects={
                'en': "UCLouvain - admission application {admission_reference} follow-up",
                'fr-be': "UCLouvain - suivi de votre demande d'admission - {admission_reference}",
            },
            contents={
                'en': '''<p>{greetings} {candidate_first_name} {candidate_last_name},</p>

                <p>Thank you for your admission application to the {training_acronym} / {training_title} programme
                  for the {academic_year} academic year.</p>

                <p>The PhD Field Committee has approved your application, which is now with the Enrolment Office (SIC).</p>

                <p>A series of practical considerations concerning your PhD are summarised in a document in your document section.</p>

                <p>Please remember that you must enrol for the PhD every year until the academic year in which you defend your thesis.</p>

                <p>{sender_name} - {doctoral_commission}</p>
                ''',
                'fr-be': '''<p>{greetings} {candidate_first_name} {candidate_last_name},</p>

                <p>Votre demande d'admission à l'année académique {academic_year} au programme {training_acronym} / {training_title}
                  nous est bien parvenue et nous vous en remercions.</p>

                <p>Nous vous informons que la Commission doctorale de domaine s’est réunie et qu’elle a validé votre demande;
                  il est actuellement entre les mains du Service des inscriptions (SIC).

                <p>Une série de considérations pratiques liées à votre doctorat sont résumées dans un document se trouvant dans votre espace document.</p>

                <p>Nous vous rappelons que l’inscription au doctorat est annuelle et ce jusqu’à l’année académique de la soutenance.</p>

                <p>{sender_name} - {doctoral_commission}</p>
                ''',
            },
        ),
        MailTemplateMigration(
            identifier=ADMISSION_EMAIL_FAC_APPROVAL_DOCTORATE_WITHOUT_BELGIAN_DIPLOMA,
            subjects={
                'en': "UCLouvain - admission application {admission_reference} follow-up",
                'fr-be': "UCLouvain - suivi de votre demande d'admission - {admission_reference}",
            },
            contents={
                'en': '''<p>{greetings} {candidate_first_name} {candidate_last_name},</p>

                <p>Thank you for your admission application to the {training_acronym} / {training_title} programme
                  for the {academic_year} academic year.</p>

                <p>The PhD Field Committee has approved your application, which is now with the Enrolment Office (SIC).</p>

                <p>If it accepts your application, SIC will immediately send you an enrolment authorisation.</p>

                <p>A series of practical considerations concerning your PhD are summarised in a document in your document section.</p>

                <p>Please remember that you must enrol for the PhD every year until the academic year in which you defend your thesis.</p>

                <p>{sender_name} - {doctoral_commission}</p>
                ''',
                'fr-be': '''<p>{greetings} {candidate_first_name} {candidate_last_name},</p>

                <p>Votre demande d'admission à l'année académique {academic_year} au programme {training_acronym} / {training_title}
                  nous est bien parvenue et nous vous en remercions.</p>

                <p>Nous vous informons que la Commission doctorale de domaine s’est réunie et qu’elle a validé votre demande;
                  il est actuellement entre les mains du Service des inscriptions (SIC).

                <p>Sous réserve de l’acceptation de votre dossier par le SIC, l’autorisation d’inscription vous sera délivrée par ce service très prochainement.</p>

                <p>Une série de considérations pratiques liées à votre doctorat sont résumées dans un document se trouvant dans votre espace document.</p>

                <p>Nous vous rappelons que l’inscription au doctorat est annuelle et ce jusqu’à l’année académique de la soutenance.</p>

                <p>{sender_name} - {doctoral_commission}</p>
                ''',
            },
        ),
        RunPython(code=remove_unused_emails, reverse_code=migrations.RunPython.noop),
    ]
