# Generated by Django 3.2.25 on 2024-10-03 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0702_auto_20240909_1218'),
        ('admission', '0226_initialize_iufc_specific_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaleducationadmission',
            old_name='financability_rule_established_by',
            new_name='financability_established_by',
        ),
        migrations.RenameField(
            model_name='generaleducationadmission',
            old_name='financability_rule_established_on',
            new_name='financability_established_on',
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='financability_established_by',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='base.person',
                verbose_name='Financability established by',
            ),
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='financability_established_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Financability established on'),
        ),
        migrations.RenameField(
            model_name='doctorateadmission',
            old_name='financability_rule_established_by',
            new_name='financability_established_by',
        ),
        migrations.RenameField(
            model_name='doctorateadmission',
            old_name='financability_rule_established_on',
            new_name='financability_established_on',
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='financability_established_by',
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='base.person',
                verbose_name='Financability established by',
            ),
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='financability_established_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Financability established on'),
        ),
    ]
