# Generated by Django 3.2.25 on 2024-10-24 09:37

from django.conf import settings
from django.db import migrations


def ajout_au_group_program_manager(apps, schema_editor):
    if settings.TESTING:
        return
    ContinuingEducationTrainingManager = apps.get_model('continuing_education', 'ContinuingEducationTrainingManager')
    Group = apps.get_model('auth', 'Group')
    group, _ = Group.objects.get_or_create(name='admission_program_managers')
    gestionnaires_iufc = ContinuingEducationTrainingManager.objects.all().select_related(
        'training__education_group',
        'person',
    )
    print(f"{gestionnaires_iufc.count()} gestionnaires IUFC a ajouter au group Program Manager")
    for gestionnaire in gestionnaires_iufc:
        gestionnaire.person.user.groups.add(group)

class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0226_initialize_iufc_specific_questions'),
    ]

    operations = [
        migrations.RunPython(ajout_au_group_program_manager, elidable=True, reverse_code=migrations.RunPython.noop),
    ]
