# Generated by Django 3.2.25 on 2024-09-25 14:22

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0226_initialize_iufc_specific_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='additional_approval_conditions',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='fac_refusal_certificate',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='first_year_inscription_and_status',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='other_training_accepted_by_fac',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='particular_cost',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='rebilling_or_third_party_payer',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='refusal_type',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='sic_refusal_certificate',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='with_additional_approval_conditions',
        ),
        migrations.DeleteModel(
            name='DoctorateFreeAdditionalApprovalCondition',
        ),
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='fac_approval_certificate',
        ),
        migrations.AddField(
            model_name='doctorateadmission',
            name='cdd_approval_certificate',
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name='Approval certificate of the CDD',
            ),
        ),
        migrations.AlterField(
            model_name='categorizedfreedocument',
            name='checklist_tab',
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        'General education',
                        (
                            ('donnees_personnelles', 'Personal data'),
                            ('assimilation', 'Belgian student status'),
                            ('frais_dossier', 'Application fee'),
                            ('parcours_anterieur', 'Previous experience'),
                            ('experiences_parcours_anterieur', 'Previous experiences'),
                            ('financabilite', 'Financeability'),
                            ('choix_formation', 'Course choice'),
                            ('specificites_formation', 'Training specificities'),
                            ('decision_facultaire', 'Decision of the faculty'),
                            ('decision_sic', 'Decision of SIC'),
                        ),
                    ),
                    (
                        'Continuing education',
                        (
                            ('fiche_etudiant', 'Student report'),
                            ('decision', 'Decision'),
                        ),
                    ),
                    (
                        'Doctorate education',
                        (
                            ('donnees_personnelles', 'Personal data'),
                            ('assimilation', 'Belgian student status'),
                            ('parcours_anterieur', 'Previous experience'),
                            ('experiences_parcours_anterieur', 'Previous experiences'),
                            ('financabilite', 'Financeability'),
                            ('choix_formation', 'Course choice'),
                            ('projet_recherche', 'Research'),
                            ('decision_cdd', 'Decision of the CDD'),
                            ('decision_sic', 'Decision of SIC'),
                        ),
                    ),
                ],
                default='',
                max_length=255,
                verbose_name='Checklist tab',
            ),
        ),
    ]
