# Generated by Django 3.2.25 on 2024-09-24 10:50

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from admission.mail_templates import ADMISSION_EMAIL_SUPERVISION_MODIFICATION_DOCTORATE


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0226_initialize_iufc_specific_questions'),
    ]

    operations = [
        MailTemplateMigration(
            ADMISSION_EMAIL_SUPERVISION_MODIFICATION_DOCTORATE,
            {
                'en': "[OSIS] UCLouvain - follow up of your application - {admission_reference}",
                'fr-be': "[OSIS] UCLouvain - suivi de votre demande d'admission - {admission_reference}",
            },
            {
                'en': '''<p>Dear {candidate_first_name} {candidate_last_name},</p>

<p>Thank you for your enrolment application to the {training_title} - {training_acronym} programme for the {academic_year} academic year.</p>

<p>We note that some elements are missing.</p>

<p>Please modify your supervisory committee as follows:</p>

<p><strong>(texte à insérer par gestionnaire)</strong> via your online application dashboard: {admissions_link_front}.</p>

<p>Please request signatures for any additional supervisory committee members in the same way as when you compiled your application.</p>

<p>{sender_name} - {phd_committee}</p>
    ''',
                'fr-be': '''<p>Cher, Chère, Cher.ère, {candidate_first_name} {candidate_last_name},</p>

<p>Votre demande d'inscription au programme {training_title} - {training_acronym} pour l'année académique {academic_year} nous est bien parvenue et nous vous en remercions.</p>

<p>Après vérification, nous constatons qu'il manque encore certains éléments.</p>

<p>Veuillez modifier votre comité d’accompagnement de la manière suivante :</p>

<p><strong>(texte à insérer par gestionnaire)</strong>, obligatoirement via votre tableau de bord de votre demande en ligne : {admissions_link_front}.</p>

<p>Veuillez demander les signatures pour les éventuels membres du comité d’accompagnement ajoutés, en procédant de la même façon que lors de la constitution de votre dossier.</p>

<p>{sender_name} - {phd_committee}</p>
    ''',
            },
        ),
    ]
