# Generated by Django 3.2.25 on 2024-10-18 17:40

import django.contrib.postgres.fields
from django.db import migrations, models


def _update_central_manager_scopes(apps, old_value, new_value):
    CentralManager = apps.get_model('admission', 'CentralManager')
    central_managers_with_all_scope = CentralManager.objects.filter(scopes__contains=[old_value])

    for central_manager in central_managers_with_all_scope:
        central_manager.scopes[central_manager.scopes.index(old_value)] = new_value

    CentralManager.objects.bulk_update(central_managers_with_all_scope, ['scopes'])


def update_central_manager_scopes_forward(apps, schema_editor):
    _update_central_manager_scopes(apps, 'ALL', 'GENERAL')


def update_central_manager_scopes_reverse(apps, schema_editor):
    _update_central_manager_scopes(apps, 'GENERAL', 'ALL')


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0226_initialize_iufc_specific_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralmanager',
            name='scopes',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[('GENERAL', 'GENERAL'), ('IUFC', 'IUFC'), ('DOCTORAT', 'DOCTORAT')],
                    max_length=200,
                ),
                blank=True,
                size=None,
            ),
        ),
        migrations.RunPython(
            code=update_central_manager_scopes_forward,
            reverse_code=update_central_manager_scopes_reverse,
        ),
    ]
