# Generated by Django 3.2.25 on 2024-10-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0226_initialize_iufc_specific_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cddconfiguration',
            name='cdd',
        ),
        migrations.RemoveField(
            model_name='confirmationpaper',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='internalnote',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='internalnote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='jurymember',
            name='country',
        ),
        migrations.RemoveField(
            model_name='jurymember',
            name='doctorate',
        ),
        migrations.RemoveField(
            model_name='jurymember',
            name='person',
        ),
        migrations.RemoveField(
            model_name='jurymember',
            name='promoter',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='CddConfiguration',
        ),
        migrations.DeleteModel(
            name='ConfirmationPaper',
        ),
        migrations.DeleteModel(
            name='InternalNote',
        ),
        migrations.DeleteModel(
            name='JuryMember',
        ),
    ]
