# Generated by Django 3.2.25 on 2024-10-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0227_auto_20241024_0937'),
        ('admission', '0227_rename_financability_established'),
    ]

    operations = [
    ]
