# Generated by Django 3.2.25 on 2024-10-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0227_doctorate_financeabilite_email'),
        ('admission', '0228_doctorate_faculty_decision_emails'),
        ('admission', '0228_merge_20241028_0856'),
    ]

    operations = [
    ]
