# Generated by Django 3.2.25 on 2024-10-11 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0703_auto_20240926_1738'),
        ('admission', '0231_alter_doctorateadmission_cotutelle_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cddconfiguration',
            name='cdd',
            field=models.OneToOneField(
                limit_choices_to={'organization__type': 'MAIN'},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='admission_config',
                to='base.entity',
            ),
        ),
        migrations.AlterField(
            model_name='cddconfigurator',
            name='entity',
            field=models.ForeignKey(
                limit_choices_to={'organization__type': 'MAIN'},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='base.entity',
            ),
        ),
        migrations.AlterField(
            model_name='cddmailtemplate',
            name='cdd',
            field=models.ForeignKey(
                limit_choices_to={'organization__type': 'MAIN'},
                on_delete=django.db.models.deletion.CASCADE,
                related_name='+',
                to='base.entity',
            ),
        ),
    ]
