# Generated by Django 4.2.16 on 2024-11-12 10:13

from django.db import migrations, models
import osis_document.contrib.fields


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0234_remove_epcinjection_osis_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="reorientation_form",
            field=osis_document.contrib.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=1,
                verbose_name="Completed and signed reorientation form",
            ),
        ),
    ]
