# Generated by Django 4.2.16 on 2025-01-14 17:37

from django.db import migrations, models
from django.db.models.expressions import Case, When, F, Value

from admission.ddd.admission.formation_generale.domain.model.enums import DroitsInscriptionMontant

VALUES_MAPPING = {
    'DROITS_MAJORES': DroitsInscriptionMontant.ANCIENS_DROITS_MAJORES_4175.name,
    'NOUVEAUX_DROITS_MAJORES': DroitsInscriptionMontant.ANCIENS_DROITS_MAJORES_2505.name,
}


def update_admission_tuition_fees_amount_with_new_values(apps, schema_editor):
    DoctorateAdmission = apps.get_model('admission', 'DoctorateAdmission')
    GeneralEducationAdmission = apps.get_model('admission', 'GeneralEducationAdmission')

    for model_class in [DoctorateAdmission, GeneralEducationAdmission]:
        # Update the old values of the tuition fees amount with the new ones
        model_class.objects.filter(tuition_fees_amount__in=VALUES_MAPPING.keys(),).update(
            tuition_fees_amount=Case(
                *[
                    When(
                        tuition_fees_amount=old_value,
                        then=Value(new_value),
                    )
                    for old_value, new_value in VALUES_MAPPING.items()
                ],
                default=F('tuition_fees_amount'),
            )
        )


def update_admission_tuition_fees_amount_with_old_values(apps, schema_editor):
    DoctorateAdmission = apps.get_model('admission', 'DoctorateAdmission')
    GeneralEducationAdmission = apps.get_model('admission', 'GeneralEducationAdmission')

    for model_class in [DoctorateAdmission, GeneralEducationAdmission]:

        # 5010 was not a predefined value so we need to specify it as a custom value
        model_class.objects.filter(tuition_fees_amount=DroitsInscriptionMontant.NOUVEAUX_DROITS_MAJORES.name,).update(
            tuition_fees_amount=DroitsInscriptionMontant.AUTRE.name,
            tuition_fees_amount_other=5010,
        )

        # Update the new values of the tuition fees amount with the old ones
        model_class.objects.filter(tuition_fees_amount__in=VALUES_MAPPING.values(),).update(
            tuition_fees_amount=Case(
                *[
                    When(
                        tuition_fees_amount=new_value,
                        then=Value(old_value),
                    )
                    for old_value, new_value in VALUES_MAPPING.items()
                ],
                default=F('tuition_fees_amount'),
            )
        )


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0236_parcours_doctoral_refactoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='tuition_fees_amount',
            field=models.CharField(
                choices=[
                    ('INSCRIPTION_AU_ROLE', 'INSCRIPTION_AU_ROLE'),
                    ('INSCRIPTION_REGULIERE', 'INSCRIPTION_REGULIERE'),
                    ('NOUVEAUX_DROITS_MAJORES', 'NOUVEAUX_DROITS_MAJORES'),
                    ('ANCIENS_DROITS_MAJORES_2505', 'ANCIENS_DROITS_MAJORES_2505'),
                    ('ANCIENS_DROITS_MAJORES_4175', 'ANCIENS_DROITS_MAJORES_4175'),
                    ('AGREGATION', 'AGREGATION'),
                    ('MASTER_DE_SPECIALISATION_SANTE', 'MASTER_DE_SPECIALISATION_SANTE'),
                    ('CERTIFICAT_60_CREDITS', 'CERTIFICAT_60_CREDITS'),
                    ('PAS_DE_DROITS_D_INSCRIPTION', 'PAS_DE_DROITS_D_INSCRIPTION'),
                    ('AUTRE', 'AUTRE'),
                ],
                default='',
                max_length=50,
                verbose_name='Tuition fees amount',
            ),
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='tuition_fees_amount',
            field=models.CharField(
                choices=[
                    ('INSCRIPTION_AU_ROLE', 'INSCRIPTION_AU_ROLE'),
                    ('INSCRIPTION_REGULIERE', 'INSCRIPTION_REGULIERE'),
                    ('NOUVEAUX_DROITS_MAJORES', 'NOUVEAUX_DROITS_MAJORES'),
                    ('ANCIENS_DROITS_MAJORES_2505', 'ANCIENS_DROITS_MAJORES_2505'),
                    ('ANCIENS_DROITS_MAJORES_4175', 'ANCIENS_DROITS_MAJORES_4175'),
                    ('AGREGATION', 'AGREGATION'),
                    ('MASTER_DE_SPECIALISATION_SANTE', 'MASTER_DE_SPECIALISATION_SANTE'),
                    ('CERTIFICAT_60_CREDITS', 'CERTIFICAT_60_CREDITS'),
                    ('PAS_DE_DROITS_D_INSCRIPTION', 'PAS_DE_DROITS_D_INSCRIPTION'),
                    ('AUTRE', 'AUTRE'),
                ],
                default='',
                max_length=50,
                verbose_name='Tuition fees amount',
            ),
        ),
        migrations.RunPython(
            code=update_admission_tuition_fees_amount_with_new_values,
            reverse_code=update_admission_tuition_fees_amount_with_old_values,
        ),
    ]
