# Generated by Django 3.2.25 on 2024-09-24 10:50

import django.contrib.postgres.fields
from django.db import migrations, models
from osis_mail_template import MailTemplateMigration

from admission.mail_templates import ADMISSION_EMAIL_SUPERVISION_MODIFICATION_DOCTORATE


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0236_parcours_doctoral_refactoring'),
    ]

    operations = [
        MailTemplateMigration(
            ADMISSION_EMAIL_SUPERVISION_MODIFICATION_DOCTORATE,
            {
                'en': "[OSIS] UCLouvain - follow up of your application - {admission_reference}",
                'fr-be': "[OSIS] UCLouvain - suivi de votre demande d'admission - {admission_reference}",
            },
            {
                'en': '''<p>Dear {candidate_first_name} {candidate_last_name},</p>

<p>Thank you for your enrolment application to the {training_title} - {training_acronym} programme for the {academic_year} academic year.</p>

<p>We note that some elements are missing.</p>

<p>Please modify your supervisory committee as follows:</p>

<p><strong>(texte à insérer par gestionnaire)</strong> via your online application dashboard: {admissions_link_front}.</p>

<p>Please request signatures for any additional supervisory committee members in the same way as when you compiled your application.</p>

<p>{sender_name} - {phd_committee}</p>
    ''',
                'fr-be': '''<p>Cher, Chère, Cher.ère, {candidate_first_name} {candidate_last_name},</p>

<p>Votre demande d'inscription au programme {training_title} - {training_acronym} pour l'année académique {academic_year} nous est bien parvenue et nous vous en remercions.</p>

<p>Après vérification, nous constatons qu'il manque encore certains éléments.</p>

<p>Veuillez modifier votre comité d’accompagnement de la manière suivante :</p>

<p><strong>(texte à insérer par gestionnaire)</strong>, obligatoirement via votre tableau de bord de votre demande en ligne : {admissions_link_front}.</p>

<p>Veuillez demander les signatures pour les éventuels membres du comité d’accompagnement ajoutés, en procédant de la même façon que lors de la constitution de votre dossier.</p>

<p>{sender_name} - {phd_committee}</p>
    ''',
            },
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='status',
            field=models.CharField(choices=[('EN_BROUILLON', 'In draft form'), ('EN_ATTENTE_DE_SIGNATURE', 'Waiting for signature'), ('CONFIRMEE', 'Application confirmed'), ('ANNULEE', 'Cancelled application'), ('TRAITEMENT_FAC', 'Processing by Fac'), ('A_COMPLETER_POUR_FAC', 'To be completed for Fac'), ('COMPLETEE_POUR_FAC', 'Completed for Fac'), ('RETOUR_DE_FAC', 'Feedback from Fac'), ('CA_A_COMPLETER', 'Support committee to be completed'), ('CA_EN_ATTENTE_DE_SIGNATURE', 'Support committee waiting for signature'), ('A_COMPLETER_POUR_SIC', 'To be completed for the Enrolment Office (SIC)'), ('COMPLETEE_POUR_SIC', 'Completed for SIC'), ('ATTENTE_VALIDATION_DIRECTION', 'Awaiting management approval'), ('CLOTUREE', 'Closed'), ('INSCRIPTION_AUTORISEE', 'Application accepted'), ('INSCRIPTION_REFUSEE', 'Application denied')], default='EN_BROUILLON', max_length=30),
        ),
        migrations.AlterField(
            model_name='doctorateworkinglist',
            name='admission_statuses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EN_BROUILLON', 'In draft form'), ('EN_ATTENTE_DE_SIGNATURE', 'Waiting for signature'), ('CONFIRMEE', 'Application confirmed'), ('ANNULEE', 'Cancelled application'), ('TRAITEMENT_FAC', 'Processing by Fac'), ('A_COMPLETER_POUR_FAC', 'To be completed for Fac'), ('COMPLETEE_POUR_FAC', 'Completed for Fac'), ('RETOUR_DE_FAC', 'Feedback from Fac'), ('CA_A_COMPLETER', 'Support committee to be completed'), ('CA_EN_ATTENTE_DE_SIGNATURE', 'Support committee waiting for signature'), ('A_COMPLETER_POUR_SIC', 'To be completed for the Enrolment Office (SIC)'), ('COMPLETEE_POUR_SIC', 'Completed for SIC'), ('ATTENTE_VALIDATION_DIRECTION', 'Awaiting management approval'), ('CLOTUREE', 'Closed'), ('INSCRIPTION_AUTORISEE', 'Application accepted'), ('INSCRIPTION_REFUSEE', 'Application denied')], max_length=30), blank=True, default=list, size=None, verbose_name='Admission statuses'),
        ),
        migrations.AlterField(
            model_name='workinglist',
            name='admission_statuses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EN_BROUILLON', 'In draft form'), ('EN_ATTENTE_DE_SIGNATURE', 'Waiting for signature'), ('FRAIS_DOSSIER_EN_ATTENTE', 'Pending application fee'), ('CONFIRMEE', 'Application confirmed'), ('EN_ATTENTE', 'On hold'), ('ANNULEE', 'Cancelled application'), ('A_COMPLETER_POUR_SIC', 'To be completed for the Enrolment Office (SIC)'), ('COMPLETEE_POUR_SIC', 'Completed for SIC'), ('TRAITEMENT_FAC', 'Processing by Fac'), ('CA_A_COMPLETER', 'Support committee to be completed'), ('A_COMPLETER_POUR_FAC', 'To be completed for Fac'), ('COMPLETEE_POUR_FAC', 'Completed for Fac'), ('RETOUR_DE_FAC', 'Feedback from Fac'), ('ATTENTE_VALIDATION_DIRECTION', 'Awaiting management approval'), ('INSCRIPTION_AUTORISEE', 'Application accepted'), ('INSCRIPTION_REFUSEE', 'Application denied'), ('CLOTUREE', 'Closed')], max_length=30), blank=True, default=list, size=None, verbose_name='Admission statuses'),
        ),
    ]
