# Generated by Django 4.2.16 on 2025-01-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0019_scholarship"),
        ("admission", "0236_parcours_doctoral_refactoring"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorateadmission",
            name="international_scholarship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reference.scholarship",
                verbose_name="International scholarship",
            ),
        ),
        migrations.AlterField(
            model_name="generaleducationadmission",
            name="double_degree_scholarship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reference.scholarship",
                verbose_name="Dual degree scholarship",
            ),
        ),
        migrations.AlterField(
            model_name="generaleducationadmission",
            name="erasmus_mundus_scholarship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reference.scholarship",
                verbose_name="Erasmus Mundus scholarship",
            ),
        ),
        migrations.AlterField(
            model_name="generaleducationadmission",
            name="international_scholarship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="reference.scholarship",
                verbose_name="International scholarship",
            ),
        ),
    ]
