# Generated by Django 4.2.16 on 2025-01-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0237_alter_admission_tuition_fees_amount"),
        ("admission", "0237_doctorate_supervision_mail_template"),
    ]

    operations = []
