# Generated by Django 4.2.16 on 2025-01-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0238_delete_scholarship"),
        ("admission", "0238_merge_20250117_1427"),
    ]

    operations = []
