# Generated by Django 4.2.16 on 2025-01-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0239_alter_onlinepayment_checkout_url"),
        ("admission", "0239_merge_20250127_1311"),
    ]

    operations = []
