# Generated by Django 4.2.16 on 2024-12-03 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0240_merge_20250127_1429"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorateadmission",
            name="related_pre_admission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="admission.doctorateadmission",
                verbose_name="Related pre-admission",
            ),
        ),
    ]
