# Generated by Django 4.2.16 on 2025-02-10 16:34

from django.db import migrations, models
from django.db.models import Case, Value, When

from base.models.enums.education_group_types import TrainingType


def initialize_last_signature_request_before_submission_at(apps, schema_editor):
    """Initialize the last_signature_request_before_submission_at field value with the submitted_at field value."""

    BaseAdmission = apps.get_model('admission', 'BaseAdmission')
    DoctorateAdmission = apps.get_model('admission', 'DoctorateAdmission')

    signature_date_by_admission_id = {
        admission.pk: admission.submitted_at
        for admission in BaseAdmission.objects.filter(
            training__education_group_type__name=TrainingType.PHD.name,
            submitted_at__isnull=False,
        )
    }

    DoctorateAdmission.objects.filter(baseadmission_ptr_id__in=signature_date_by_admission_id.keys()).update(
        last_signature_request_before_submission_at=Case(
            *[
                When(baseadmission_ptr_id=admission_id, then=Value(signature_date))
                for admission_id, signature_date in signature_date_by_admission_id.items()
            ],
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0242_alter_centralmanager_scopes"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorateadmission",
            name="last_signature_request_before_submission_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Last signature request before submission at",
            ),
        ),
        migrations.RunPython(
            code=initialize_last_signature_request_before_submission_at,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
