# Generated by Django 4.2.16 on 2025-02-06 16:40

from django.db import migrations, models
from django.db.models import Q


def update_doctorate_enums_values(apps, schema_editor):
    DoctorateAdmission = apps.get_model('admission', 'DoctorateAdmission')

    DoctorateAdmission.objects.filter(phd_already_done='PARTIAL').update(phd_already_done='YES')

    DoctorateAdmission.objects.filter(Q(proximity_commission='BCM') | Q(proximity_commission='GIM')).update(
        proximity_commission='BCGIM'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0243_doctorateadmission_last_signature_request_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorateadmission',
            name='program_planned_years_number',
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='phd_already_done',
            field=models.CharField(
                blank=True,
                choices=[('YES', 'YES'), ('NO', 'NO')],
                default='NO',
                max_length=255,
                verbose_name='PhD already done',
            ),
        ),
        migrations.AlterField(
            model_name='doctorateadmission',
            name='proximity_commission',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ECONOMY', 'ECONOMY'),
                    ('MANAGEMENT', 'MANAGEMENT'),
                    (
                        'ECLI',
                        'Proximity commission for experimental and clinical research (ECLI)',
                    ),
                    (
                        'BCGIM',
                        'Proximity commission for biochemistry, cellular and molecular biology, '
                        'genetics, immunology (BCGIM)',
                    ),
                    ('NRSC', 'Proximity Commission for Neuroscience (NRSC)'),
                    (
                        'SPSS',
                        'Proximity commission for public health, health and society (SPSS)',
                    ),
                    ('DENT', 'Proximity Commission for Dental Sciences (DENT)'),
                    ('DFAR', 'Proximity Commission for Pharmaceutical Sciences (DFAR)'),
                    ('MOTR', 'Proximity Commission for Motricity Sciences (MOTR)'),
                    ('PHYSICS', 'PHYSICS'),
                    ('CHEMISTRY', 'CHEMISTRY'),
                    ('MATHEMATICS', 'MATHEMATICS'),
                    ('STATISTICS', 'STATISTICS'),
                    ('BIOLOGY', 'BIOLOGY'),
                    ('GEOGRAPHY', 'GEOGRAPHY'),
                ],
                default="",
                max_length=255,
                verbose_name='Proximity commission',
            ),
        ),
        migrations.RunPython(code=update_doctorate_enums_values, reverse_code=migrations.RunPython.noop),
    ]
