# Generated by Django 4.2.16 on 2025-02-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0244_remove_doctorateadmission_program_planned_years_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounting",
            name="sport_affiliation",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "LOUVAIN_WOLUWE",
                        "Yes, in Louvain-la-Neuve and/or Woluwe-Saint-Lambert (E60)",
                    ),
                    ("MONS_UCL", "Yes, in Mons and other UCLouvain campuses (E60)"),
                    ("MONS", "Yes, only in Mons (E12)"),
                    (
                        "SAINT_GILLES_UCL",
                        "Yes, in Saint-Gilles and other UCLouvain campuses (E60)",
                    ),
                    ("SAINT_GILLES", "Yes, only in Saint-Gilles (E12)"),
                    (
                        "TOURNAI_UCL",
                        "Yes, in Tournai and other UCLouvain campuses (E60)",
                    ),
                    ("TOURNAI", "Yes, only in Tournai (E12)"),
                    (
                        "SAINT_LOUIS_UCL",
                        "Yes, in Saint-Louis and other UCLouvain campuses (E60)",
                    ),
                    ("SAINT_LOUIS", "Yes, only in Saint-Louis (free)"),
                    ("NON", "No"),
                ],
                default="",
                max_length=32,
                verbose_name="Sport affiliation",
            ),
        ),
    ]
