# Generated by Django 4.2.16 on 2025-03-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admission",
            "0244_remove_doctorateadmission_program_planned_years_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="financabilite_dispensation_vrae",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Financability VRAE dispensation",
            ),
        ),
    ]
