# Generated by Django 4.2.16 on 2025-03-18 15:27

from django.db import migrations, models

from admission.migrations.utils.initialize_has_scholarship_fields import (
    initialize_has_scholarship_fields,
)


def initialize_has_scholarship_fields_migration(apps, schema_editor):
    GeneralEducationAdmission = apps.get_model("admission", "GeneralEducationAdmission")
    initialize_has_scholarship_fields(admission_class=GeneralEducationAdmission)


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0246_doctorateadmission_approved_by_cdd_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="has_double_degree_scholarship",
            field=models.BooleanField(blank=True, null=True, verbose_name="Has dual degree scholarship"),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="has_erasmus_mundus_scholarship",
            field=models.BooleanField(blank=True, null=True, verbose_name="Has Erasmus Mundus scholarship"),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="has_international_scholarship",
            field=models.BooleanField(blank=True, null=True, verbose_name="Has international scholarship"),
        ),
        migrations.RunPython(
            code=initialize_has_scholarship_fields_migration,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
