# Generated by Django 4.2.16 on 2025-03-19 13:19

from django.db import migrations, models

from admission.ddd.admission.formation_generale.domain.model.enums import TypeDeRefus

PREVIOUS_VALUE = 'REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIESS'


def update_refusal_type_published_conditions_for_master(apps, schema_editor):
    GeneralEducationAdmission = apps.get_model('admission', 'GeneralEducationAdmission')

    GeneralEducationAdmission.objects.filter(refusal_type=PREVIOUS_VALUE).update(
        refusal_type=TypeDeRefus.REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER.name,
    )


def reverse_update_refusal_type_published_conditions_for_master(apps, schema_editor):
    GeneralEducationAdmission = apps.get_model('admission', 'GeneralEducationAdmission')

    GeneralEducationAdmission.objects.filter(
        refusal_type__in=[
            TypeDeRefus.REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER.name,
            TypeDeRefus.REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER_SPECIALISATION.name,
        ],
    ).update(refusal_type=PREVIOUS_VALUE)


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0247_generaleducationadmission_has_double_degree_scholarship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generaleducationadmission",
            name="refusal_type",
            field=models.CharField(
                choices=[
                    (
                        "REFUS_EQUIVALENCE",
                        "REFUS_EQUIVALENCE",
                    ),
                    (
                        "REFUS_BAC_HUE_ACADEMIQUE",
                        "REFUS_BAC_HUE_ACADEMIQUE",
                    ),
                    (
                        "REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER",
                        "REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER",
                    ),
                    (
                        "REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER_SPECIALISATION",
                        "REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER_SPECIALISATION",
                    ),
                    (
                        "REFUS_ARTICLE_95_JURY",
                        "REFUS_ARTICLE_95_JURY",
                    ),
                    (
                        "REFUS_ARTICLE_95_GENERIQUE_IRRECEVABILITE",
                        "REFUS_ARTICLE_95_GENERIQUE_IRRECEVABILITE",
                    ),
                    (
                        "REFUS_AGREGATION",
                        "REFUS_AGREGATION",
                    ),
                    (
                        "REFUS_ARTICLE_96_UE_HUE_ASSIMILES",
                        "REFUS_ARTICLE_96_UE_HUE_ASSIMILES",
                    ),
                    (
                        "REFUS_ARTICLE_96_HUE_RAISON_ACADEMIQUE",
                        "REFUS_ARTICLE_96_HUE_RAISON_ACADEMIQUE",
                    ),
                    (
                        "REFUS_DOSSIER_TARDIF",
                        "REFUS_DOSSIER_TARDIF",
                    ),
                    (
                        "REFUS_COMPLEMENT_TARDIF",
                        "REFUS_COMPLEMENT_TARDIF",
                    ),
                    (
                        "REFUS_ARTICLE_96_HUE_NON_PROGRESSION",
                        "REFUS_ARTICLE_96_HUE_NON_PROGRESSION",
                    ),
                    (
                        "REFUS_LIBRE",
                        "REFUS_LIBRE",
                    ),
                ],
                default="",
                max_length=64,
                verbose_name="Refusal type",
            ),
        ),
        migrations.RunPython(
            code=update_refusal_type_published_conditions_for_master,
            reverse_code=reverse_update_refusal_type_published_conditions_for_master,
        ),
    ]
