# Generated by Django 3.2.25 on 2024-07-08 15:17
from django.conf import settings
from django.db import migrations

from admission.management.commands.initialize_specific_questions import (
    SpecificContinuingQuestionToInit,
)
from admission.migrations.utils.apply_specific_questions_to_year import (
    apply_specific_questions_to_year,
)


def initialize_iufc_specific_questions_2025(apps, schema_editor):
    AdmissionFormItemInstantiation = apps.get_model('admission', 'AdmissionFormItemInstantiation')
    AcademicYear = apps.get_model('base', 'AcademicYear')

    if settings.TESTING:
        return

    apply_specific_questions_to_year(
        form_item_instantiation_model=AdmissionFormItemInstantiation,
        academic_year_model=AcademicYear,
        form_item_internal_labels=SpecificContinuingQuestionToInit.get_values(),
        from_year=2024,
        to_year=2025,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0249_generaleducationadmission_delegate_vrae_dispensation_and_more'),
    ]

    operations = [
        migrations.RunPython(code=initialize_iufc_specific_questions_2025, reverse_code=migrations.RunPython.noop),
    ]
