# Generated by Django 4.2.20 on 2025-04-14 15:57
from django.conf import settings
from django.db import migrations, models
from django.db.models import Max


def initialize_epc_injection_in_error_list(apps, schema_editor):
    ContinuingWorkingList = apps.get_model('admission', 'ContinuingWorkingList')

    order = ContinuingWorkingList.objects.aggregate(Max('order', default=0)).get('order__max', 0) + 1

    ContinuingWorkingList.objects.create(
        name={
            settings.LANGUAGE_CODE_FR: 'Dossiers EPC en erreur',
            settings.LANGUAGE_CODE_EN: 'Dossiers with EPC injection error',
        },
        order=order,
        epc_injection_in_error=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "admission",
            "0249_generaleducationadmission_delegate_vrae_dispensation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="continuingworkinglist",
            name="epc_injection_in_error",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="EPC injection in error",
            ),
        ),
        migrations.RunPython(code=initialize_epc_injection_in_error_list, reverse_code=migrations.RunPython.noop),
    ]
