# Generated by Django 4.2.20 on 2025-05-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0250_continuingworkinglist_epc_injection_in_error"),
        ("admission", "0250_generaleducationadmission_financabilite_dispensation_vrae"),
        ("admission", "0250_initialize_iufc_specific_questions_2025"),
    ]

    operations = []
