# Generated by Django 4.2.16 on 2024-12-05 15:21

from django.db import migrations, models


def remove_duplicate_roles(apps, schema_editor):
    CommitteeMember = apps.get_model("admission", "CommitteeMember")
    Promoter = apps.get_model("admission", "Promoter")

    for model_class in [CommitteeMember, Promoter]:
        members = model_class.objects.all()
        found_persons_ids = set()
        members_ids_to_delete = []

        for member in members:
            if member.person_id in found_persons_ids:
                members_ids_to_delete.append(member.pk)
            else:
                found_persons_ids.add(member.person_id)

        model_class.objects.filter(pk__in=members_ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0251_merge_20250505_0951"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_roles, reverse_code=migrations.RunPython.noop),
    ]
