# Generated by Django 4.2.16 on 2025-01-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0252_promoter_unique_constraint_data_migration"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="committeemember",
            constraint=models.UniqueConstraint(
                fields=("person",),
                name="admission_unique_committee_member_by_person",
            ),
        ),
        migrations.AddConstraint(
            model_name="promoter",
            constraint=models.UniqueConstraint(
                fields=("person",),
                name="admission_unique_promoter_by_person",
            ),
        ),
    ]
