# Generated by Django 4.2.20 on 2025-05-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0253_promoter_unique_constraint_data_structure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onlinepayment",
            name="payment_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
