# Generated by Django 4.2.20 on 2025-04-28 14:23

import django.contrib.postgres.fields
from django.db import migrations, models
from django.db.models import Case, F, Value, When

from admission.infrastructure.admission.shared_kernel.domain.service.annee_inscription_formation import (
    AnneeInscriptionFormationTranslator,
)
from admission.models.working_list import UNCHANGED_KEY


def update_working_lists(apps, schema_editor):
    WorkingList = apps.get_model("admission", "WorkingList")

    default_education_group_types = list(
        AnneeInscriptionFormationTranslator.GENERAL_EDUCATION_TYPES
        | AnneeInscriptionFormationTranslator.DOCTORATE_EDUCATION_TYPES
    )

    WorkingList.objects.update(
        admission_education_types=default_education_group_types,
        admission_type=Case(
            When(admission_type='', then=Value(UNCHANGED_KEY)),
            default=F('admission_type'),
        ),
    )


def reverse_update_working_lists(apps, schema_editor):
    WorkingList = apps.get_model("admission", "WorkingList")

    WorkingList.objects.update(
        admission_type=Case(
            When(admission_type=UNCHANGED_KEY, then=Value('')),
            default=F('admission_type'),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0253_promoter_unique_constraint_data_structure"),
    ]

    operations = [
        migrations.AddField(
            model_name="workinglist",
            name="admission_education_types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("BACHELOR", "Bachelor"),
                        ("MASTER_MC", "Master of specialist"),
                        ("MASTER_MA_120", "Master MA 120"),
                        ("MASTER_MD_120", "Master MD 120"),
                        ("MASTER_MS_120", "Master MS 120"),
                        ("MASTER_MS_180_240", "Master MS 180-240"),
                        ("MASTER_M1", "Master in 60 credits"),
                        ("MASTER_M4", "Master in 120 credits FIE section 4"),
                        ("MASTER_M5", "Master in 60 credits FIE section 5"),
                        ("AGGREGATION", "Aggregation"),
                        ("CAPAES", "CAPAES"),
                        ("CERTIFICATE", "Certificate"),
                        ("CERTIFICATE_OF_PARTICIPATION", "Certificate of participation"),
                        ("CERTIFICATE_OF_SUCCESS", "Certificate of success"),
                        ("UNIVERSITY_FIRST_CYCLE_CERTIFICATE", "University first cycle certificate"),
                        ("UNIVERSITY_SECOND_CYCLE_CERTIFICATE", "University second cycle certificate"),
                        ("PHD", "Ph.D"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=list,
                size=None,
                verbose_name="Admission education types",
            ),
        ),
        migrations.AlterField(
            model_name="workinglist",
            name="admission_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "All"),
                    ("INCHANGE", "INCHANGE"),
                    ("ADMISSION", "ADMISSION"),
                    ("INSCRIPTION", "INSCRIPTION"),
                ],
                default="",
                max_length=16,
                verbose_name="Admission type",
            ),
        ),
        migrations.RunPython(code=update_working_lists, reverse_code=reverse_update_working_lists),
    ]
