# Generated by Django 4.2.16 on 2025-03-19 13:19

from django.db import migrations
from django.db.models import QuerySet

from admission.ddd.admission.formation_generale.domain.model.enums import (
    ChoixStatutChecklist,
)


def update_checklist_specific_info_insufficient(apps, schema_editor):
    BaseAdmission = apps.get_model('admission', 'BaseAdmission')

    admissions: QuerySet[BaseAdmission] = BaseAdmission.objects.filter(
        checklist__current__specificites_formation__statut=ChoixStatutChecklist.GEST_BLOCAGE.name,
    )

    for admission in admissions:
        admission.checklist['current']['specificites_formation']['extra']['insufficient'] = '1'

    BaseAdmission.objects.bulk_update(admissions, fields=['checklist'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0253_promoter_unique_constraint_data_structure"),
    ]

    operations = [
        migrations.RunPython(
            code=update_checklist_specific_info_insufficient,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
