# Generated by Django 4.2.20 on 2025-04-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0254_alter_onlinepayment_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseadmission",
            name="is_exam_access_title",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Is the exam the access title for this admission?",
            ),
        ),
    ]
