# Generated by Django 4.2.20 on 2025-05-16 14:32

from django.db import migrations


def remove_email_templates(apps, _):
    templates_to_delete = [
        'osis-admission-cdd-refusal-doctorate',
    ]
    MailTemplate = apps.get_model('osis_mail_template', 'MailTemplate')
    MailTemplate.objects.filter(identifier__in=templates_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0255_doctoraterefusalreasoncategory_and_more"),
    ]

    operations = [
        migrations.RunPython(code=remove_email_templates, reverse_code=migrations.RunPython.noop),
    ]
