# Generated by Django 3.2.23 on 2024-02-15 14:33

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from admission.mail_templates import ADMISSION_EMAIL_SIC_REFUSAL_DOCTORATE


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0256_remove_doctorate_cdd_refusal_email'),
    ]

    operations = [
        MailTemplateMigration(
            ADMISSION_EMAIL_SIC_REFUSAL_DOCTORATE,
            subjects={
                'en': "UCLouvain - inscription application {admission_reference} follow-up",
                'fr-be': "UCLouvain - suivi de votre demande d'inscription - {admission_reference}",
            },
            contents={
                'en': '''<p>{greetings} {candidate_first_name} {candidate_last_name},</p>
        <p>Thank you for your inscription application to the {training_acronym} / {training_title} programme
          for the {academic_year} academic year.</p>
        <p>After evaluating your application, we regret to inform you that your application for inscription
          has not been accepted.</p>
        <p>To be aware of the reasons, <strong>we invite you to download
        <a href="{document_link}">your letter of inadmissibility</a>
        and keep it</strong>. This link will be valid for 1 year from today.</p>

        <p>{sender_name} - {doctoral_commission}</p>
        ''',
                'fr-be': '''<p>{greetings} {candidate_first_name} {candidate_last_name},</p>
        <p>Votre demande d'inscription à l'année académique {academic_year} au programme {training_acronym} / {training_title}
          nous est bien parvenue et nous vous en remercions.</p>
        <p>Après analyse de votre dossier, nous sommes au regret de vous informer que votre demande d'inscription n'a
          pu faire l'objet d'une réponse favorable.</p>
        <p>Pour prendre connaissances des motifs, <strong>nous vous invitons à télécharger
        <a href="{document_link}">votre courrier d’irrecevabilité</a>
        et à le conserver</strong>. Ce lien sera valide pendant 1 an à dater de ce jour.</p>

        <p>{sender_name} - {doctoral_commission}</p>
        ''',
            },
        ),
    ]
