# Generated by Django 4.2.20 on 2025-05-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0254_alter_onlinepayment_payment_id"),
        ("admission", "0254_update_checklist_specific_info_insufficient"),
        ("admission", "0256_remove_doctorate_cdd_refusal_email"),
    ]

    operations = []
