# Generated by Django 4.2.20 on 2025-05-21 15:28

import osis_document_components.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0257_doctorate_sic_refusal_mail_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorateadmission",
            name="sic_refusal_certificate",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Refusal certificate from SIC",
            ),
        ),
    ]
