# Generated by Django 4.2.20 on 2025-05-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0257_merge_20250530_1042"),
        ("admission", "0258_doctorateadmission_sic_refusal_certificate"),
    ]

    operations = []
