# Generated by Django 4.2.20 on 2025-04-25 17:39

import osis_document_components.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admission",
            "0260_alter_doctorateadmission_financability_computed_rule_situation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="regular_registration_proof_for_registration_change",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=1,
                verbose_name="Proof of regular registration for registration change",
            ),
        ),
    ]
