# Generated by Django 4.2.20 on 2025-06-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0254_workinglist_admission_education_group_and_more"),
        ("admission", "0254_alter_generaleducationadmission_refusal_type"),
        (
            "admission",
            "0261_generaleducationadmission_regular_registration_proof_for_registration_change",
        ),
    ]

    operations = []
