# Generated by Django 4.2.20 on 2025-06-02 18:39

import django.db.models.deletion
from django.db import migrations, models


def remove_old_doctorate_readers(apps, schema_editor):
    DoctorateReader = apps.get_model('admission', 'DoctorateReader')
    DoctorateReader.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0711_delete_etatfinancabilite2023"),
        (
            "admission",
            "0261_generaleducationadmission_regular_registration_proof_for_registration_change",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="doctoratereader",
            name="education_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="base.educationgroup",
                null=True,
            ),
        ),
        migrations.RunPython(
            code=remove_old_doctorate_readers,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
