# Generated by Django 4.2.20 on 2025-06-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0254_alter_generaleducationadmission_refusal_type"),
        ("admission", "0262_merge_20250610_1440"),
    ]

    operations = []
