# Generated by Django 4.2.20 on 2025-06-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0711_delete_etatfinancabilite2023"),
        ("admission", "0262_doctoratereader_education_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctoratereader",
            name="education_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="base.educationgroup",
            ),
        ),
    ]
