# Generated by Django 4.2.20 on 2025-06-16 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0262_update_determined_academic_year'),
        ('admission', '0263_merge_20250611_1348'),
    ]

    operations = [
    ]
