# Generated by Django 4.2.20 on 2025-06-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0255_baseadmission_is_exam_access_title"),
        ("admission", "0264_merge_20250616_1717"),
    ]

    operations = []
