# Generated by Django 4.2.20 on 2025-06-06 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0711_delete_etatfinancabilite2023"),
        ("admission", "0265_merge_20250618_0859"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorateCommitteeMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "education_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.educationgroup",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role: Doctorate committee member",
                "verbose_name_plural": "Role: Doctorate committee members",
            },
        ),
        migrations.DeleteModel(
            name="DoctorateReader",
        ),
    ]
