# Generated by Django 4.2.20 on 2025-05-12 16:01

from django.db import migrations, models

from admission.migrations.utils.initialize_requested_documents_deadline import (
    initialize_requested_documents_deadline,
)


def initialize_requested_documents_deadline_code(apps, schema_editor):
    BaseAdmission = apps.get_model('admission', 'BaseAdmission')
    initialize_requested_documents_deadline(model_class=BaseAdmission)


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0267_alter_generaleducationadmission_refusal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseadmission",
            name="requested_documents_deadline",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Requested documents deadline",
            ),
        ),
        migrations.RunPython(
            code=initialize_requested_documents_deadline_code,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
