# Generated by Django 4.2.20 on 2025-08-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0714_sicmanagement'),
        ('admission', '0268_baseadmission_requested_documents_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSicManagement',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('base.sicmanagement',),
        ),
        migrations.DeleteModel(
            name='SicManagement',
        ),
    ]
