# Generated by Django 4.2.20 on 2025-07-17 16:12

from django.db import migrations
from osis_mail_template import MailTemplateMigration

from admission.mail_templates.signatures import (
    ADMISSION_EMAIL_SIGNATURE_CANDIDATE_APPROVAL,
    ADMISSION_EMAIL_SIGNATURE_CANDIDATE_REFUSAL,
    ADMISSION_EMAIL_SIGNATURE_REQUESTS_PROMOTER,
)


def delete_old_template(apps, schema_editor):
    MailTemplate = apps.get_model('osis_mail_template', 'MailTemplate')
    MailTemplate.objects.filter(identifier='osis-admission-signature-candidate').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0269_admissionsicmanagement_delete_sicmanagement"),
    ]

    operations = [
        migrations.RunPython(delete_old_template, reverse_code=migrations.RunPython.noop),
        MailTemplateMigration(
            ADMISSION_EMAIL_SIGNATURE_CANDIDATE_APPROVAL,
            {
                'en': '[OSIS] Answer from {signataire_first_name} {signataire_last_name} for {training_title}',
                'fr-be': '[OSIS] Réponse de {signataire_first_name} {signataire_last_name} pour un {training_title}',
            },
            {
                'en': '''<p>Hello {candidate_first_name} {candidate_last_name},</p>

    <p>{signataire_first_name} {signataire_last_name} ({signataire_role}) has answered your request for {training_title}
    with the following : Approved.</p>

    <p>---<br/>
    The OSIS Team</p>
    ''',
                'fr-be': '''<p>Bonjour {candidate_first_name} {candidate_last_name},</p>

    <p>{signataire_first_name} {signataire_last_name} ({signataire_role}) a répondu à votre demande de {training_title}
    avec ce qui suit : Approuvée.</p>

    <p>---<br/>
    L'équipe OSIS</p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_SIGNATURE_CANDIDATE_REFUSAL,
            {
                'en': '[OSIS] Answer from {signataire_first_name} {signataire_last_name} for {training_title}',
                'fr-be': '[OSIS] Réponse de {signataire_first_name} {signataire_last_name} pour un {training_title}',
            },
            {
                'en': '''<p>Hello {candidate_first_name} {candidate_last_name},</p>

    <p>{signataire_first_name} {signataire_last_name} ({signataire_role}) has answered your request for {training_title}
    with the following : Denied.</p>

    <p>---<br/>
    The OSIS Team</p>
    ''',
                'fr-be': '''<p>Bonjour {candidate_first_name} {candidate_last_name},</p>

    <p>{signataire_first_name} {signataire_last_name} ({signataire_role}) a répondu à votre demande de {training_title}
    avec ce qui suit : Rejetée.</p>

    <p>---<br/>
    L'équipe OSIS</p>
    ''',
            },
        ),
        MailTemplateMigration(
            ADMISSION_EMAIL_SIGNATURE_REQUESTS_PROMOTER,
            {
                'en': '[OSIS] Invite to supervise {candidate_first_name} {candidate_last_name} for {training_title}',
                'fr-be': '[OSIS] Invitation à superviser {candidate_first_name} {candidate_last_name} '
                'pour un {training_title}',
            },
            {
                'en': '''<p>Hello {signataire_first_name} {signataire_last_name},</p>

    <p>{candidate_first_name} {candidate_last_name} has added you as {signataire_role} for {training_title}.</p>

    <p>Please indicate your approval or refusal and view the admission request by clicking
    on the {admission_link_front} link.</p>

    <p>---<br/>
    The OSIS Team</p>
    ''',
                'fr-be': '''<p>Bonjour {signataire_first_name} {signataire_last_name},</p>

    <p>{candidate_first_name} {candidate_last_name} vous a ajouté en tant que {signataire_role}
    pour son {training_title}.</p>

    <p>Merci d'indiquer votre approbation ou refus et visualiser sa demande en cliquer sur le lien {admission_link_front}.

    <p>---<br/>
    L'équipe OSIS</p>
    ''',
            },
        ),
    ]
