# Generated by Django 4.2.25 on 2025-10-27 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("osis_profile", "0033_initialize_exams"),
        ("admission", "0271_doctorate_manager_submission_mail_template"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionExam",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam",
                        to="admission.baseadmission",
                        verbose_name="Admission",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admissions",
                        to="osis_profile.exam",
                        verbose_name="Exam",
                    ),
                ),
            ],
        ),
    ]
