# Generated by Django 4.2.25 on 2025-11-03 13:01
import datetime

from django.db import migrations, models


def populate_changed(apps, schema_editor):
    Accounting = apps.get_model('admission', 'Accounting')
    Accounting.objects.all().update(changed=datetime.datetime.now())


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0272_admissionexam'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='changed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(populate_changed),
    ]
