# Generated by Django 4.2.25 on 2025-11-04 18:08

from django.db import migrations, models
import osis_document_components.fields

RESIDENT_STUDENT_FORM = "Dossier résident - contingentement"
RESIDENCE_CERTIFICATE = "Certificat de résidence"
PASS_LAS = "PASS et LAS"


def migrate_specific_questions(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0273_accounting_changed"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_file",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Non-resident file",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_with_second_year_enrolment",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Do you intend to make an enrolment directly for the second year ?",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_with_second_year_enrolment_form",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Non-resident enrolment form for an enrolment beyond the first 60 credits",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="residence_certificate",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Residence certificate",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="residence_student_form",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Resident student form",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="resident_competitive_entrance_examination",
            field=models.CharField(
                choices=[
                    ("JAMAIS", "JAMAIS"),
                    ("UNE_FOIS", "UNE"),
                    ("DEUX_FOIS_OU_PLUS", "DEUX_OU_PLUS"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.RunPython(migrate_specific_questions)
    ]
