# Generated by Django 5.2.8 on 2025-11-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0274_remove_baseadmission_specific_question_answers_and_more'),
        ('base', '0720_rename_educationgroupyear_acronym_academic_year_base_educat_acronym_c47631_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='prerequisite_courses',
            field=models.ManyToManyField(blank=True, through='admission.DoctorateAdmissionPrerequisiteCourses', through_fields=('admission', 'course'), to='base.learningunityear', verbose_name='Prerequisite courses'),
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='prerequisite_courses',
            field=models.ManyToManyField(blank=True, through='admission.AdmissionPrerequisiteCourses', through_fields=('admission', 'course'), to='base.learningunityear', verbose_name='Prerequisite courses'),
        ),
    ]
