# Generated by Django 4.2.25 on 2025-11-04 18:08

from django.db import migrations, models
import osis_document_components.fields
from django.db.models import Subquery, F, OuterRef, Case, When, Value
from django.db.models.functions import Coalesce

RESIDENT_STUDENT_FORM = "Dossier résident - contingentement"
RESIDENCE_CERTIFICATE = "Certificat de résidence"
PASS_LAS = "PASS et LAS"

SIGLES_WITH_QUOTA = ['KINE1BA', 'VETE1BA', 'LOGO1BA']


def migrate_specific_questions(apps, schema_editor):
    AdmissionFormItem = apps.get_model("admission", "AdmissionFormItem")
    GeneralEducationAdmission = apps.get_model("admission", "GeneralEducationAdmission")
    SpecificQuestionAnswer = apps.get_model("admission", "SpecificQuestionAnswer")

    internal_labels = [RESIDENT_STUDENT_FORM, RESIDENCE_CERTIFICATE, PASS_LAS]
    AdmissionFormItem.objects.filter(internal_label__in=internal_labels).update(active=False)

    GeneralEducationAdmission.objects.order_by().filter(
        baseadmission_ptr__training__acronym__in=SIGLES_WITH_QUOTA,
    ).annotate(
        residence_certificate_answer=Subquery(SpecificQuestionAnswer.objects.filter(
            admission=OuterRef("pk"),
            form_item__internal_label=RESIDENCE_CERTIFICATE,
        ).values('file')[:1]),
        resident_competitive_entrance_examination_answer=Subquery(SpecificQuestionAnswer.objects.filter(
            admission=OuterRef("pk"),
            form_item__internal_label=PASS_LAS,
        ).values('answer')[:1]),
        residence_student_form_answer=Subquery(SpecificQuestionAnswer.objects.filter(
            admission=OuterRef("pk"),
            form_item__internal_label=RESIDENT_STUDENT_FORM,
        ).values('file')[:1]),
    ).update(
        residence_certificate=Coalesce(F('residence_certificate_answer'), Value([])),
        resident_competitive_entrance_examination=Case(
            When(resident_competitive_entrance_examination_answer=0, then=Value('JAMAIS')),
            When(resident_competitive_entrance_examination_answer=1, then=Value('UNE_FOIS')),
            When(resident_competitive_entrance_examination_answer=2, then=Value('DEUX_FOIS_OU_PLUS')),
            default=Value(''),
        ),
        residence_student_form=Coalesce(F('residence_student_form_answer'), Value([])),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0274_remove_baseadmission_specific_question_answers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_file",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Non-resident file",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_with_second_year_enrolment",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Do you intend to make an enrolment directly for the second year ?",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_with_second_year_enrolment_form",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Non-resident enrolment form for an enrolment beyond the first 60 credits",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="residence_certificate",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Residence certificate",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="residence_student_form",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Resident student form",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="resident_competitive_entrance_examination",
            field=models.CharField(
                choices=[
                    ("JAMAIS", "JAMAIS"),
                    ("UNE_FOIS", "UNE"),
                    ("DEUX_FOIS_OU_PLUS", "DEUX_OU_PLUS"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.RunPython(migrate_specific_questions)
    ]
