# Generated by Django 4.2.25 on 2025-10-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0275_alter_doctorateadmission_prerequisite_courses_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorateadmission",
            name="tuition_fees_amount",
            field=models.CharField(
                choices=[
                    ("INSCRIPTION_AU_ROLE", "INSCRIPTION_AU_ROLE"),
                    ("INSCRIPTION_REGULIERE", "INSCRIPTION_REGULIERE"),
                    ("NOUVEAUX_DROITS_MAJORES", "NOUVEAUX_DROITS_MAJORES"),
                    ("ANCIENS_DROITS_MAJORES_2505", "ANCIENS_DROITS_MAJORES_2505"),
                    ("ANCIENS_DROITS_MAJORES_4175", "ANCIENS_DROITS_MAJORES_4175"),
                    ("AGREGATION", "AGREGATION"),
                    (
                        "MASTER_DE_SPECIALISATION_SANTE",
                        "MASTER_DE_SPECIALISATION_SANTE",
                    ),
                    ("CERTIFICAT_60_CREDITS", "CERTIFICAT_60_CREDITS"),
                    ("PAS_DE_DROITS_D_INSCRIPTION", "PAS_DE_DROITS_D_INSCRIPTION"),
                    ("CO_DIPLOMATION_901", "CO_DIPLOMATION_901"),
                    ("CO_DIPLOMATION_132", "CO_DIPLOMATION_132"),
                    ("AUTRE", "AUTRE"),
                ],
                default="",
                max_length=50,
                verbose_name="Tuition fees amount",
            ),
        ),
        migrations.AlterField(
            model_name="generaleducationadmission",
            name="tuition_fees_amount",
            field=models.CharField(
                choices=[
                    ("INSCRIPTION_AU_ROLE", "INSCRIPTION_AU_ROLE"),
                    ("INSCRIPTION_REGULIERE", "INSCRIPTION_REGULIERE"),
                    ("NOUVEAUX_DROITS_MAJORES", "NOUVEAUX_DROITS_MAJORES"),
                    ("ANCIENS_DROITS_MAJORES_2505", "ANCIENS_DROITS_MAJORES_2505"),
                    ("ANCIENS_DROITS_MAJORES_4175", "ANCIENS_DROITS_MAJORES_4175"),
                    ("AGREGATION", "AGREGATION"),
                    (
                        "MASTER_DE_SPECIALISATION_SANTE",
                        "MASTER_DE_SPECIALISATION_SANTE",
                    ),
                    ("CERTIFICAT_60_CREDITS", "CERTIFICAT_60_CREDITS"),
                    ("PAS_DE_DROITS_D_INSCRIPTION", "PAS_DE_DROITS_D_INSCRIPTION"),
                    ("CO_DIPLOMATION_901", "CO_DIPLOMATION_901"),
                    ("CO_DIPLOMATION_132", "CO_DIPLOMATION_132"),
                    ("AUTRE", "AUTRE"),
                ],
                default="",
                max_length=50,
                verbose_name="Tuition fees amount",
            ),
        ),
    ]
