# Generated by Django 5.2.8 on 2025-11-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0272_alter_doctorateadmission_tuition_fees_amount_and_more"),
        ("admission", "0275_alter_doctorateadmission_prerequisite_courses_and_more"),
    ]

    operations = []
