# Generated by Django 5.2.8 on 2025-12-04 16:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0277_generaleducationadmission_non_resident_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centralmanager",
            name="scopes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("GENERAL", "GENERAL"),
                        ("IUFC", "IUFC"),
                        ("DOCTORAT", "DOCTORAT"),
                        ("CONTINGENTE_NON_RESIDENT", "CONTINGENTE_NON_RESIDENT"),
                    ],
                    max_length=200,
                ),
                blank=True,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="LimitedEnrolmentDelegate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role: Limited enrolment delegate",
                "verbose_name_plural": "Role: Limited enrolment delegate",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person",),
                        name="admission_unique_limited_enrolment_delegate_by_person",
                    )
                ],
            },
        ),
    ]
