# Generated by Django 5.2.8 on 2025-12-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0278_alter_centralmanager_scopes_limitedenrolmentdelegate"),
        ("base", "0722_alter_academiccalendar_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContingenteTraining",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_import",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last import at"
                    ),
                ),
                (
                    "last_bulk_notification",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last bulk notification at"
                    ),
                ),
                (
                    "training",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.educationgroupyear",
                        verbose_name="Training",
                    ),
                ),
            ],
        ),
    ]
