# Generated by Django 4.2.24 on 2025-10-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0717_update_dates_calendrier_academique"),
        ("admission", "0279_doctorate_faculty_decision_emails"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="doctoratecommitteemember",
            unique_together={("person", "education_group")},
        ),
    ]
