# Generated by Django 5.2.8 on 2025-12-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0279_contingentetraining"),
    ]

    operations = [
        migrations.AddField(
            model_name="contingentetraining",
            name="places_number",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Number of places"
            ),
        ),
    ]
