# Generated by Django 5.2.8 on 2025-12-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0279_doctorate_faculty_decision_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="continuingworkinglist",
            name="quarantine",
            field=models.BooleanField(null=True, verbose_name="Quarantine"),
        ),
    ]
