# Generated by Django 5.2.8 on 2025-12-10 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0280_contingentetraining_places_number"),
        ("base", "0722_alter_academiccalendar_reference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contingentetraining",
            name="last_bulk_notification",
        ),
        migrations.RemoveField(
            model_name="contingentetraining",
            name="last_import",
        ),
        migrations.AddField(
            model_name="contingentetraining",
            name="last_bulk_notification_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Last bulk notification at"
            ),
        ),
        migrations.AddField(
            model_name="contingentetraining",
            name="last_bulk_notification_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="base.person",
                verbose_name="Last bulk notification by",
            ),
        ),
        migrations.AddField(
            model_name="contingentetraining",
            name="last_import_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Last import at"
            ),
        ),
        migrations.AddField(
            model_name="contingentetraining",
            name="last_import_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="base.person",
                verbose_name="Last import by",
            ),
        ),
        migrations.AlterField(
            model_name="contingentetraining",
            name="training",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.educationgroupyear",
                verbose_name="Training",
            ),
        ),
    ]
