# Generated by Django 5.2.9 on 2026-01-16 12:31
import itertools

import django.db.models.deletion
from django.db import migrations, models, transaction
from django.db.models import Q, Case, When

from osis_profile.models.enums.experience_validation import EtatAuthentificationParcours, \
    ChoixStatutValidationExperience


def extract_experience_checklist(apps, schema_editor):
    BaseAdmission = apps.get_model('base', 'Admission')
    SecondaryStudies = apps.get_model('osis_profile', 'SecondaryStudies')
    Exam = apps.get_model('osis_profile', 'Exam')
    EducationalExperience = apps.get_model('osis_profile', 'EducationalExperience')
    ProfessionalExperience = apps.get_model('osis_profile', 'ProfessionalExperience')

    checklist_condition = Q(
        checklist__current__parcours_anterieur__enfants__contains={'statut': 'GEST_REUSSITE'},
    )

    for state in EtatAuthentificationParcours:
        checklist_condition |= Q(
            checklist__current__parcours_anterieur__enfants__contains={
                'extra': {'etat_authentification': state}
            }
        )


    admissions = BaseAdmission.objects.filter(
        checklist__current__parcours_anterieur__enfants__len__gt=0,
    ).filter(checklist_condition).only('candidate_id', 'checklist')

    valid_status = ChoixStatutValidationExperience.VALIDEE.name
    validated_experiences_uuids = []
    candidates_ids_with_validated_secondary_studies = []

    experiences_uuids_by_authentication_status = {}
    candidates_ids_by_authentication_status_secondary_studies = {}

    for authentication_state in EtatAuthentificationParcours:
        experiences_uuids_by_authentication_status[authentication_state.name] = []
        candidates_ids_by_authentication_status_secondary_studies[authentication_state.name] = []

    for admission in admissions:
        for experience_checklist in admission.checklist['current']['parcours_anterieur']['enfants']:
            if experience_checklist.get('identifiant') == 'ETUDES_SECONDAIRES':

                if experience_checklist.get('statut') == 'GEST_REUSSITE':
                    candidates_ids_with_validated_secondary_studies.append(admission.candidate_id)

                if experience_checklist.get('extra', {}).get('etat_authentification') and experience_checklist['extra']['etat_authentification'] != EtatAuthentificationParcours.NON_CONCERNE.name:
                    candidates_ids_by_authentication_status_secondary_studies[experience_checklist['extra']['etat_authentification']].append(admission.candidate_id)

            elif experience_checklist.get('identifiant'):
                if experience_checklist.get('statut') == 'GEST_REUSSITE':
                    validated_experiences_uuids.append(experience_checklist['identifiant'])

                if experience_checklist.get('extra', {}).get('etat_authentification'):
                    experiences_uuids_by_authentication_status[experience_checklist['extra']['etat_authentification']].append(experience_checklist['identifiant'])

    all_candidates_ids_for_authenticated_secondary_studies = []
    authenticated_secondary_studies_conditions = []

    for status, person_ids in candidates_ids_by_authentication_status_secondary_studies.items():
        if person_ids:
            all_candidates_ids_for_authenticated_secondary_studies.extend(person_ids)
            authenticated_secondary_studies_conditions.append(When(person_id__in=person_ids, then=status))

    all_authenticated_experiences_uuids = []
    authenticated_experiences_conditions = []

    for status, experience_uuids in experiences_uuids_by_authentication_status.items():
        if experience_uuids:
            all_authenticated_experiences_uuids.extend(experience_uuids)
            authenticated_experiences_conditions.append(When(person_id__in=experience_uuids, then=status))

    with transaction.atomic():
        SecondaryStudies.objects.filter(
            person_id__in=candidates_ids_with_validated_secondary_studies
        ).update(
            validation_status=valid_status
        )

        SecondaryStudies.objects.filter(
            person_id__in=all_candidates_ids_for_authenticated_secondary_studies
        ).update(
            authentification_status=Case(
                *[When(person_id__in=person_ids, then=status) for status, person_ids in candidates_ids_by_authentication_status_secondary_studies.items()]
            )
        )

        Exam.objects.filter(
            uuid__in=validated_experiences_uuids
        ).update(
            validation_status=valid_status
        )

        EducationalExperience.filter(
            uuid__in=validated_experiences_uuids
        ).update(
            validation_status=valid_status
        )

        ProfessionalExperience.filter(
            uuid__in=validated_experiences_uuids
        ).update(
            validation_status=valid_status
        )

        Exam.objects.filter(
            uuid__in=all_authenticated_experiences_uuids
        ).update(
            authentication_status=authenticated_experiences_conditions
        )

        EducationalExperience.filter(
            uuid__in=all_authenticated_experiences_uuids
        ).update(
            authentication_status=authenticated_experiences_conditions
        )

        ProfessionalExperience.filter(
            uuid__in=all_authenticated_experiences_uuids
        ).update(
            authentication_status=authenticated_experiences_conditions
        )


def reverse_extract_experience_checklist(apps, schema_editor):
    BaseAdmission = apps.get_model('base', 'Admission')
    SecondaryStudies = apps.get_model('osis_profile', 'SecondaryStudies')
    Exam = apps.get_model('osis_profile', 'Exam')
    EducationalExperience = apps.get_model('osis_profile', 'EducationalExperience')
    ProfessionalExperience = apps.get_model('osis_profile', 'ProfessionalExperience')


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0280_alter_doctoratecommitteemember_unique_together"),
        ("osis_profile", "0038_belgianhighschooldiploma_authentification_status_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=extract_experience_checklist,
            reverse_code=reverse_extract_experience_checklist,
        )
    ]
