# Generated by Django 4.2.25 on 2025-11-04 18:08

import osis_document_components.fields
from django.db import migrations, models
from django.db.models import Case, F, OuterRef, Subquery, Value, When
from django.db.models.functions import Coalesce
from osis_mail_template import MailTemplateMigration

RESIDENT_STUDENT_FORM = "Dossier résident - contingentement"
RESIDENCE_CERTIFICATE = "Certificat de résidence"

SIGLES_WITH_QUOTA = ['KINE1BA', 'VETE1BA', 'LOGO1BA']


def migrate_specific_questions(apps, schema_editor):
    AdmissionFormItem = apps.get_model("admission", "AdmissionFormItem")
    GeneralEducationAdmission = apps.get_model("admission", "GeneralEducationAdmission")
    SpecificQuestionAnswer = apps.get_model("admission", "SpecificQuestionAnswer")

    internal_labels = [RESIDENT_STUDENT_FORM, RESIDENCE_CERTIFICATE]
    AdmissionFormItem.objects.filter(internal_label__in=internal_labels).update(active=False)

    GeneralEducationAdmission.objects.order_by().filter(
        baseadmission_ptr__training__acronym__in=SIGLES_WITH_QUOTA,
    ).annotate(
        residence_certificate_answer=Subquery(
            SpecificQuestionAnswer.objects.filter(
                admission=OuterRef("pk"),
                form_item__internal_label=RESIDENCE_CERTIFICATE,
            ).values('file')[:1]
        ),
        residence_student_form_answer=Subquery(
            SpecificQuestionAnswer.objects.filter(
                admission=OuterRef("pk"),
                form_item__internal_label=RESIDENT_STUDENT_FORM,
            ).values('file')[:1]
        ),
    ).update(
        residence_certificate=Coalesce(F('residence_certificate_answer'), Value([])),
        residence_student_form=Coalesce(F('residence_student_form_answer'), Value([])),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0280_alter_doctoratecommitteemember_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_file",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Non-resident file",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_with_second_year_enrolment",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Do you intend to make an enrolment directly for the second year?",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_with_second_year_enrolment_form",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Non-resident enrolment form for an enrolment beyond the first 60 credits",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="residence_certificate",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Residence certificate",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="residence_student_form",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Resident student form",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="ares_application_number",
            field=models.CharField(
                default="",
                editable=False,
                max_length=30,
                verbose_name="Ares application number for trainings with quota",
            ),
        ),
        migrations.AddConstraint(
            model_name="generaleducationadmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ares_application_number", ""), _negated=True),
                fields=("ares_application_number",),
                name="unique_admission_general_education_ares_application_number",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="quota_admission_receipt",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Quota admission receipt",
            ),
        ),
        MailTemplateMigration(
            'osis-admission-contingente-soumission',
            {
                'en': '',
                'fr-be': "[OSIS] Dépôt d'un dossier non-résident pour une formation contingentée {ares_application_number}",
            },
            {
                'en': '',
                'fr-be': '''<p>Madame, Monsieur,</p>
<p>Nous accusons bonne réception du dépôt de votre dossier « non-résident » en version digitale,
pour l'une des formations contingentées : {training_title}.</p>
<p>Veuillez télécharger votre accusé de réception officiel.</p>
<p style="text-align: center; padding-top: 5px; padding-bottom: 10px;">
    <span style="color: #dc3545; border: 1px solid #dc3545; padding: 10px; border-radius: 10px;">
        Télécharger :
        <a
            href="{receipt_document_link}"
            target="_blank"
            style="color: #dc3545;"
        >Accusé de réception</a>
    </span>
</p>
<p>Cet accusé reprend votre numéro de dossier qui sera utilisé pour le tirage au sort.</p>
<p>Veillez donc à le conserver précieusement.</p>
<p>Pour plus d'informations sur les modalités qui encadrent ces études contingentées (dates du tirage au sort,
communication des résultats, ...), nous vous invitons à consulter la page
<a href="https://uclouvain.be/fr/etudier/inscriptions/etudes-contingentees.html">https://uclouvain.be/fr/etudier/inscriptions/etudes-contingentees.html</a>
qui sera mise à jour à chaque nouvelle étape de la procédure.</p>
<p>Nous vous remercions d'avoir choisi notre Institution.</p>
<p>Le Service des inscriptions de l'UCLouvain</p>
                    ''',
            },
        ),
        migrations.RunPython(migrate_specific_questions),
    ]
