# Generated by Django 5.2.8 on 2025-12-05 10:52

import osis_document_components.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0280_continuingworkinglist_quarantine"),
    ]

    operations = [
        migrations.AddField(
            model_name="continuingeducationadmission",
            name="authorization_analysis_folder",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Analysis folder generated when the application is validated",
            ),
        ),
    ]
