# Generated by Django 5.2.8 on 2025-12-04 16:06

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Max


def create_non_resident_working_list(apps, schema_editor):
    WorkingList = apps.get_model('admission', 'WorkingList')

    order = WorkingList.objects.aggregate(Max('order', default=0)).get('order__max', 0) + 1

    WorkingList.objects.create(
        name={
            settings.LANGUAGE_CODE_FR: 'Contingenté non-résident',
            settings.LANGUAGE_CODE_EN: 'Non-resident limited-enrolment',
        },
        admission_contingentes=['CONTINGENTE_NON_RESIDENT'],
        order=order,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0281_generaleducationadmission_non_resident_file_and_more"),
        ("base", "0721_alter_academiccalendar_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="draw_number",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Draw number"),
        ),
        migrations.AlterField(
            model_name="centralmanager",
            name="scopes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("GENERAL", "GENERAL"),
                        ("IUFC", "IUFC"),
                        ("DOCTORAT", "DOCTORAT"),
                        ("CONTINGENTE_NON_RESIDENT", "CONTINGENTE_NON_RESIDENT"),
                    ],
                    max_length=200,
                ),
                blank=True,
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="LimitedEnrolmentDelegate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="base.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role: Limited enrolment delegate",
                "verbose_name_plural": "Role: Limited enrolment delegate",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("person",),
                        name="admission_unique_limited_enrolment_delegate_by_person",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContingenteTraining",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_import_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last import at"),
                ),
                (
                    "last_bulk_notification_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Last bulk notification at"),
                ),
                (
                    "last_import_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="base.person",
                        verbose_name="Last import by",
                    ),
                ),
                (
                    "last_bulk_notification_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="base.person",
                        verbose_name="Last bulk notification by",
                    ),
                ),
                (
                    "training",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.educationgroupyear",
                        verbose_name="Training",
                    ),
                ),
                (
                    "places_number",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Number of places"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workinglist",
            name="admission_contingentes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("NON_CONTINGENTE", "Not limited-enrolment"),
                        ("CONTINGENTE_RESIDENT", "Resident limited-enrolment"),
                        ("CONTINGENTE_NON_RESIDENT", "Non-resident limited-enrolment"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=["NON_CONTINGENTE", "CONTINGENTE_RESIDENT"],
                size=None,
                verbose_name="Admission limited enrolment",
            ),
        ),
        migrations.RunPython(create_non_resident_working_list),
    ]
