# Generated by Django 5.2.8 on 2025-12-16 11:17
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
from django.db.models import Max


def create_non_resident_working_list(apps, schema_editor):
    WorkingList = apps.get_model('admission', 'WorkingList')

    order = WorkingList.objects.aggregate(Max('order', default=0)).get('order__max', 0) + 1

    WorkingList.objects.create(
        name={
            settings.LANGUAGE_CODE_FR: 'Contingenté non-résident',
            settings.LANGUAGE_CODE_EN: 'Non-resident limited-enrolment',
        },
        admission_contingentes=['CONTINGENTE_NON_RESIDENT'],
        order=order,
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "admission",
            "0281_remove_contingentetraining_last_bulk_notification_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workinglist",
            name="admission_contingentes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("NON_CONTINGENTE", "Not limited-enrolment"),
                        ("CONTINGENTE_RESIDENT", "Resident limited-enrolment"),
                        ("CONTINGENTE_NON_RESIDENT", "Non-resident limited-enrolment"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=["NON_CONTINGENTE", "CONTINGENTE_RESIDENT"],
                size=None,
                verbose_name="Admission limited enrolment",
            ),
        ),
        migrations.RunPython(create_non_resident_working_list),
    ]
