# Generated by Django 5.2.9 on 2026-01-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0280_alter_doctoratecommitteemember_unique_together"),
        (
            "admission",
            "0281_continuingeducationadmission_authorization_analysis_folder",
        ),
    ]

    operations = []
