# Generated by Django 5.2.9 on 2026-01-16 12:31

from django.db import migrations

from admission.migrations.utils.extract_experience_checklists import extract_experience_checklist


def extract_experience_checklist_migration(
    apps,
    schema_editor,
):
    extract_experience_checklist(
        base_admission_model=apps.get_model('admission', 'BaseAdmission'),
        secondary_studies_model=apps.get_model('osis_profile', 'SecondaryStudies'),
        exam_model=apps.get_model('osis_profile', 'Exam'),
        educational_experience_model=apps.get_model('osis_profile', 'EducationalExperience'),
        professional_experience_model=apps.get_model('osis_profile', 'ProfessionalExperience'),
    )

def reverse_extract_experience_checklist_migration(apps, schema_editor):
    BaseAdmission = apps.get_model('admission', 'BaseAdmission')
    SecondaryStudies = apps.get_model('osis_profile', 'SecondaryStudies')
    Exam = apps.get_model('osis_profile', 'Exam')
    EducationalExperience = apps.get_model('osis_profile', 'EducationalExperience')
    ProfessionalExperience = apps.get_model('osis_profile', 'ProfessionalExperience')


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0282_merge_20260119_1021"),
        ("osis_profile", "0038_belgianhighschooldiploma_authentification_status_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=extract_experience_checklist_migration,
            reverse_code=migrations.RunPython.noop,
        )
    ]
