# Generated by Django 5.2.8 on 2026-01-21 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0282_alter_centralmanager_scopes_limitedenrolmentdelegate"),
        ("base", "0723_academiccalendar_end_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_notified_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Non-resident notified at"
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_notified_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="base.person",
                verbose_name="Non-resident notified by",
            ),
        ),
        migrations.AlterField(
            model_name="contingentetraining",
            name="last_bulk_notification_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Last bulk notification at"
            ),
        ),
        migrations.AlterField(
            model_name="contingentetraining",
            name="last_import_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Last import at"
            ),
        ),
    ]
