# Generated by Django 5.2.8 on 2026-01-28 15:47

import django.db.models.deletion
import osis_document_components.fields
from django.db import migrations, models
from osis_mail_template import MailTemplateMigration


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0282_alter_centralmanager_scopes_limitedenrolmentdelegate"),
        ("base", "0724_alter_academiccalendar_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contingentetraining",
            name="last_bulk_notification_at",
            field=models.DateTimeField(editable=False, null=True, verbose_name="Last bulk notification at"),
        ),
        migrations.AlterField(
            model_name="contingentetraining",
            name="last_import_at",
            field=models.DateTimeField(editable=False, null=True, verbose_name="Last import at"),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_notified_at",
            field=models.DateTimeField(editable=False, null=True, verbose_name="Non-resident notified at"),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_notified_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="base.person",
                verbose_name="Non-resident notified by",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_limited_enrolment_acceptance_file",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Non-resident limited enrolment acceptance file",
            ),
        ),
        MailTemplateMigration(
            'osis-admission-contingente-acceptation',
            {
                'en': '[OSIS] : Enrolment UCLouvain – complete your file ({ares_application_number})',
                'fr-be': '[OSIS] : Inscription UCLouvain – compléter votre dossier ({ares_application_number})',
            },
            {
                'en': '''<p>Dear,</p>

<p>Please find attached the official notification of the favourable decision following
the random selection of your application for one of the limited-enrolment
courses for the {academic_year} academic year.</p>

<p>Please complete the various steps required as mentioned in the attachment to
confirm your application.</p>

<p>To retrieve your acceptance notification to be returned to us signed :</p>

<p style="text-align: center; padding-top: 5px; padding-bottom: 10px;">
    <span style="color: #dc3545; border: 1px solid #dc3545; padding: 10px; border-radius: 10px;">
        Download:
        <a
            href="{acceptance_document_link}"
            target="_blank"
            style="color: #dc3545;"
        >Acceptance notification</a>
    </span>
</p>

{required_documents_paragraph}

<p>In order to continue processing your application, the documents mentioned in your
acceptance notification must be added to your application for the {deadline_date}:</p>

<p>To submit your documents on your online application platform, including your
signed acceptance notification:</p>

<p style="text-align: center; padding-top: 5px; padding-bottom: 10px;">
    <span style="border: 1px solid; padding: 10px; border-radius: 10px;">
        <a
            href="{admission_link_front_requested_documents}"
            target="_blank"
        >{admission_link_front_requested_documents}</a>
    </span>
</p>

<p>Please note that if you already have a global account (email address and Noma), please
connect to your OSIS platform using your e-mail address ending with
@student.uclouvain.be. If you have any problems, please contact the service
desk.</p>

<p>Sincerely,</p>

<p>The Enrolment Office</p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

<p>Vous trouverez ci-joint la notification officielle de la décision favorable suite au
tirage au sort en ordre utile de votre dossier d'inscription à une des formations
contingentées pour l'année académique {academic_year}.</p>

<p>Veuillez remplir les différentes étapes indispensables, telles que mentionnées
dans le PDF ci-dessous afin de confirmer votre demande d'inscription.</p>

<p>Pour récupérer votre notification d’acceptation à nous renvoyer signée :</p>

<p style="text-align: center; padding-top: 5px; padding-bottom: 10px;">
    <span style="color: #dc3545; border: 1px solid #dc3545; padding: 10px; border-radius: 10px;">
        Télécharger :
        <a
            href="{acceptance_document_link}"
            target="_blank"
            style="color: #dc3545;"
        >Notification d’acceptation</a>
    </span>
</p>

{required_documents_paragraph}

<p>Afin de pouvoir poursuivre l’analyse de votre demande d’admission, les documents mentionnés
dans votre notification d’acceptation doivent être ajoutés obligatoirement à votre dossier en ligne
pour le {deadline_date} :</p>
<p>Pour déposer vos documents sur votre plateforme de demande en ligne, y compris votre notification
d’acception signée :</p>

<p style="text-align: center; padding-top: 5px; padding-bottom: 10px;">
    <span style="border: 1px solid; padding: 10px; border-radius: 10px;">
        <a
            href="{admission_link_front_requested_documents}"
            target="_blank"
        >{admission_link_front_requested_documents}</a>
    </span>
</p>

<p>Si vous disposez déjà d’un compte global (adresse mail UCLouvain et noma),
veuillez vous connecter à votre plateforme OSIS avec votre adresse mail se
terminant par @student.uclouvain.be.</p>

<p>Veuillez agréer l'expression de nos salutations distinguées.</p>

<p>Le Service des inscriptions</p>''',
            },
        ),
    ]
