# Generated by Django 5.2.8 on 2025-12-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0282_worklist_non_resident"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="draw_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Draw number"
            ),
        ),
    ]
