# Generated by Django 5.2.9 on 2026-01-16 12:31

from django.db import migrations

from admission.migrations.utils.extract_experience_checklist_comment import extract_experience_checklist_comment
from admission.migrations.utils.extract_experience_checklists import extract_experience_checklist
from django.conf import settings


def extract_experience_checklist_migration(apps, schema_editor):
    if settings.TESTING:
        return

    extract_experience_checklist(
        base_admission_model=apps.get_model('admission', 'BaseAdmission'),
        secondary_studies_model=apps.get_model('osis_profile', 'HighSchoolDiploma'),
        exam_model=apps.get_model('osis_profile', 'Exam'),
        educational_experience_model=apps.get_model('osis_profile', 'EducationalExperience'),
        professional_experience_model=apps.get_model('osis_profile', 'ProfessionalExperience'),
        epc_injection_model=apps.get_model('osis_profile', 'EpcInjection'),
        admission_educational_valuated_experiences_model=apps.get_model('admission', 'AdmissionEducationalValuatedExperiences'),
        inscription_programme_annuel_model=apps.get_model('epc', 'InscriptionProgrammeAnnuel'),
        admission_professional_valuated_experiences_model=apps.get_model('admission', 'AdmissionProfessionalValuatedExperiences'),
        foreign_high_school_diploma_model=apps.get_model('osis_profile', 'ForeignHighSchoolDiploma'),
        belgian_high_school_diploma_model=apps.get_model('osis_profile', 'BelgianHighSchoolDiploma'),
        admission_exam_model=apps.get_model('admission', 'AdmissionExam'),
    )

def extract_experience_checklist_comment_migration(apps, schema_editor):
    if settings.TESTING:
        return

    BaseAdmission = apps.get_model('admission', 'BaseAdmission')
    CommentEntry = apps.get_model('osis_comment', 'CommentEntry')

    extract_experience_checklist_comment(comment_model=CommentEntry, base_admission_model=BaseAdmission)



class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0284_extract_personal_data_checklist"),
        ("osis_profile", "0038_belgianhighschooldiploma_authentification_status_and_more"),
    ]

    operations = [
        migrations.RunPython(
            code=extract_experience_checklist_migration,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=extract_experience_checklist_comment_migration,
            reverse_code=migrations.RunPython.noop,
        )
    ]
