# Generated by Django 5.2.9 on 2026-02-24 10:35

import osis_document_components.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0286_extract_experience_checklists"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="bama_15_proof",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Proof of re-enrolment for the bachelor's degree (BAMA15)",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="is_concerned_by_bama_15",
            field=models.BooleanField(blank=True, null=True, verbose_name="Is concerned by BAMA15"),
        ),
    ]
