# Generated by Django 5.2.11 on 2026-03-04 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0285_alter_doctorateadmission_financability_computed_rule_situation_and_more'),
        ('admission', '0286_extract_experience_checklists'),
    ]

    operations = [
    ]
