# Generated by Django 5.2.12 on 2026-03-12 11:38

from django.db import migrations, models


def _set_tuition_fees_amount(apps, schema_editor):
    DoctorateAdmission = apps.get_model('admission', 'DoctorateAdmission')
    GeneraleducationAdmission = apps.get_model('admission', 'GeneraleducationAdmission')
    DoctorateAdmission.objects.filter(tuition_fees_amount='INSCRIPTION_REGULIERE').update(
        tuition_fees_amount='INSCRIPTION_REGULIERE_835'
    )
    GeneraleducationAdmission.objects.filter(tuition_fees_amount='INSCRIPTION_REGULIERE').update(
        tuition_fees_amount='INSCRIPTION_REGULIERE_835'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0287_merge_20260304_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='tuition_fees_amount',
            field=models.CharField(
                choices=[
                    ('INSCRIPTION_AU_ROLE', 'INSCRIPTION_AU_ROLE'),
                    ('INSCRIPTION_REGULIERE_1194', 'INSCRIPTION_REGULIERE_1194'),
                    ('INSCRIPTION_REGULIERE_835', 'INSCRIPTION_REGULIERE_835'),
                    ('DROITS_MAJORES', 'DROITS_MAJORES'),
                    ('NOUVEAUX_DROITS_MAJORES', 'NOUVEAUX_DROITS_MAJORES'),
                    ('ANCIENS_DROITS_MAJORES_2505', 'ANCIENS_DROITS_MAJORES_2505'),
                    ('ANCIENS_DROITS_MAJORES_4175', 'ANCIENS_DROITS_MAJORES_4175'),
                    ('AGREGATION', 'AGREGATION'),
                    ('MASTER_DE_SPECIALISATION_SANTE', 'MASTER_DE_SPECIALISATION_SANTE'),
                    ('CERTIFICAT_60_CREDITS', 'CERTIFICAT_60_CREDITS'),
                    ('PAS_DE_DROITS_D_INSCRIPTION', 'PAS_DE_DROITS_D_INSCRIPTION'),
                    ('CO_DIPLOMATION_1260', 'CO_DIPLOMATION_1260'),
                    ('CO_DIPLOMATION_901', 'CO_DIPLOMATION_901'),
                    ('CO_DIPLOMATION_132', 'CO_DIPLOMATION_132'),
                    ('AUTRE', 'AUTRE'),
                ],
                default='',
                max_length=50,
                verbose_name='Tuition fees amount',
            ),
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='tuition_fees_amount',
            field=models.CharField(
                choices=[
                    ('INSCRIPTION_AU_ROLE', 'INSCRIPTION_AU_ROLE'),
                    ('INSCRIPTION_REGULIERE_1194', 'INSCRIPTION_REGULIERE_1194'),
                    ('INSCRIPTION_REGULIERE_835', 'INSCRIPTION_REGULIERE_835'),
                    ('DROITS_MAJORES', 'DROITS_MAJORES'),
                    ('NOUVEAUX_DROITS_MAJORES', 'NOUVEAUX_DROITS_MAJORES'),
                    ('ANCIENS_DROITS_MAJORES_2505', 'ANCIENS_DROITS_MAJORES_2505'),
                    ('ANCIENS_DROITS_MAJORES_4175', 'ANCIENS_DROITS_MAJORES_4175'),
                    ('AGREGATION', 'AGREGATION'),
                    ('MASTER_DE_SPECIALISATION_SANTE', 'MASTER_DE_SPECIALISATION_SANTE'),
                    ('CERTIFICAT_60_CREDITS', 'CERTIFICAT_60_CREDITS'),
                    ('PAS_DE_DROITS_D_INSCRIPTION', 'PAS_DE_DROITS_D_INSCRIPTION'),
                    ('CO_DIPLOMATION_1260', 'CO_DIPLOMATION_1260'),
                    ('CO_DIPLOMATION_901', 'CO_DIPLOMATION_901'),
                    ('CO_DIPLOMATION_132', 'CO_DIPLOMATION_132'),
                    ('AUTRE', 'AUTRE'),
                ],
                default='',
                max_length=50,
                verbose_name='Tuition fees amount',
            ),
        ),
        migrations.RunPython(_set_tuition_fees_amount),
    ]
