# Generated by Django 5.2.12 on 2026-03-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0287_merge_20260304_1039"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseadmission",
            name="is_in_pursuit",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Is in pursuit"
            ),
        ),
    ]
