# Generated by Django 5.2.12 on 2026-03-11 15:48
from django.conf import settings
from django.db.models import Max, Subquery, OuterRef, F, Value
from django.db.models.functions import Coalesce
from osis_mail_template import MailTemplateMigration

import admission.models.working_list
import django.contrib.postgres.fields
import django.db.models.deletion
import osis_document_components.fields
from django.db import migrations, models

RESIDENT_STUDENT_FORM = "Dossier résident - contingentement"
RESIDENCE_CERTIFICATE = "Certificat de résidence"

SIGLES_WITH_QUOTA = ['KINE1BA', 'VETE1BA', 'LOGO1BA']


def migrate_specific_questions(apps, schema_editor):
    AdmissionFormItem = apps.get_model("admission", "AdmissionFormItem")
    GeneralEducationAdmission = apps.get_model("admission", "GeneralEducationAdmission")
    SpecificQuestionAnswer = apps.get_model("admission", "SpecificQuestionAnswer")

    internal_labels = [RESIDENT_STUDENT_FORM, RESIDENCE_CERTIFICATE]
    AdmissionFormItem.objects.filter(internal_label__in=internal_labels).update(active=False)

    GeneralEducationAdmission.objects.order_by().filter(
        baseadmission_ptr__training__acronym__in=SIGLES_WITH_QUOTA,
    ).annotate(
        residence_certificate_answer=Subquery(
            SpecificQuestionAnswer.objects.filter(
                admission=OuterRef("pk"),
                form_item__internal_label=RESIDENCE_CERTIFICATE,
            ).values('file')[:1]
        ),
        residence_student_form_answer=Subquery(
            SpecificQuestionAnswer.objects.filter(
                admission=OuterRef("pk"),
                form_item__internal_label=RESIDENT_STUDENT_FORM,
            ).values('file')[:1]
        ),
    ).update(
        residence_certificate=Coalesce(F('residence_certificate_answer'), Value([])),
        residence_student_form=Coalesce(F('residence_student_form_answer'), Value([])),
    )


def create_non_resident_working_list(apps, schema_editor):
    WorkingList = apps.get_model('admission', 'WorkingList')

    order = WorkingList.objects.aggregate(Max('order', default=0)).get('order__max', 0) + 1

    WorkingList.objects.create(
        name={
            settings.LANGUAGE_CODE_FR: 'Contingenté non-résident',
            settings.LANGUAGE_CODE_EN: 'Non-resident limited-enrolment',
        },
        admission_contingentes=['CONTINGENTE_NON_RESIDENT'],
        order=order,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0287_merge_20260304_1039"),
        ("base", "0728_academiccalendar_end_time_and_more"),
        ("reference", "0019_scholarship"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContingenteTraining",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "places_number",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Number of places"
                    ),
                ),
                (
                    "last_import_at",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Last import at"
                    ),
                ),
                (
                    "last_bulk_notification_at",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Last bulk notification at",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LimitedEnrolmentDelegate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Role: Limited enrolment delegate",
                "verbose_name_plural": "Role: Limited enrolment delegate",
            },
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="ares_application_number",
            field=models.CharField(
                default="",
                editable=False,
                max_length=30,
                verbose_name="Ares application number for trainings with quota",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="draw_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Draw number"
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_file",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Non-resident file",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_limited_enrolment_acceptance_file",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Non-resident limited enrolment acceptance file",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_notified_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Non-resident notified at"
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_notified_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="base.person",
                verbose_name="Non-resident notified by",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_with_second_year_enrolment",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="Do you intend to make an enrolment directly for the second year?",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="non_resident_with_second_year_enrolment_form",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Non-resident enrolment form for an enrolment beyond the first 60 credits",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="quota_admission_receipt",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Quota admission receipt",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="residence_certificate",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Residence certificate",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="residence_student_form",
            field=osis_document_components.fields.FileField(
                base_field=models.UUIDField(),
                blank=True,
                default=list,
                size=None,
                verbose_name="Resident student form",
            ),
        ),
        migrations.AddField(
            model_name="workinglist",
            name="admission_contingentes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("NON_CONTINGENTE", "Not limited-enrolment"),
                        ("CONTINGENTE_RESIDENT", "Resident limited-enrolment"),
                        ("CONTINGENTE_NON_RESIDENT", "Non-resident limited-enrolment"),
                    ],
                    max_length=64,
                ),
                blank=True,
                default=admission.models.working_list.get_admission_contingentes_default,
                size=None,
                verbose_name="Admission limited enrolment",
            ),
        ),
        migrations.AlterField(
            model_name="centralmanager",
            name="scopes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("GENERAL", "GENERAL"),
                        ("IUFC", "IUFC"),
                        ("DOCTORAT", "DOCTORAT"),
                        ("CONTINGENTE_NON_RESIDENT", "CONTINGENTE_NON_RESIDENT"),
                    ],
                    max_length=200,
                ),
                blank=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="generaleducationadmission",
            name="refusal_type",
            field=models.CharField(
                choices=[
                    ("REFUS_EQUIVALENCE", "REFUS_EQUIVALENCE"),
                    ("REFUS_BAC_HUE_ACADEMIQUE", "REFUS_BAC_HUE_ACADEMIQUE"),
                    (
                        "REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER",
                        "REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER",
                    ),
                    (
                        "REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER_SPECIALISATION",
                        "REFUS_ARTICLE_95_SIC_CONDITIONS_PUBLIEES_MASTER_SPECIALISATION",
                    ),
                    ("REFUS_ARTICLE_95_CERTIFICAT", "REFUS_ARTICLE_95_CERTIFICAT"),
                    ("REFUS_ARTICLE_95_ACCES_S4", "REFUS_ARTICLE_95_ACCES_S4"),
                    ("REFUS_ARTICLE_95_ACCES_S5", "REFUS_ARTICLE_95_ACCES_S5"),
                    (
                        "REFUS_ARTICLE_95_ACCES_MS_ENSEIGNEMENT",
                        "REFUS_ARTICLE_95_ACCES_MS_ENSEIGNEMENT",
                    ),
                    ("REFUS_ARTICLE_95_JURY", "REFUS_ARTICLE_95_JURY"),
                    (
                        "REFUS_ARTICLE_95_GENERIQUE_IRRECEVABILITE",
                        "REFUS_ARTICLE_95_GENERIQUE_IRRECEVABILITE",
                    ),
                    ("REFUS_AGREGATION", "REFUS_AGREGATION"),
                    (
                        "REFUS_ARTICLE_96_UE_HUE_ASSIMILES",
                        "REFUS_ARTICLE_96_UE_HUE_ASSIMILES",
                    ),
                    (
                        "REFUS_ARTICLE_96_HUE_RAISON_ACADEMIQUE",
                        "REFUS_ARTICLE_96_HUE_RAISON_ACADEMIQUE",
                    ),
                    ("REFUS_DOSSIER_TARDIF", "REFUS_DOSSIER_TARDIF"),
                    ("REFUS_COMPLEMENT_TARDIF", "REFUS_COMPLEMENT_TARDIF"),
                    (
                        "REFUS_ARTICLE_96_HUE_NON_PROGRESSION",
                        "REFUS_ARTICLE_96_HUE_NON_PROGRESSION",
                    ),
                    (
                        "REFUS_ARTICLE_95_CONTINGENTES_NR_NON_FINANCABLE",
                        "REFUS_ARTICLE_95_CONTINGENTES_NR_NON_FINANCABLE",
                    ),
                    (
                        "REFUS_ARTICLE_95_CONTINGENTES_NR_DOSSIER_INCOMPLET",
                        "REFUS_ARTICLE_95_CONTINGENTES_NR_DOSSIER_INCOMPLET",
                    ),
                    (
                        "REFUS_ARTICLE_95_CONTINGENTES_NR_TITRE_D_ACCES",
                        "REFUS_ARTICLE_95_CONTINGENTES_NR_TITRE_D_ACCES",
                    ),
                    (
                        "REFUS_ARTICLE_95_CONTINGENTES_NR_EXCLUSION",
                        "REFUS_ARTICLE_95_CONTINGENTES_NR_EXCLUSION",
                    ),
                    ("REFUS_LIBRE", "REFUS_LIBRE"),
                ],
                default="",
                max_length=64,
                verbose_name="Refusal type",
            ),
        ),
        migrations.AddConstraint(
            model_name="generaleducationadmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ares_application_number", ""), _negated=True),
                fields=("ares_application_number",),
                name="unique_admission_general_education_ares_application_number",
            ),
        ),
        migrations.AddField(
            model_name="contingentetraining",
            name="last_bulk_notification_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="base.person",
                verbose_name="Last bulk notification by",
            ),
        ),
        migrations.AddField(
            model_name="contingentetraining",
            name="last_import_by",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="base.person",
                verbose_name="Last import by",
            ),
        ),
        migrations.AddField(
            model_name="contingentetraining",
            name="training",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.educationgroupyear",
                verbose_name="Training",
            ),
        ),
        migrations.AddField(
            model_name="limitedenrolmentdelegate",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="base.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="limitedenrolmentdelegate",
            constraint=models.UniqueConstraint(
                fields=("person",),
                name="admission_unique_limited_enrolment_delegate_by_person",
            ),
        ),
        MailTemplateMigration(
            'osis-admission-contingente-acceptation',
            {
                'en': '[OSIS] : Enrolment UCLouvain – complete your file ({ares_application_number})',
                'fr-be': '[OSIS] : Inscription UCLouvain – compléter votre dossier ({ares_application_number})',
            },
            {
                'en': '''<p>Dear,</p>

<p>Please find attached the official notification of the favourable decision following
the random selection of your application for one of the limited-enrolment
courses for the {academic_year} academic year.</p>

<p>Please complete the various steps required as mentioned in the attachment to
confirm your application.</p>

<p>To retrieve your acceptance notification to be returned to us signed :</p>

<p style="text-align: center; padding-top: 5px; padding-bottom: 10px;">
    <span style="color: #dc3545; border: 1px solid #dc3545; padding: 10px; border-radius: 10px;">
        Download:
        <a
            href="{acceptance_document_link}"
            target="_blank"
            style="color: #dc3545;"
        >Acceptance notification</a>
    </span>
</p>

{required_documents_paragraph}

<p>In order to continue processing your application, the documents mentioned in your
acceptance notification must be added to your application for the {deadline_date}:</p>

<p>To submit your documents on your online application platform, including your
signed acceptance notification:</p>

<p style="text-align: center; padding-top: 5px; padding-bottom: 10px;">
    <span style="border: 1px solid; padding: 10px; border-radius: 10px;">
        <a
            href="{admission_link_front_requested_documents}"
            target="_blank"
        >{admission_link_front_requested_documents}</a>
    </span>
</p>

<p>Please note that if you already have a global account (email address and Noma), please
connect to your OSIS platform using your e-mail address ending with
@student.uclouvain.be. If you have any problems, please contact the service
desk.</p>

<p>Sincerely,</p>

<p>The Enrolment Office</p>
    ''',
                'fr-be': '''<p>Bonjour,</p>

<p>Vous trouverez ci-joint la notification officielle de la décision favorable suite au
tirage au sort en ordre utile de votre dossier d'inscription à une des formations
contingentées pour l'année académique {academic_year}.</p>

<p>Veuillez remplir les différentes étapes indispensables, telles que mentionnées
dans le PDF ci-dessous afin de confirmer votre demande d'inscription.</p>

<p>Pour récupérer votre notification d’acceptation à nous renvoyer signée :</p>

<p style="text-align: center; padding-top: 5px; padding-bottom: 10px;">
    <span style="color: #dc3545; border: 1px solid #dc3545; padding: 10px; border-radius: 10px;">
        Télécharger :
        <a
            href="{acceptance_document_link}"
            target="_blank"
            style="color: #dc3545;"
        >Notification d’acceptation</a>
    </span>
</p>

{required_documents_paragraph}

<p>Afin de pouvoir poursuivre l’analyse de votre demande d’admission, les documents mentionnés
dans votre notification d’acceptation doivent être ajoutés obligatoirement à votre dossier en ligne
pour le {deadline_date} :</p>
<p>Pour déposer vos documents sur votre plateforme de demande en ligne, y compris votre notification
d’acception signée :</p>

<p style="text-align: center; padding-top: 5px; padding-bottom: 10px;">
    <span style="border: 1px solid; padding: 10px; border-radius: 10px;">
        <a
            href="{admission_link_front_requested_documents}"
            target="_blank"
        >{admission_link_front_requested_documents}</a>
    </span>
</p>

<p>Si vous disposez déjà d’un compte global (adresse mail UCLouvain et noma),
veuillez vous connecter à votre plateforme OSIS avec votre adresse mail se
terminant par @student.uclouvain.be.</p>

<p>Veuillez agréer l'expression de nos salutations distinguées.</p>

<p>Le Service des inscriptions</p>''',
            },
        ),
        MailTemplateMigration(
            'osis-admission-contingente-soumission',
            {
                'en': '',
                'fr-be': "[OSIS] Dépôt d'un dossier non-résident pour une formation contingentée {ares_application_number}",
            },
            {
                'en': '',
                'fr-be': '''<p>Madame, Monsieur,</p>
<p>Nous accusons bonne réception du dépôt de votre dossier « non-résident » en version digitale,
pour l'une des formations contingentées : {training_title}.</p>
<p>Veuillez télécharger votre accusé de réception officiel.</p>
<p style="text-align: center; padding-top: 5px; padding-bottom: 10px;">
    <span style="color: #dc3545; border: 1px solid #dc3545; padding: 10px; border-radius: 10px;">
        Télécharger :
        <a
            href="{receipt_document_link}"
            target="_blank"
            style="color: #dc3545;"
        >Accusé de réception</a>
    </span>
</p>
<p>Cet accusé reprend votre numéro de dossier qui sera utilisé pour le tirage au sort.</p>
<p>Veillez donc à le conserver précieusement.</p>
<p>Pour plus d'informations sur les modalités qui encadrent ces études contingentées (dates du tirage au sort,
communication des résultats, ...), nous vous invitons à consulter la page
<a href="https://uclouvain.be/fr/etudier/inscriptions/etudes-contingentees.html">https://uclouvain.be/fr/etudier/inscriptions/etudes-contingentees.html</a>
qui sera mise à jour à chaque nouvelle étape de la procédure.</p>
<p>Nous vous remercions d'avoir choisi notre Institution.</p>
<p>Le Service des inscriptions de l'UCLouvain</p>
                    ''',
            },
        ),
        migrations.RunPython(migrate_specific_questions),
        migrations.RunPython(create_non_resident_working_list),
    ]
