# Generated by Django 5.2.12 on 2026-03-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0286_alter_doctorateadmission_tuition_fees_amount_and_more'),
        ('admission', '0287_merge_20260304_1039'),
    ]

    operations = [
    ]
