# Generated by Django 5.2.12 on 2026-03-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0288_baseadmission_is_in_pursuit"),
    ]

    operations = [
        migrations.AddField(
            model_name="generaleducationadmission",
            name="several_admissions_same_cycle_same_year_justification",
            field=models.TextField(
                blank=True,
                verbose_name="Text justification to create several applications for a same cycle and a same year.",
                default="",
            ),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="several_admissions_same_cycle_same_year_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "ANNULER_PRECEDENTES_DEMANDES",
                        "Create this new application in and cancel your other ones",
                    ),
                    ("SUIVRE_EN_PARALLELE", "Take several courses at the same time"),
                ],
                default="",
                max_length=30,
                verbose_name="Reason to create several applications for a same cycle and a same year.",
            ),
        ),
    ]
