# Generated by Django 5.2.12 on 2026-04-02 18:06

from django.db import migrations
from django.db.models import JSONField, Func, Value, F


def migrate_checklist_toilette(apps, schema_editor):
    BaseAdmission = apps.get_model('admission', 'BaseAdmission')

    BaseAdmission.objects.filter(
        generaleducationadmission__isnull=False, checklist__current__parcours_anterieur__statut='GEST_EN_COURS'
    ).update(
        checklist=Func(
            F('checklist'),
            Value(['current', 'parcours_anterieur', 'extra']),
            Value({'en_cours': 'toilette'}, output_field=JSONField()),
            function='jsonb_set',
            output_field=JSONField(),
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0290_generaleducationadmission_bama_15_proof_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_checklist_toilette),
    ]
