# Generated by Django 5.2.12 on 2026-04-10 10:22

from django.db import migrations, models


def migrate_is_in_pursuit(apps, schema_editor):
    GeneralEducationAdmission = apps.get_model("admission", "GeneralEducationAdmission")
    GeneralEducationAdmission.objects.filter(is_in_pursuit__isnull=True).update(is_in_pursuit=False)


class Migration(migrations.Migration):

    dependencies = [
        ("admission", "0291_in_pursuit_fields"),
    ]

    operations = [
        migrations.RunPython(migrate_is_in_pursuit),
        migrations.AlterField(
            model_name="generaleducationadmission",
            name="is_in_pursuit",
            field=models.BooleanField(blank=True, default=False, verbose_name="Is in pursuit"),
        ),
        migrations.AddField(
            model_name="generaleducationadmission",
            name="is_belgian_access_diploma",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NON_CONCERNE", "NON_CONCERNE"),
                    ("OUI", "OUI"),
                    ("NON", "NON"),
                ],
                default="NON_CONCERNE",
                max_length=30,
                verbose_name="Is belgian access diploma",
            ),
        ),
    ]
