# Generated by Django 5.2.13 on 2026-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admission", "0291_in_pursuit_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounting",
            name="verified_debt_clearance",
            field=models.BooleanField(default=False, verbose_name="Verified debt clearance"),
        ),
    ]
