# Generated by Django 5.2.13 on 2026-04-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0291_in_pursuit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorateadmission',
            name='admission_requirement',
            field=models.CharField(blank=True, choices=[('NON_CONCERNE', 'Non concerné'), ('SNU_PASSERELLE_1', 'SNU Passerelle 1'), ('SNU_PASSERELLE_2', 'SNU Passerelle 2'), ('SNU_PASSERELLE_3', 'SNU Passerelle 3'), ('VAE', 'VAE'), ('PROGRAMME_AMENAGE', 'Progr. aménagé'), ('VALORISATION_180_ECTS', 'Valorisation 180'), ('VALORISATION_240_ECTS', 'Valorisation 240'), ('VALORISATION_300_ECTS', 'Valorisation 300'), ('SECONDAIRE', 'Secondaire'), ('BAC', 'Bachelier univ'), ('BAC_EPM', 'BAMA15 (1ADP)'), ('BAMA15', 'BAMA15'), ('BAC_SEUL_15_CREDITS_MAX_EPM', 'Bachelier seul 15 crédits max (BAC - EPM)'), ('BAC_15_CREDITS_MAX_MASTER_EPM', 'Bachelier 15 crédits max + Master(BAC - EPM)'), ('MASTER', 'Master univ'), ('UNI_SNU_AUTRE', 'UNI/SNU Autres'), ('PARCOURS', 'Parcours'), ('EXAMEN_ADMISSION', "Examen d'admission"), ('SNU_TYPE_COURT', 'Passerelle'), ('SNU_TYPE_COURT_HORS_PASSERELLE', 'SNU Type court (hors passerelle)'), ('SNU_TYPE_LONG_1ER_CYCLE', 'SNU Type long 1er cycle'), ('SNU_TYPE_LONG_2EME_CYCLE', 'SNU Type long 2ème cycle'), ('MASTER_EPM', 'Master - EPM'), ('BAC_MASTER_ANTICIPE', 'BAMA30'), ('INDETERMINE', 'Indéterminé')], default='', max_length=30, verbose_name='Admission requirement'),
        ),
        migrations.AlterField(
            model_name='generaleducationadmission',
            name='admission_requirement',
            field=models.CharField(blank=True, choices=[('NON_CONCERNE', 'Non concerné'), ('SNU_PASSERELLE_1', 'SNU Passerelle 1'), ('SNU_PASSERELLE_2', 'SNU Passerelle 2'), ('SNU_PASSERELLE_3', 'SNU Passerelle 3'), ('VAE', 'VAE'), ('PROGRAMME_AMENAGE', 'Progr. aménagé'), ('VALORISATION_180_ECTS', 'Valorisation 180'), ('VALORISATION_240_ECTS', 'Valorisation 240'), ('VALORISATION_300_ECTS', 'Valorisation 300'), ('SECONDAIRE', 'Secondaire'), ('BAC', 'Bachelier univ'), ('BAC_EPM', 'BAMA15 (1ADP)'), ('BAMA15', 'BAMA15'), ('BAC_SEUL_15_CREDITS_MAX_EPM', 'Bachelier seul 15 crédits max (BAC - EPM)'), ('BAC_15_CREDITS_MAX_MASTER_EPM', 'Bachelier 15 crédits max + Master(BAC - EPM)'), ('MASTER', 'Master univ'), ('UNI_SNU_AUTRE', 'UNI/SNU Autres'), ('PARCOURS', 'Parcours'), ('EXAMEN_ADMISSION', "Examen d'admission"), ('SNU_TYPE_COURT', 'Passerelle'), ('SNU_TYPE_COURT_HORS_PASSERELLE', 'SNU Type court (hors passerelle)'), ('SNU_TYPE_LONG_1ER_CYCLE', 'SNU Type long 1er cycle'), ('SNU_TYPE_LONG_2EME_CYCLE', 'SNU Type long 2ème cycle'), ('MASTER_EPM', 'Master - EPM'), ('BAC_MASTER_ANTICIPE', 'BAMA30'), ('INDETERMINE', 'Indéterminé')], default='', max_length=30, verbose_name='Admission requirement'),
        ),
    ]
